### ISSUE TITLE
Display HD44780 small mistake

### ISSUE THREAD

**Issue by ik1whn** [g4klx/MMDVMHost#101]
Display 20x4, the fourth line (mmdvm idle) is not cleared in listen mode

**Comment by g0wfv** [comment]
I'd removed an ::lcdClear() statement I thought was redundant!  I've now
put it back in and submitted a pull request to Jon's main code.

Tony

On Sun, Jun 19, 2016 at 3:48 PM ik1whn <notifications@github.com> wrote:

> Display 20x4, the fourth line (mmdvm idle) is not cleared in listen mode
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/g4klx/MMDVMHost/issues/101>, or mute the thread
> <https://github.com/notifications/unsubscribe/AQf_4tErG3uOSiB5Vz9fBzGkMiK28S44ks5qNVangaJpZM4I5Lhq>
> .
>
-- 

A J Corbett

G0WFV
