### ISSUE TITLE
DVMEGA PI support

### ISSUE THREAD

**Issue by lb5je** [g4klx/MMDVMHost#105]
Has DVMEGA PI support been broken? Using firmware version 2.29a. The DVMEGA is responding and working OK using G4KLX dstarrepeaterd.

M: 2016-06-22 17:55:18.749 MMDVMHost-20160614 is starting
I: 2016-06-22 17:55:18.749 Modem Parameters
I: 2016-06-22 17:55:18.749 Port: /dev/ttyAMA0
I: 2016-06-22 17:55:18.750 RX Invert: yes
I: 2016-06-22 17:55:18.750 TX Invert: yes
I: 2016-06-22 17:55:18.750 PTT Invert: no
I: 2016-06-22 17:55:18.751 TX Delay: 100ms
I: 2016-06-22 17:55:18.751 DMR Delay: 0 (0.0ms)
I: 2016-06-22 17:55:18.751 RX Level: 50%
I: 2016-06-22 17:55:18.751 TX Level: 50%
I: 2016-06-22 17:55:18.752 RX Frequency: 433637500Hz
I: 2016-06-22 17:55:18.752 TX Frequency: 433637500Hz
I: 2016-06-22 17:55:18.752 Osc. Offset: 0ppm
M: 2016-06-22 17:55:18.753 Opening the MMDVM
E: 2016-06-22 17:55:28.577 Unable to read the firmware version after six attempts

**Comment by g0wfv** [comment]
Ensure dstarrepeaterd isn't trying to access the software at the same time
ie shut it down.

On Wed, 22 Jun 2016, 19:31 lb5je, <notifications@github.com> wrote:

> Has DVMEGA PI support been broken? Using firmware version 2.29a. The
> DVMEGA is responding and working OK using G4KLX dstarrepeaterd.
>
> M: 2016-06-22 17:55:18.749 MMDVMHost-20160614 is starting
> I: 2016-06-22 17:55:18.749 Modem Parameters
> I: 2016-06-22 17:55:18.749 Port: /dev/ttyAMA0
> I: 2016-06-22 17:55:18.750 RX Invert: yes
> I: 2016-06-22 17:55:18.750 TX Invert: yes
> I: 2016-06-22 17:55:18.750 PTT Invert: no
> I: 2016-06-22 17:55:18.751 TX Delay: 100ms
> I: 2016-06-22 17:55:18.751 DMR Delay: 0 (0.0ms)
> I: 2016-06-22 17:55:18.751 RX Level: 50%
> I: 2016-06-22 17:55:18.751 TX Level: 50%
> I: 2016-06-22 17:55:18.752 RX Frequency: 433637500Hz
> I: 2016-06-22 17:55:18.752 TX Frequency: 433637500Hz
> I: 2016-06-22 17:55:18.752 Osc. Offset: 0ppm
> M: 2016-06-22 17:55:18.753 Opening the MMDVM
> E: 2016-06-22 17:55:28.577 Unable to read the firmware version after six
> attempts
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/g4klx/MMDVMHost/issues/105>, or mute the thread
> <https://github.com/notifications/unsubscribe/AQf_4tn5mKBi9YM4v3i-cs5KGcfcgwudks5qOX-OgaJpZM4I8FUd>
> .
>
-- 

A J Corbett

G0WFV

**Comment by lb5je** [comment]
dstarrepeaterd is not running. Any debugging I can turn on to get some extra output?

LB5JE - Hans Jørgen

**Comment by g0wfv** [comment]
Have you restarted the Pi?  Dstarrepeaterd uses one protocol whereas
mmdvmhost uses another. The dvmega requires a power cycle to swap between
the two.

https://groups.yahoo.com/neo/groups/mmdvm/conversations/messages/5546

On Thu, 23 Jun 2016, 21:22 lb5je, <notifications@github.com> wrote:

> dstarrepeaterd is not running. Any debugging I can turn on to get some
> extra output?
>
> LB5JE - Hans Jørgen
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/g4klx/MMDVMHost/issues/105#issuecomment-228171853>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQf_4lKMi_kVL4s4Mo7zGAX-Zy624hrZks5qOur-gaJpZM4I8FUd>
> .
>
-- 

A J Corbett

G0WFV

**Comment by lb5je** [comment]
The power cycle did the trick, a big thanks.

73 de LB5JE
