### ISSUE TITLE
Daemon mode

### ISSUE THREAD

**Issue by lb5je** [g4klx/MMDVMHost#113]
Hi, gets "Cannot open device - /dev/ttyAMA0" when trying to run MMDVMHost in daemon mode. Have done the commands from README.Daemon.

73 de LB5JE

**Comment by g0wfv** [comment]
Can you open the port in non daemon mode?

On Fri, 1 Jul 2016, 19:05 lb5je, <notifications@github.com> wrote:

> Hi, gets "Cannot open device - /dev/ttyAMA0" when trying to run MMDVMHost
> in daemon mode. Have done the commands from README.Daemon.
>
> 73 de LB5JE
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/g4klx/MMDVMHost/issues/113>, or mute the thread
> <https://github.com/notifications/unsubscribe/AQf_4hBSEItleVcPXsukMEbRcjklGe0aks5qRVbhgaJpZM4JDXFI>
> .
>
-- 

A J Corbett

G0WFV

**Comment by lb5je** [comment]
Yes, working OK in non daemon mode.

73 de LB5JE

**Comment by g0wfv** [comment]
and what does the out put from the command 'groups mmdvm' look like?

On Fri, Jul 1, 2016 at 7:58 PM lb5je <notifications@github.com> wrote:

> Yes, working OK in non daemon mode.
>
> 73 de LB5JE
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/g4klx/MMDVMHost/issues/113#issuecomment-230023404>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQf_4j2lABMv66K1K7t4Oyyo76im5D9jks5qRWNHgaJpZM4JDXFI>
> .
>
-- 

A J Corbett

G0WFV

**Comment by lb5je** [comment]
opendv@raspberrypi ~/MMDVMHost $ sudo groups mmdvm
mmdvm : mmdvm dialout

**Comment by g0wfv** [comment]
I'm puzzled why it's not working then?

What does 'ls -l /dev/ttyAMA0' give you

On Fri, Jul 1, 2016 at 8:22 PM lb5je <notifications@github.com> wrote:

> opendv@raspberrypi ~/MMDVMHost $ sudo groups mmdvm
> mmdvm : mmdvm dialout
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/g4klx/MMDVMHost/issues/113#issuecomment-230028323>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQf_4lo-LeDYF6gqq6elLR3dW0Zk9sXkks5qRWj5gaJpZM4JDXFI>
> .
>
-- 

A J Corbett

G0WFV

**Comment by lb5je** [comment]
opendv@raspberrypi ~/MMDVMHost $ ls -l /dev/ttyAMA0 
crw-rw---T 1 root dialout 204, 64 Jul  1  2016 /dev/ttyAMA0

**Comment by lb5je** [comment]
Ah, it was the user rights on log file.

**Comment by lb5je** [comment]
Strange it works when it self wants to ;-)

**Comment by lb5je** [comment]
Seems it fails when run from rc.local or via sudo.

**Comment by g0wfv** [comment]
are you using a RPi?

**Comment by lb5je** [comment]
Yes, a RPi.

**Comment by lb5je** [comment]
Seems I had to also add the user root to the dial out group.

**Comment by lb5je** [comment]
Still not possible to get the MMDVMHost to start from rc.local. Must be some access rights mixup...

**Comment by lb5je** [comment]
If I call /home/opendv/MMDVMHost/MMDVMHost from rc.local MMDVMHost fails to start with this in the log:
M: 2016-07-10 17:58:47.480 Opening the MMDVM
E: 2016-07-10 17:58:47.480 Cannot open device - /dev/ttyAMA0

But if I then sudo su and start it manually via /home/opendv/MMDVMHost/MMDVMHost it starts OK with this in the log: 
M: 2016-07-10 18:04:01.234 Opening the MMDVM
I: 2016-07-10 18:04:03.245 MMDVM protocol version: 1, description: DVMEGA HR2.29

Both times the MMDVMHost log file is created by the mmdvm user. Beginning to loose most of my hair :-) Could it be that /dev/ttyAMA0 is not ready when /etc/rc.local is run? What is the diff, as far as I know rc.local is run by root?

LB5JE

**Comment by phl0** [comment]
Maybe the device /dev/ttyAMA0 is not created yet when rc.local starts
MMDVMHost? You could for example add an "ls -la /dev/ttyAMA0 >
/tmp/AMA0.txt" to rc.local. What is the content of this file if you have
a look at it when booting has finished?

**Comment by lb5je** [comment]
A good theory but it's there. 
opendv@raspberrypi ~ $ cat /tmp/AMA0.txt 
crw-rw---T 1 root dialout 204, 64 Jan  1  1970 /dev/ttyAMA0

I also tried to copy the MMDVMHost file to /usr/local/bin with no difference.

LB5JE

**Comment by phl0** [comment]
Okay. Maybe anything else blocking the port while booting? What does the
output of "ps aux | grep ttyAMA0 > /tmp/AMA0.txt" give?

Or maybe give it a try with a sleep for several seconds in rc.local
before starting MMDVMHost?

**Comment by lb5je** [comment]
Now it starts after, upgraded to Debian Jessie and starts MMDVMHost with sudo from rc.local. 
But now the log is lost :-)

LB5JE
