### ISSUE TITLE
Strange strings on hd44780 display 

### ISSUE THREAD

**Issue by iw9grl** [g4klx/MMDVMHost#118]
After the yesterday updated strange strings appear like this:

![img_20160705_213016](https://cloud.githubusercontent.com/assets/16877668/16597316/933359b2-42f8-11e6-80e6-b53b0c87f3f0.jpg)

73

**Comment by g0wfv** [comment]
How do you get your code?  (Yahoo group or github?)

What version (if Yahoo group code) or commit (if github code) did you upgrade from and to?

When you do a 'locale' command, what is the output?

What was the time when you took this photo? (01:30:18 or 21:30:18?)

How do you compile the code?  ('make clean ; make' or just a 'make' without doing a 'make clean' first?)

**Comment by g0wfv** [comment]
In addition, what modes do you have configured? (D-STAR, DMR, YSF)

**Comment by g0wfv** [comment]
I've reconfigured my screen to think it's wider than it is, the end result being that it's running the same code that positions the clock on the LCD that yours will be.  A 16x2 has explicit code to position the clock, whereas any other size shares code which dynamically works out where the clock should display.  I'm unable to recreate your symptoms and my date/time display correctly.

I initially thought it may be something to do with the scrolling text not being turned off before returning to idle (that's the only thing that I can think that positions text on the same line as the time), but it doesn't seem to be that. 

I have however found another bug in the logic that affects 2 line displays greater than 16 chars wide (ie, 40x2!)  I've fixed that but as I say, can't recreate your symptoms.

**Comment by iw9grl** [comment]
Hi Tony
The code is from github with git pull * the previous before your update ) .

About the output, if you need, I can take some pictures of the display in the cases that you need.

The time was 21:30.

I compile the code using : make -f Makefile.Pi.HD44780 and before I use the make clean command .

I configured the DMR and DSTAR mode ( C4FM not used ) 

thank you for your appreciated support.

73 de Daniele IW9GRL

**Comment by g0wfv** [comment]
I've been running with a 20x4 screen for a few weeks now and have not encountered this issue.  Unless it is recurrent for you and you can reproduce it, I am inclined to beleive it was a one off.

I have seen one occurrence of another LCD related "funny" when the cursor appeared (it is commanded OFF in the code" and put this down to the LCD disregarding the command for that one instance of MMDVMHost - a restart cleared it and I've not seen a re-occurrence!

Can this be closed?
