### ISSUE TITLE
Error compiling Makefile.Pi.HD44780

### ISSUE THREAD

**Issue by iw9grl** [g4klx/MMDVMHost#124]
After the last update the compile of Makefile.Pi.HD44780 failed !!!

thank you
73 de IW9GRL

**Comment by phl0** [comment]
Confirmed. Will come up with a bugfix in 1/2 hour.

**Comment by iw9grl** [comment]
Thank you so much
73

**Comment by phl0** [comment]
I submitted a PR to fix this. See https://github.com/g4klx/MMDVMHost/pull/125. As soon as that is merged into the main branch it should work again.
I guess @hacknix forgot the other Makefiles in 66415e00.

**Comment by hacknix** [comment]
On 13/07/16 19:07, Florian (DF2ET) wrote:
>
> I submitted a PR to fix this. See #125
> <https://github.com/g4klx/MMDVMHost/pull/125>. As soon as that is
> merged into the main branch it should work again.
> I guess @hacknix <https://github.com/hacknix> forgot the other
> Makefiles in 66415e0
> <https://github.com/g4klx/MMDVMHost/commit/66415e004ee589a90bf74cc26e9b56615695380c>.
>
>
>
Thanks Florian. I will be sure not to make that mistake again ;-)

Simon

**Comment by phl0** [comment]
>Thanks Florian. I will be sure not to make that mistake again ;-)

No problem at all.

**Comment by phl0** [comment]
@IW9GRL: Jonathan merged my PR into bis repo. Would you please test and report? If it works you can close the issue. If not please comment. Thank you

**Comment by iw9grl** [comment]
yes it works!!!!  thank you so much 
73

**Comment by phl0** [comment]
np. Thank you for the feedback.
