### ISSUE TITLE
Separate TX audio setting for each supported mode

### ISSUE THREAD

**Issue by dd5xl** [g4klx/MMDVMHost#136]
TX audio setting in mmdvm.ini should be splitted to allow different settings for each supported digital mode rather than a global setting in the [modem] section. This allows fine tuning of the modem audio settings to gain optimum performance for each mode.
Second approach would be to keep a global value in the [modem] section and add an additional correction value for each digital mode.

**Comment by g4klx** [comment]
I have done as you asked. TXLevel sets all of them, you can set them separately also, or just override the value for specific modes. There are examples in the example MMDVM.ini file.

**Comment by dd5xl** [comment]
Wow, that was a really fast integration! Thanks for the changes, will check tonight how it works!
73 de Bert
