### ISSUE TITLE
Last git , strange message during make ......

### ISSUE THREAD

**Issue by iw9grl** [g4klx/MMDVMHost#146]
DMRAccessControl.cpp: In static member function 'static unsigned int DMRAccessControl::DstIdRewrite(unsigned int, unsigned int, unsigned int, bool)':
DMRAccessControl.cpp:219:94: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

73

**Comment by YV5OF** [comment]
Hi,

Same error from Make process :  

g++ -g -O3 -Wall -std=c++0x -pthread -c -o DMRAccessControl.o DMRAccessControl.cpp
DMRAccessControl.cpp: In static member function ‘static unsigned int DMRAccessControl::DstIdRewrite(unsigned int, unsigned int, unsigned int, bool)’:
DMRAccessControl.cpp:219:94: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   } else if (did == 9 && m_dstRewriteID != 9 && m_dstRewriteID != 0 && (m_time + m_callHang) > currenttime) {
                                                                                              ^

**Comment by iw9grl** [comment]
last git same error using Makefile.Pi.HD44780

**Comment by iball** [comment]
Saw the same issue here.

**Comment by vk5zea** [comment]
I too observed this same error.

**Comment by g0wfv** [comment]
Fixed with #155
