### ISSUE TITLE
 DMRLookup - Not loading DMR Ids to the callsign lookup table

### ISSUE THREAD

**Issue by pjao** [g4klx/MMDVMHost#150]
From last pull, it starts to not loading DMR Ids as it was used to.

Last time on logs, after update was this morning.

I: 2016-09-22 11:30:26.004 Loaded 43359 DMR Ids to the callsign lookup table

**Comment by iw9grl** [comment]
confirm!!!  same problem

**Comment by pjao** [comment]
Fix with #151
