### ISSUE TITLE
DMRLookup - Not loading DMR Ids to the callsign lookup table (Again)

### ISSUE THREAD

**Issue by pjao** [g4klx/MMDVMHost#160]
From last pull, it starts to not loading DMR Ids as it was used to.

Last time on logs, after update was this morning.

Tried to see "Fix reading of IDs #151" but no longer there...

**Comment by g4klx** [comment]
The log message about loading IDs has changed and also its position, it no longer says DMR as it's also used for P25. Is it still converting IDs to callsigns?

**Comment by pjao** [comment]
Hi,

Nop... It's not converting IDs to callsigns.

It seams it is not loading DMR Ids to the callsign lookup table.

M: 2016-09-29 10:25:01.797 DMR Slot 2, received network voice header from 2682044 to TG 9
M: 2016-09-29 10:25:02.388 DMR Slot 2, received network end of voice transmission, 0.5 seconds, 0% packet loss, BER: 0.0%
M: 2016-09-29 10:29:30.414 DMR Slot 2, received network voice header from 2682040 to TG 9
M: 2016-09-29 10:29:31.378 DMR Slot 2, received network end of voice transmission, 0.8 seconds, 0% packet loss, BER: 0.0%

**Comment by g4klx** [comment]
What does the log say about loading the ID file? It's put in the log at the beginning of the run.

**Comment by pjao** [comment]
After last pull, that seams nothing related it started to load the IDs again:

M: 2016-09-29 13:13:02.483 Opening DMR Network
I: 2016-09-29 13:13:02.483 ID lookup File: /etc/DMRIds.dat
I: 2016-09-29 13:13:02.671 Loaded 43815 Ids to the callsign lookup table

**Comment by g4klx** [comment]
So is it working correctly for you now? Can I close this issue?

**Comment by pjao** [comment]
Yep! Closed!

**Comment by s-s-s** [comment]
`M: 2016-10-31 13:25:16.623 DMR, Opening DMR Network
I: 2016-10-31 13:25:16.623 DMR Id Lookups
I: 2016-10-31 13:25:16.623     File: None
W: 2016-10-31 13:25:16.623 Cannot open the Id lookup file -
...
M: 2016-10-31 13:25:16.625 MMDVMHost-20161021 is running
M: 2016-10-31 13:25:26.646 DMR, Logged into the master successfully
M: 2016-10-31 13:26:28.172 DMR Slot 2, received RF voice header from 2502007 to TG 2501
D: 2016-10-31 13:26:28.351 DMR Slot 2, audio sequence no. 0, errs: 0/141
D: 2016-10-31 13:26:28.399 DMR Slot 2, audio sequence no. 1, errs: 0/141`

**Comment by phl0** [comment]
You have the correct parameter in the MMDVM.ini?

**Comment by s-s-s** [comment]
> You have the correct parameter in the MMDVM.ini?
Right now, I am checking it again )
It seems that in a last version of MMDVM.ini, the description DMRIds was moved to a special section )

**Comment by pjao** [comment]
In here it looks ok also.

I: 2016-10-31 14:15:32.867 DMR Id Lookups
I: 2016-10-31 14:15:32.867     File: /etc/DMRIds.dat
I: 2016-10-31 14:15:32.867     Reload: 12 hours
I: 2016-10-31 14:15:33.070 Loaded 45741 Ids to the callsign lookup table

**Comment by s-s-s** [comment]
The new format of MMDVM.ini

> [DMR Id Lookup]
> File=DMRIds.dat
> Time=24
> 
> [DMR]
> Enable=1
> Beacons=1
> Id=000
> ColorCode=1
> SelfOnly=0
> CallHang=3
> TXHang=4
> 

In the old was so:

> [DMR]
> Enable=1
> Beacons=0
> Id=000
> ColorCode=1
> SelfOnly=0
> LookupFile=DMRIds.dat
