### ISSUE TITLE
C4FM high BER

### ISSUE THREAD

**Issue by iw9grl** [g4klx/MMDVMHost#170]
Hi

why in Fusion the BER is very high ? 
In DN mode the BER is around 15/20% , but it is lower using VM mode , I noticed also that after pushing the PTT I ear some seconds of tail with my last over .
There will be some future improvements ?
tnx
73

**Comment by g4klx** [comment]
No. C4FM uses a much greater bandwidth than the other modes. It is important that you use a wider RX filters on it otherwise you get a high BER. You need at least a 25 kHz filter in your RX.

**Comment by iw9grl** [comment]
Thank you Jonathan, if I put 25khz on my gm340 rx there are something that could create problems in Dstar or dmr?  Actually I have 20khz bandwidth. 73

**Comment by vk4tux** [comment]
I also use 20KHz > RX radio, only for YSF/P25 too (pwm switched) with 
the results you saw before. What is your threshold level ?

**Comment by vk4tux** [comment]
code is good here for YSF with DN ;

M: 2016-10-03 10:54:12.289 YSF, received RF end of transmission, 4.8 
seconds, BER: 0.3%
M: 2016-10-03 10:54:29.193 YSF, received RF end of transmission, 6.2 
seconds, BER: 0.0%
M: 2016-10-03 10:55:31.615 YSF, received RF end of transmission, 6.7 
seconds, BER: 0.0%
M: 2016-10-03 10:55:38.629 YSF, received network end of transmission, 
4.5 seconds, 0% packet loss, BER: 0.0%
M: 2016-10-03 10:56:18.054 YSF, received RF end of transmission, 35.9 
seconds, BER: 0.2%
M: 2016-10-03 10:56:44.698 YSF, received network end of transmission, 
21.4 seconds, 0% packet loss, BER: 0.0%
M: 2016-10-03 10:57:11.336 YSF, received RF end of transmission, 23.9 
seconds, BER: 0.0%
M: 2016-10-03 10:57:34.269 YSF, received network end of transmission, 
18.5 seconds, 0% packet loss, BER: 0.0%
M: 2016-10-03 10:58:11.911 YSF, received RF end of transmission, 34.8 
seconds, BER: 0.1%
M: 2016-10-03 10:58:42.737 YSF, received network end of transmission, 
25.8 seconds, 0% packet loss, BER: 0.0%


I think it depends on your equipment and setup

**Comment by iw9grl** [comment]
@vk4tux  My equipments are : 

x2 GM340 - Arduino DUE genuine ( last MMDVM ) , RPi3 ( last MMDVMHost )
