### ISSUE TITLE
Radio check & Call alert using DVMEGA & MMDVMHost

### ISSUE THREAD

**Issue by ea8cwb** [g4klx/MMDVMHost#174]
I have no got radio checl or call alert works using a DVMEGA with MMDVMHost so i ask myself if any software issue is happening.
When using a repeater have no problem. It seems to be only a DVMEGA so i thing the DMO mode in MMDVMHost could have any issue...
What do you think about?

**Comment by g4klx** [comment]
Those messages aren't defined the DMR specification, they are proprietary to the radio manufacturer, If you can provide more information about them, I may be able to include them.
