### ISSUE TITLE
REQUEST:  SharkRF IP IP Protocol Connector support?

### ISSUE THREAD

**Issue by iball** [g4klx/MMDVMHost#177]
Would it be possible to roll in additional connector support into MMDVMHost for this?

Details at the githubs below:

Client:
https://github.com/sharkrf/srf-ip-conn

Server:
https://github.com/sharkrf/srf-ip-conn-srv

**Comment by g4klx** [comment]
What is the use case for this? What does it give me over and above what we already have?

**Comment by iball** [comment]
It allows a user to build their own sharkRF IP server and use both openspot and mmsmvhost hotspot users to connect to it to use a private network for public event services.  It should also allow for both c4fm and DMR users to connect to the same server by having a hot spot running multiple dvmegas and different instances of mmdvmhost running on a single box.

**Comment by iball** [comment]
Upon further thought and reflection, just forget the whole idea.
