### ISSUE TITLE
Can't use TCXO with odd frequency

### ISSUE THREAD

**Issue by reiser4** [g4klx/MMDVMHost#183]
Hello, I'm trying to use a TCXO at 11.289600 mhz.
Decode stops after about 0.7 seconds and I can't improve the situation acting on the OscOffset parameter.
I guess the problem is the integer division by 24000 and 48000.
Could MMDVM support my TCXO or should I throw it in the garbage and get a different frequency?
thanks.

**Comment by iw9grl** [comment]
Tcxo supported are: 12mhz,14.4mhz and 19.2mhz or other integer division by 24000!!!

**Comment by reiser4** [comment]
Grazie IW9GRL, avevo visto le frequenze suggerite nel file config, pero` chiedo se sia possibile in qualche modo ottenere una configurazione funzionante anche con valori leggermente diversi.

**Comment by g4klx** [comment]
Some frequencies aren't possible because the division ratio isn't an exact integer. I don't know whether that frequency isn't suitable.

Jonathan  EA7/G4KLX
