### ISSUE TITLE
Rewrite function have to exclude some IDs- Echo/Parrot

### ISSUE THREAD

**Issue by pjao** [g4klx/MMDVMHost#186]
Hi there, trying to use the new rewrite functions, but it fails with Echo/Parrot (9990).

Echo/Parrot (9990) is a private call, not a group call, but even that i've tested.

With rewrite active:

Private call to 9990:
M: 2016-10-27 21:33:16.736 DMR Slot 2, Rewrite outbound private call to 9990 Group Call (Connect talkgroup by private call)
M: 2016-10-27 21:33:16.736 DMR Slot 2, received RF voice header from CT2JAY to TG 9990

Group call to 9990:
M: 2016-10-27 21:34:09.194 DMR Slot 2, received RF voice header from CT2JAY to TG 9990

Disable rewrite:

Private call to 9990:
M: 2016-10-27 21:35:30.142 DMR Slot 2, received RF voice header from CT2JAY to 9990
M: 2016-10-27 21:35:31.701 DMR Slot 2, received RF end of voice transmission, 1.4 seconds, BER: 0.2%
M: 2016-10-27 21:35:34.926 DMR Slot 2, received network voice header from 9990 to CT2JAY
M: 2016-10-27 21:35:36.198 DMR Slot 2, received network end of voice transmission, 1.6 seconds, 0% packet loss, BER: 0.0%

Group call to 9990:
M: 2016-10-27 21:36:53.011 DMR Slot 2, received RF voice header from CT2JAY to TG 9990

Any ideas how can it be fix it?
Thanks 
Paulo - CT2JAY

**Comment by g4klx** [comment]
It's on my list to fix.

**Comment by g4klx** [comment]
I've updated the code, I hope it works for you now. Get the latest from GitHub.

**Comment by pjao** [comment]
I've get the latest but it seams something not working.

Echo/Parrot is working fine now with rewrite function!

BM reflector voice prompt: working fine;
Private call changed to group call: working fine;

After that, using TG9 should be rewrite to the group, but that is not happening.

**Comment by g4klx** [comment]
Can you ask on the MMDVM group please as the original author appears not to read on here. He needs to fix it.
