### ISSUE TITLE
Build 1eb03ca does not compile with Visual Studio 2015

### ISSUE THREAD

**Issue by iball** [g4klx/MMDVMHost#188]
Getting this error:

 Generating Code...
MMDVMHost.obj : error LNK2019: unresolved external symbol "public: __cdecl CLCDproc::CLCDproc(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,unsigned int,unsigned int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned int,bool,bool,bool,bool)" (??0CLCDproc@@QEAA@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@IIAEBV12@I_N222@Z) referenced in function "private: void __cdecl CMMDVMHost::createDisplay(void)" (?createDisplay@CMMDVMHost@@AEAAXXZ)
C:\Users\iball\Source\Repos\MMDVMHost2\x64\Debug\MMDVMHost.exe : fatal error LNK1120: 1 unresolved externals

Compiles just fine on the Pi itself but not in Windows Visual Studio 2015.
Is there something else I have to install in VS2015 now?

**Comment by iball** [comment]
UPDATE:  Yup, looks like the LCDproc.cpp and LCDproc.h are not included in the project files for VS2015.  
Lemme see if hand-adding them "fixes" it...

**Comment by iball** [comment]
1>------ Build started: Project: MMDVMHost, Configuration: Debug x64 ------
1>  LCDproc.cpp
1>c:\users\iball\source\repos\mmdvmhost2\lcdproc.cpp(30): fatal error C1083: Cannot open include file: 'sys/select.h': No such file or directory
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by iball** [comment]
Nope.  The VS project needs to be updated?

**Comment by g4klx** [comment]
I'll look into it tonight.

**Comment by iball** [comment]
Can confirm that build 7431f50 now compiles under VS2015 and the EXE runs just fine on Windows 10.
