### ISSUE TITLE
LOOP after wifi down

### ISSUE THREAD

**Issue by iw9grl** [g4klx/MMDVMHost#203]
I try to simulate a wifi network down and I found in the log : 

M: 2016-11-07 18:52:20.431 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.431 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.431 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.431 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.431 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.431 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.431 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.431 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.431 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.431 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.431 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.432 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.432 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.432 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.432 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.432 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.432 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.432 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.432 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.432 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.432 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.432 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.433 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.433 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.433 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.433 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.433 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.433 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.433 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.433 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.433 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.433 DMR, Opening DMR Network
M: 2016-11-07 18:52:20.433 DMR, Opening DMR Network
and so on .............................

a loop that doesn't stop after the WIFI goes up !!!!!! 
I MUST restart the MMDVMHost service .........

it is possible to fix this issue ?

73

**Comment by g4klx** [comment]
A fix has been applied to the DMR networking code by Andy CA6JAU. Can you do a Git pull and try again please.

**Comment by borjam** [comment]
I observed a similar behavior when the wireless network went down (rebooting the AP). I have done a pull, and at least the behavior I observed is fixed now. Woohoo! It recovered without any manual intervention.

Sorry for repeating it, but it's better to keep track of the fix here I think.


E: 2016-11-18 12:02:55.581 Error returned from sendto, err: 101
E: 2016-11-18 12:02:55.581 DMR, Socket has failed when writing data to the master, retrying connection
M: 2016-11-18 12:02:55.581 DMR, Opening DMR Network
E: 2016-11-18 12:03:05.584 Error returned from sendto, err: 101
E: 2016-11-18 12:03:05.593 DMR, Socket has failed when writing data to the master, retrying connection
M: 2016-11-18 12:03:05.593 DMR, Opening DMR Network
E: 2016-11-18 12:03:15.591 Error returned from sendto, err: 101
E: 2016-11-18 12:03:15.591 DMR, Socket has failed when writing data to the master, retrying connection
M: 2016-11-18 12:03:15.591 DMR, Opening DMR Network
E: 2016-11-18 12:03:25.597 Error returned from sendto, err: 101
E: 2016-11-18 12:03:25.597 DMR, Socket has failed when writing data to the master, retrying connection
M: 2016-11-18 12:03:25.597 DMR, Opening DMR Network
E: 2016-11-18 12:03:35.598 Error returned from sendto, err: 101
E: 2016-11-18 12:03:35.598 DMR, Socket has failed when writing data to the master, retrying connection
M: 2016-11-18 12:03:35.599 DMR, Opening DMR Network
E: 2016-11-18 12:03:45.604 Error returned from sendto, err: 101
E: 2016-11-18 12:03:45.604 DMR, Socket has failed when writing data to the master, retrying connection
M: 2016-11-18 12:03:45.605 DMR, Opening DMR Network
E: 2016-11-18 12:03:55.607 Error returned from sendto, err: 101
E: 2016-11-18 12:03:55.607 DMR, Socket has failed when writing data to the master, retrying connection
M: 2016-11-18 12:03:55.607 DMR, Opening DMR Network
E: 2016-11-18 12:04:05.616 Error returned from sendto, err: 101
E: 2016-11-18 12:04:05.617 DMR, Socket has failed when writing data to the master, retrying connection
M: 2016-11-18 12:04:05.617 DMR, Opening DMR Network
E: 2016-11-18 12:04:15.622 Error returned from sendto, err: 101
E: 2016-11-18 12:04:15.622 DMR, Socket has failed when writing data to the master, retrying connection
M: 2016-11-18 12:04:15.623 DMR, Opening DMR Network
E: 2016-11-18 12:04:25.626 Error returned from sendto, err: 101
E: 2016-11-18 12:04:25.627 DMR, Socket has failed when writing data to the master, retrying connection
M: 2016-11-18 12:04:25.627 DMR, Opening DMR Network
E: 2016-11-18 12:04:35.632 Error returned from sendto, err: 101
E: 2016-11-18 12:04:35.632 DMR, Socket has failed when writing data to the master, retrying connection
M: 2016-11-18 12:04:35.632 DMR, Opening DMR Network
E: 2016-11-18 12:04:45.638 Error returned from sendto, err: 101
E: 2016-11-18 12:04:45.638 DMR, Socket has failed when writing data to the master, retrying connection
M: 2016-11-18 12:04:45.639 DMR, Opening DMR Network
E: 2016-11-18 12:04:55.646 Error returned from sendto, err: 101
E: 2016-11-18 12:04:55.647 DMR, Socket has failed when writing data to the master, retrying connection
M: 2016-11-18 12:04:55.647 DMR, Opening DMR Network
E: 2016-11-18 12:05:05.652 Error returned from sendto, err: 101
E: 2016-11-18 12:05:05.652 DMR, Socket has failed when writing data to the master, retrying connection
M: 2016-11-18 12:05:05.652 DMR, Opening DMR Network
E: 2016-11-18 12:05:15.655 Error returned from sendto, err: 101
E: 2016-11-18 12:05:15.655 DMR, Socket has failed when writing data to the master, retrying connection
M: 2016-11-18 12:05:15.655 DMR, Opening DMR Network
D: 2016-11-18 12:05:21.653 sending CW ID
E: 2016-11-18 12:05:25.658 Error returned from sendto, err: 101
E: 2016-11-18 12:05:25.659 DMR, Socket has failed when writing data to the master, retrying connection
M: 2016-11-18 12:05:25.659 DMR, Opening DMR Network
E: 2016-11-18 12:05:35.661 Error returned from sendto, err: 101
E: 2016-11-18 12:05:35.662 DMR, Socket has failed when writing data to the master, retrying connection
M: 2016-11-18 12:05:35.662 DMR, Opening DMR Network
E: 2016-11-18 12:05:45.669 Error returned from sendto, err: 101
E: 2016-11-18 12:05:45.670 DMR, Socket has failed when writing data to the master, retrying connection
M: 2016-11-18 12:05:45.670 DMR, Opening DMR Network
E: 2016-11-18 12:05:55.677 Error returned from sendto, err: 101
E: 2016-11-18 12:05:55.678 DMR, Socket has failed when writing data to the master, retrying connection
M: 2016-11-18 12:05:55.678 DMR, Opening DMR Network
E: 2016-11-18 12:06:05.686 Error returned from sendto, err: 101
E: 2016-11-18 12:06:05.687 DMR, Socket has failed when writing data to the master, retrying connection
M: 2016-11-18 12:06:05.687 DMR, Opening DMR Network



D: 2016-11-18 12:07:08.140 DMR, Sending authorisation
D: 2016-11-18 12:07:08.176 DMR, Sending configuration
M: 2016-11-18 12:07:08.208 DMR, Logged into the master successfully

**Comment by iw9grl** [comment]
Hi Jonathan, I confirm what "borjam"  says, I see the same messages on the log and after the wifi goes up MMDVMHost recover the master server without any problems. I will see in a few days if it is solved definitely. 
Best regards 
Daniele IW9GRL
