### ISSUE TITLE
Radio Check - blacklisted

### ISSUE THREAD

**Issue by pjao** [g4klx/MMDVMHost#211]
Hi!

Trying to do radio check with the md380, but it appears as blacklisted, is it a limitation of dvmega or something that could be solved?

Here it goes part of the log.

M: 2016-11-10 21:08:51.138 0000:  A4 10 00 00 28 EC AF 28 F0 C2 0A F5                *....(..(....*
M: 2016-11-10 21:08:51.139 DMR Slot 2, invalid access attempt from 0 (blacklisted)

**Comment by g4klx** [comment]
A DMR Id of zero is not valid, so it is rejected.

**Comment by pjao** [comment]
Before that mensage it appears:

M: 2016-11-10 22:07:38.411 Unhandled CSBK type

**Comment by g4klx** [comment]
It should work better by the end of the weekend.
