### ISSUE TITLE
ADC is always in overflow with last updates 

### ISSUE THREAD

**Issue by iw9grl** [g4klx/MMDVMHost#224]
Hi 
I noticed that in our MMDVM repeaters after the last updates, I think in the last weeks, the message of the ADC overflow have many occurrence, I try to decrease the RXLevel but nothing change regarding the overflow only threshold change ( of course). Any helps? 
73 de IW9GRL

**Comment by iw9grl** [comment]
![screenshot_2016-11-18-19-30-03](https://cloud.githubusercontent.com/assets/16877668/20455256/e7923846-ae57-11e6-9cb8-842baf4f3b83.png)

**Comment by g4klx** [comment]
I think you should find this has now been fixed.

**Comment by iw9grl** [comment]
YEs ...  tnx
