### ISSUE TITLE
Blacklist issues 

### ISSUE THREAD

**Issue by iw9grl** [g4klx/MMDVMHost#231]
Hi dear, I noticed that the blacklist settings doesn't work, could you confirm please? 
73

**Comment by phl0** [comment]
Could you please give more details? 

- Which version if MMDVMHost are you using?
- What display type are you using?
- What is configured in MMDVM.ini?
- Any hints in the logs?

**Comment by iw9grl** [comment]
Hi dear, I use the last revision of mmdvmhost, if you see in the last ini the blacklist reference were removed, I added manually the blacklist details, I use the HD44780 display, nothing relevant in the log file.  73
