### ISSUE TITLE
Multimode RSSI Inaccurate V tracking

### ISSUE THREAD

**Issue by vk4tux** [g4klx/MMDVMHost#245]
Previous to multimode we hd three repeaters tracking DMR RSSI perfectly, tested against field test equipment.

However we are finding with latest update that max signals are indicated regardless off V mapping applied

D: 2017-01-09 14:39:28.219 P25, LDU2 audio, errs: 9/1233
D: 2017-01-09 14:39:28.398 P25, raw RSSI: 26112, reported RSSI: -47 dBm
D: 2017-01-09 14:39:28.399 P25, LDU1 audio, errs: 10/1233

Test mapping for above ;

9700        -47
7150        -90
300        -107
The same issue is in all modes

Previous calibrated mapping which worked well when DMR only RSSI was in code ;

1320        -60
1250        -70
1090        -90
970        -100
820        -110
710        -120

No hardware changes occurred, only FW update to latest > now that debugging level>RX buffer issue dealt with, & Host update, both to latest. If FW is reverted to previous,

# https://github.com/g4klx/MMDVM/commit/461e7c942e49325b0371036b7f3e355cf774074d

, then DMR RSSI is again accurate.

**Comment by g4klx** [comment]
The raw RSSI is shown as 26112, however that is beyond the range of your mapping file. If it is outside that range, then the nearest value is chosen, in this case -47 from 9700. You need a mapping file that covers the whole range of values.

**Comment by vk4tux** [comment]
On 10/01/17 01:09, Jonathan Naylor wrote:
>
> The raw RSSI is shown as 26112,               << where did this number 
> come from.
>

I understood the previous raw rssi value of 1000 to be > ~ 1000mV . Was 
this not correct ?

The repeater rssi range was mapped from -60 to -120, using calibrated 
test equipment inputs, and A6 measure direct at A6 pin point due to 1/2V 
Sp8NTH v6.1 10K/10K V divider prior in circuit; R6 A6 R9

We found this accurate. This the raw rssi value's must be now working in 
a different numeral range

Raw RSSI value ??? = 1V Is there a value that equate's to 1 Volt now on 
new raw output ?

Thankyou for the response

**Comment by vk4tux** [comment]
I converted to the range and its tracking thankyou ;

D: 2017-01-09 15:43:03.580 P25, raw RSSI: 27648, reported RSSI: -74 dBm
D: 2017-01-09 15:43:03.581 P25, LDU1 audio, errs: 20/1233
D: 2017-01-09 15:43:03.755 P25, raw RSSI: 29184, reported RSSI: -71 dBm
D: 2017-01-09 15:43:03.756 P25, LDU2 audio, errs: 20/1233
D: 2017-01-09 15:43:03.936 P25, raw RSSI: 29952, reported RSSI: -70 dBm
D: 2017-01-09 15:43:03.937 P25, LDU1 audio, errs: 22/1233
D: 2017-01-09 15:43:04.116 P25, raw RSSI: 29184, reported RSSI: -71 dBm
D: 2017-01-09 15:43:04.117 P25, LDU2 audio, errs: 19/1233
D: 2017-01-09 15:43:04.296 P25, raw RSSI: 28672, reported RSSI: -72 dBm
D: 2017-01-09 15:43:04.297 P25, LDU1 audio, errs: 16/1233
D: 2017-01-09 15:43:04.476 P25, raw RSSI: 28416, reported RSSI: -73 dBm
D: 2017-01-09 15:43:04.477 P25, LDU2 audio, errs: 20/1233
D: 2017-01-09 15:43:04.656 P25, raw RSSI: 26368, reported RSSI: -77 dBm
D: 2017-01-09 15:43:04.657 P25, LDU1 audio, errs: 21/1233
D: 2017-01-09 15:43:04.837 P25, raw RSSI: 31488, reported RSSI: -68 dBm
D: 2017-01-09 15:43:04.838 P25, LDU2 audio, errs: 14/1233
D: 2017-01-09 15:43:05.017 P25, raw RSSI: 31488, reported RSSI: -68 dBm
D: 2017-01-09 15:43:05.018 P25, LDU1 audio, errs: 23/1233
D: 2017-01-09 15:43:05.197 P25, raw RSSI: 34304, reported RSSI: -65 dBm
D: 2017-01-09 15:43:05.198 P25, LDU2 audio, errs: 13/1233
D: 2017-01-09 15:43:05.377 P25, raw RSSI: 28928, reported RSSI: -72 dBm
D: 2017-01-09 15:43:05.378 P25, LDU1 audio, errs: 19/1233
D: 2017-01-09 15:43:05.558 P25, raw RSSI: 46336, reported RSSI: -60 dBm
M: 2017-01-09 15:43:05.558 P25, received RF end of transmission, 9.2 
seconds, BER: 2.5%, RSSI: -94/-60/-75 dBm
