### ISSUE TITLE
MMDVMHost segfault on loss of network

### ISSUE THREAD

**Issue by m1geo** [g4klx/MMDVMHost#246]
I notice that the Host program segmentation faults when a network connection (maybe internet connectivity?) is lost.

This is frustrating since on our site, the repeater hardware is USP backed up, but the internet hardware is not.

It would be even more awesome to let users know there was internet via voice feedback.

**Comment by g4klx** [comment]
It shouldn't segfault. I wonder what the particular circumstances of this are? It's pretty good at recovering these days. Regarding a voice prompt, that is way beyond the core functionality of the project and is best implemented externally. The decision has to be made about announcing in which of the many modes?

**Comment by m1geo** [comment]
I should have got a stacktrace. It's normally bulletproof, as you say, but it fell over today on loss of internet. About 6am this morning.

Regarding the announcement, I was thinking if a user tried to connect to something remote, just respond in the mode they attempted, saying there was no internet.

If it happens again, I'll have the logs. Next time I am on site, I'll try and force the issue again, and get a log.

**Comment by m1geo** [comment]
This does not appear to be an issue any more. I guess it came about because I operate MMDVMHost over a VPN connection, and on the loss of connection, the device (tun0 or tap0) drops, and MMDVMHost falls over.
