### ISSUE TITLE
DMO mode & SP8NTH duplex=0

### ISSUE THREAD

**Issue by vk4tux** [g4klx/MMDVMHost#251]
Latest code does not work with DMO/Simplex any mode on SP8NTH.

DMR does not key properly and no reaction to P25, DStar, C4FM.

Go back to 1 NOV 2015 code and above works perfect on same SP8NTH hardware.
We also have to undo latest Host code update on p25 repeaters due to increased error rate.

Just an FYI

**Comment by g4klx** [comment]
There are no other reports of issues with any version later than 1 Nov. Please recheck your system.

**Comment by vk4tux** [comment]
Yes
