### ISSUE TITLE
Embedded Talker Alias

### ISSUE THREAD

**Issue by pjao** [g4klx/MMDVMHost#254]
Hi @g4klx !

Could be possible to add first occurrence of the alias-block in LogLevel 2?

That way it could be workable with Dashboard from @dg9vh

Thanks
Paulo - CT2JAY

**Comment by g4klx** [comment]
In my next change I'll increase the log level of the Talker Alias to message. Once I have seen one on my system I'll interpret the data correctly. I cannot guarantee that it'll only appear once per transmission though. That can be the dashboard's job.

**Comment by pjao** [comment]
Thanks Jonathan - @g4klx ! Hope for news soon!

**Comment by g4klx** [comment]
It should now appear only once per transmissions, and now at log level 2.
