### ISSUE TITLE
CW ID MMDVMHost &DVMEGA

### ISSUE THREAD

**Issue by kc0mmy** [g4klx/MMDVMHost#255]
Greetings,

Is it possible to have MMDVMHOST transmit my call sign using CW with the DVMEGA?  If so, how?  If not, are there any plans for implementation?  I'd like to be able to properly ID my hotspot.

Thank you and 73 de Andre
KC0MMY

**Comment by g4klx** [comment]
It's a hardware/firmware limitation of the DVMEGA and nothing to do with my host software.

**Comment by kc0mmy** [comment]
Okay.  Thanks for the info!  

73 de Andre
KC0MMY

Sent to you via radio waves.
