### ISSUE TITLE
D-Star control feature

### ISSUE THREAD

**Issue by ok2it** [g4klx/MMDVMHost#260]
Hi
Would it be possible to add:
Error reply
RPT1 VALID
Beacon and Beacon TXT

Mainly Err reply and RPT Val as currently as long as Call and module don't match mmdvm host sends nothing. Modern radios will setup if they get a set RPT reply.
Could I kindly ask if it is doable as we use mmdvm for DSTAR a lot here in OK

73 AND wow....What a machine this is

**Comment by g4klx** [comment]
I do that on the D-Star Repeater software but not for the MMDVM. My original thinking was because it can cause problems between multiple hostspots on the same frequency. Maybe I should re-add it and make it configurable so it can be disabled if needed. I'll look into it.

**Comment by ok2it** [comment]
Hi Jonathan

Not sure my reply made it through as I am in France (didn’t know how bad could internet get in same areas here.....hmmm) on dodgy hotel wifi.
Anyway, you are right, feature to turn automatic ACK and Error Reply off was mainly due to hotspots colliding on same QRG. We are using a lot of MMDVMs currently to swap out older SNDCARD and GMSKs running your D-Star RPTR/GW platform. On repeaters though, having an option to enable beacons, enable Err reply and ACK/RPT VAL would make big step forward as that way MMDVM as D-Star repeater would come to par with currently used setups.
I have to say that I still cant get my head around how did this even crossed your mind(MMDVM as a concept)and I am amazed as I have run lots of comparesments between MMDVM(48/24KHz) GMSK modem (CMX589s) and SNDCARDs and I have to say, considering that DMR occupy wider channel hence D-Star by its natre drives 12bit ADC to lower levels, I haven’t found instance where it would fail where other would work. It really is working amazingly well.

While I know how busy you must be I will use this opportunity to ask a question or two....
Firtstly – how hard would be to add DTMF (plain FM with DTMF)decode with GPIO output (0/1 or change state)of Due or similar?

And secondly...
I have been asked by Milan OK1MX to help with translation as it seems he got himself into some cross with Heinz and Torsten. Altough I understand DMR+ and DMR-BM are in (I hope healthy)competition, I seem to be missing point why would someone block a person callsign from accessing DCS-Reflectors and as a reason for doing so put: Brandmeister.!?
I respect you not only for your work but also for common sense you have displayed while seeing some of your presentations so I hope you don’t mind me asking – is it worth fighting with Heinz/Torsten or is it better to just back off and “move services elsewhere”?

Thanks again for all your hard work and I am always looking forward for new releases... I wish I was a coder who could help.. all I could is betatest lol

73
Jiri OK2IT


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by g4klx** [comment]
Hi Jiri

I've added the error ack to the D-Star side of the MMDVM. I hope to get the code committed this evening, but it will be untested for now. By default it will be enabled, and it will be able to be switched off from a new entry in the MMDVM.ini file. The new .ini file will include this setting as an example.

I will not be adding anything that will control any special hardware other than the MMDVM, UMP and displays. It is far better to write something that monitors the log file and trigger the GPIO pin based on a log entry. That is much more general and flexible than anything that I can add.

I would suggest that you go with BM. I think it is a far more advanced platform than DMR+ and is adding new features all of the time. At least in the UK there is far less politics around BM than any of the alternative networks available. There have been many cases of people and repeaters being blocked on DCS because of DMR politics, this is not good. It's not in the spirit of the hobby and I reject all of it. People who block others do not deserve to run a network.

**Comment by ok2it** [comment]
Thanks a lot for everything.

In regards to UMP I can actually have separate DTMF decoder controling UMP instead. That makes sense.

I will be back tonight so I can pull from github and test it out. I just realised beacon isn't needed as GW can receive data to TX text and ambe voice.

All good stuff.
DMR-wise yes we moved to BM hence our DSTAR dcs being blocked. I setup XLX so it won't take long anyway.

Thanks again for all help
Really appreciate it.

Jiri

Jiří Čulák
Presales Engineer
FourteenIP EU - Czech republic
Tel +420 22888 0370
Mob +420 731 611577




On Wed, Feb 15, 2017 at 4:44 PM +0100, "Jonathan Naylor" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Jiri

I've added the error ack to the D-Star side of the MMDVM. I hope to get the code committed this evening, but it will be untested for now. By default it will be enabled, and it will be able to be switched off from a new entry in the MMDVM.ini file. The new .ini file will include this setting as an example.

I will not be adding anything that will control any special hardware other than the MMDVM, UMP and displays. It is far better to write something that monitors the log file and trigger the GPIO pin based on a log entry. That is much more general and flexible than anything that I can add.

I would suggest that you go with BM. I think it is a far more advanced platform than DMR+ and is adding new features all of the time. At least in the UK there is far less politics around BM than any of the alternative networks available. There have been many cases of people and repeaters being blocked on DCS because of DMR politics, this is not good. It's not in the spirit of the hobby and I reject all of it. People who block others do not deserve to run a network.

**Comment by ok2it** [comment]
Hi Jonathan

I have closed this off so not sure you get this via github but I just stumbled upon an article regarding D-Start HotSpots and delay between ACK is being sent compared to RPTR Duplex mode and suggestions
Are that times about 1-3seconds are used, while HotSpot is still trying to receive and decode right up to the moment when it decides its over and sends ACK.
Is there a variable which can control this? I mean it doesn’t need to only happen in Duplex=1 mode. I am only starting with C / C++ and will try to look for it as an excersice but if you do know and are willing if not a massive job this might also enhance the multimode hotspot featureset.

Anyway. I will wait for the commit and try the ack err.

Tnx a lot and as always, very appreciated….
Do you code for living??

Jiri

**Comment by g4klx** [comment]
Hi Jiri
I've added the error ack to the D-Star side of the MMDVM. It is settable from the .ini file and the default is for it to be on. It's on GitHub now.
The delay is fixed at 750ms which is what the Icom repeaters use, so I am guided by that. I don't think having an adjustable time is that important to be honest. It isn't adjustable in the D-Star Repeater and I've had no complaints over the seven years that it's been available!
I do coding for a living, but unfortunately not anything like the MMDVM :-(
Jonathan  G4KLX

**Comment by ok2it** [comment]
You are right – I don’t think it really does make any difference - D–Star either deliver RF EOT or it send ACK after timeout anyway and making the period adjustable probably doesn’t make anything better.
At least it will be uniform – we have couple of hotspot were delay got set to 4000ms using windows registry….

Question – in early stages you mentioned you are missing DMR Repeater…I mean off the shelf repeater to compare, etc. Do you still need one?

**Comment by g4klx** [comment]
I don't need a "real" DMR repeater now. I think I know as much as I need to about DMR, there are only a couple of minor edge cases left, and that can easily be tested by tracing a real DMR repeater. I have friends who can do that for me.
Jonathan  G4KLX

**Comment by ok2it** [comment]
Hi Jonathan

I just realized Blacklist=   doesn’t work under DMR part in MMDVM.ini anymore?

We have had few OK9s (M6,M3 equiv) buying Baofeng DMR Tier1 radios blocking both TS1 and TS2 and normal explanations don’t work – they don’t care if someone else can’t use repeater.

Is there a way to define temporary Blacklist for specific Ids??

Thanks a lot
Jiri

**Comment by ok2it** [comment]
I juset realized its not Blacklist but  BlackList while looking at Conf.cpp

Sorry…

I am slowly getting into CPP…very slowly… I hope one day to be able to help…even a little.

73
Jiri

From: Jirka Culak <jiri.culak@outlook.com<mailto:jiri.culak@outlook.com>>
Date: neděle 19. února 2017 16:37
To: g4klx/MMDVMHost <reply@reply.github.com<mailto:reply@reply.github.com>>
Subject: URGENT - BlackList

Hi Jonathan

I just realized Blacklist=   doesn’t work under DMR part in MMDVM.ini anymore?

We have had few OK9s (M6,M3 equiv) buying Baofeng DMR Tier1 radios blocking both TS1 and TS2 and normal explanations don’t work – they don’t care if someone else can’t use repeater.

Is there a way to define temporary Blacklist for specific Ids??

Thanks a lot
Jiri
