### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by fmgkamps** [g4klx/MMDVMHost#264]
Hi Jonathan,
I'm using a DVMega in combination with MMDVMHost for DMR.
The DVMega is slightly of frequency, about 70Hz. This is enough to result in a high BER and missing end and start of voice transmissions.
Is there a possibility to add a parameter in mmdvm.ini to correct the frequency?
For now I entered a corrected rx and tx frequency in the mmdvm.ini file.
This results however in an incorrect frequency representation on brandmeister dashboard.
Kind regards, 
73 PE0FK

**Comment by g4klx** [comment]
No. Your DVMega is obviously not working correctly, contact Guus or your supplier and talk to them about it.
