### ISSUE TITLE
Failed to build MMDVMHost commit 1146a0f

### ISSUE THREAD

**Issue by dg3yjb** [g4klx/MMDVMHost#273]
$ make
echo "const char *gitversion = \"1146a0f05f622d9971a1917e063ad00a30eafb19\";" > gitversion.h
g++ -g -O3 -Wall -std=c++0x -pthread -c -o MMDVMHost.o MMDVMHost.cpp
MMDVMHost.cpp:36:24: fatal error: GitVersion.h: Datei oder Verzeichnis nicht gefunden
 #include "GitVersion.h"
                        ^
compilation terminated.
Makefile:22: recipe for target 'MMDVMHost.o' failed
make: *** [MMDVMHost.o] Error 1

**Comment by AndyTaylorTweet** [comment]
Confirmed I am getting the same, file "Gitversion.h" is missing from the Git repo.

**Comment by phl0** [comment]
@dg3yjb @AndyTaylorTweet See https://github.com/g4klx/MMDVMHost/pull/274

**Comment by AndyTaylorTweet** [comment]
Merged already and now builds are clean again.
