### ISSUE TITLE
Makefile.Pi - potential missing external Library

### ISSUE THREAD

**Issue by jpronans** [g4klx/MMDVMHost#280]
Hi, I was in with EI8JA earlier helping him to get going on getting RSSI working with his repeater.  Once I realised that there was no support for RSSI.dat in the version of mmdvm host. I did a git pull and tried to rebuild using Makefile.Pi.  It failed with a linker error.  After thinking about it for a few minutes, a minor change to the makefile got it to build.

`git diff Makefile.Pi
diff --git a/Makefile.Pi b/Makefile.Pi
index 3ac85ad..e4d796d 100644
--- a/Makefile.Pi
+++ b/Makefile.Pi
@@ -3,7 +3,7 @@
 CC      = gcc
 CXX     = g++
 CFLAGS  = -g -O3 -Wall -std=c++0x -pthread -DRASPBERRY_PI -I/usr/local/include
-LIBS    = -lwiringPi -lwiringPiDev -lpthread
+LIBS    = -lwiringPi -lwiringPiDev -lpthread -lcrypt
 LDFLAGS = -g -L/usr/local/lib
 
 OBJECTS = \
`
Regards
John
EI7IG

**Comment by g4klx** [comment]
This is odd. The software makes no use of any cryptography so the use of that library troubles me. What is the root problem that this solves?

**Comment by jpronans** [comment]
I completely agree, but mmdvmhost wouldn't link without it.  I'll find out what Pi Image John is using and see if I can replicate it at home, not on his actual repeater.

**Comment by g4klx** [comment]
No-one else has reported any such issues so I'm wondering what's different about that system.

**Comment by jpronans** [comment]
I'm closing this issue.

I unnecessarily used Makefile.Pi which pulls in "-DRASPBERRY_PI -I/usr/local/include" and the wiringPi library maybe one of those requires crypt.

Sorry for the distraction.
