### ISSUE TITLE
Feature Request : Update MMDVM Coordinates from GPS Informations while moving

### ISSUE THREAD

**Issue by F4FPR** [g4klx/MMDVMHost#287]
Hello Folks,

This is a feature request,

Is there any way for MMDVMHost , allow real time update of GPS coordinates uploaded to Brandmeister or DMR+ in real time (using a "external" GPS from Raspberry PI for exemple) ?

Actualy MMDVMHost send the coordinates define on MMDVM.ini which never changes.

Using an external GPS, if MMDVM is able to, the user could see its coordinates updated in real time on the network while moving (bike , car , train , etc).

Hoping that this functionality could be coded one day.

With my best 73

Benjamin L / F4FPR / AG5HQ

**Comment by g4klx** [comment]
This isn't currently possible. The protocol only allows for the sending of host GPS data at start time. I'm not sure how else to add it other than talking to aprs.fi directly.

**Comment by F4FPR** [comment]
Any way then to talk to Aprs.fi for interval auto update ??

**Comment by g4klx** [comment]
The MMDVM Host doesn't talk to aprs.fi. DMR positions are handled by the network, and there is no way to update them dynamically.
