### ISSUE TITLE
MMDVMHost doesn't compile with flag -DHD44780

### ISSUE THREAD

**Issue by dd5xl** [g4klx/MMDVMHost#298]
When compiling latest commit with -DHD44780 there occurs an error at MMDVMHost.cpp:

g++ -g -O3 -Wall -std=c++0x -pthread -DHD44780 -I/usr/local/include -c -o MMDVMHost.o MMDVMHost.cpp
MMDVMHost.cpp: In member function ‘int CMMDVMHost::run()’:
MMDVMHost.cpp:792:1: error: a function-definition is not allowed here before ‘{’ token
 {
 ^
MMDVMHost.cpp:1294:1: error: expected ‘}’ at end of input
 }
 ^
MMDVMHost.cpp:1294:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^

**Comment by phl0** [comment]
Made a PR to fix this. See above.

**Comment by phl0** [comment]
@dd5xl PR has be merged. Please test the latest version of the code. Compiled cleanly here. If all is ok, pls close this issue. ;-)

**Comment by dd5xl** [comment]
Confirm, latest commit fixes this issue, now compiles flawlessly. Thanks for the quick support! 73 de Bert

**Comment by phl0** [comment]
You are welcome :+1:
