### ISSUE TITLE
MMDVMHost connect to FCS-reflector?

### ISSUE THREAD

**Issue by chrigu62** [g4klx/MMDVMHost#301]
Is it possible to connect to FCS-reflector with MMDVMHost? (Yaesu Fusion)

**Comment by g0wfv** [comment]
Short answer - No.

**Comment by phl0** [comment]
Long(er) answer: https://groups.yahoo.com/neo/groups/mmdvm/conversations/topics/9528;_ylc=X3oDMTM2M2c2N3VwBF9TAzk3MzU5NzE0BGdycElkAzkyMTkwMDA2BGdycHNwSWQDMTcwNTA2MjI4MARtc2dJZAMxMDQwMQRzZWMDZnRyBHNsawN2dHBjBHN0aW1lAzE0ODI5NDk2MTkEdHBjSWQDOTUyOA--
