### ISSUE TITLE
Bridging systems like openSPOT

### ISSUE THREAD

**Issue by amvidalrc** [g4klx/MMDVMHost#302]
Hello. I have some DMR & C4FM radios. I have searched and didn't find nothing about.
The question is simple: It's possible to talk on a DMR TG using a Yaesu FT2D for example and only 1 DV-mega and MMDVMHost? 

If not, Will be possible?

Thanks in advance.

**Comment by g4klx** [comment]
The bridging of systems is best done by the external network. I know that BrandMeister can do such things. I don't have the time to add such features, but since it is all open source, maybe others will?

**Comment by amvidalrc** [comment]
I'm not developer, so maybe it's a function request, but will be very very great to bridge technologies, DMR and C4FM already exist, so, I don't know if somebody can see if that is possible with MMDVMHost.

About bridging of systems: I have created my own server with a YSF Reflector, also I have my YSFGateway and my DMR Gateway on the same MMDVMHost. BM have the option to bridge them at network level?? 

more info will be appreciated.

Thanks for your great work and efforts in your project!

ea8dam.-

**Comment by g4klx** [comment]
It requires time and effort that I don't have. I know that BM has many such facilities, please contact them. I do not believe that this is a function that should be at the repeater end.

**Comment by amvidalrc** [comment]
I will contact BM directly. Thanks!!
