### ISSUE TITLE
MMDVMHost.ini Sanity

### ISSUE THREAD

**Issue by AndyTaylorTweet** [g4klx/MMDVMHost#303]
DMR+ uses the [DMR Network] section Options= line.
The syntax for this line is not sane;

`Options=StartRef=4409;RelinkTime=60;UserLink=1;`
This is not a sane line for standard ini files, because of the multiple "="
This causes parse issues when trying to wrangle this config file with anything other than a text editor.

`Options="StartRef=4409;RelinkTime=60;UserLink=1;"`
The above IS sane.

I propose the following changes to make the migration pain free;

in MMDVMHost.h
Line 34 / Add:
`#include <algorithm>`

in MMDVMHost.cpp
After line 900:
`std::string options = m_conf.getDMRNetworkOptions();`

Add this line:
`options.erase (std::remove(options.begin(), options.end(), '"'), options.end());`

This allows the use of the quotes in the config, while not passing them to the network. If the quotes do not exist, the application still works as it always did.

**Comment by AndyTaylorTweet** [comment]
Edited the above after I ran into a bug with OLED screen compiles, the improved version (above) works correctly and still compiles clean with the OLED screens.

**Comment by g4klx** [comment]
I disagree. I expect people to use text editors, and your solution would mangle the line:

Options=fu="bar"

The format of the Options line is meant to be free from, network specific, so any simplistic parsing is guaranteed to cause problems somewhere.

**Comment by AndyTaylorTweet** [comment]
I guess that means I'll have to maintain a locally patched version, a shame but I do understand your sentiment.
