### ISSUE TITLE
compiling error in VS2015 (Windows)

### ISSUE THREAD

**Issue by farnouche** [g4klx/MMDVMHost#306]
Hi Jonathan,

I had a mistake when I want to compile the last MMDVMHost on Windows OS with VS2015. (older version 20170206 compiled well with VS2015 ;-) )
The compilator don't find "GitVersion.h" file and "gitversion" variable

How can I fix it?

73 QRO 
F4CWF Farnouche

**Comment by phl0** [comment]
@m1geo Did you test the GitVersion stuff on Windows?

**Comment by farnouche** [comment]
I fix it ... LOL

I read some posts and find the solution

The "GitVersion.h" and "gitversion" variable are created by Makefile on Linux OS
So ... I do the same steps :-)

- Created "GitVersion.h" (because it is not in the repository)
- write Inside `const char *gitversion = "0000000000000000000000000000000000000000";` 

And now I can compile it
