### ISSUE TITLE
GPS support for cinese Radio

### ISSUE THREAD

**Issue by ik6qoo** [g4klx/MMDVMHost#320]
Is it possible to implement gps support for tyt or Chinese clones in the future?

73s de Gianluca IK6QOO

**Comment by marrold** [comment]
From Brandmeisters recentish change log-

> Fixed reception of TYT MD-380/390 GPS on MMDVM

Its my understanding that its the TYT's implementation that is flawed, and Brandmeister have put in a workaround. But I could be wrong.
