### ISSUE TITLE
MMDVMHost does not validate if Modem and Display are on same serial port

### ISSUE THREAD

**Issue by marrold** [g4klx/MMDVMHost#321]
This is 100% user error so perhaps a fix isn't required, but just to make you aware-

MMDVMHost will start if the screen and modem are configured to use the same port in the configuration. It will then proceed to throw errors (as expected)

```
M: 2017-07-22 23:02:12.035 Unknown message, type: 3C
```

Thanks
Matthew

**Comment by g4klx** [comment]
There are lots of things like that in the code. I assume that people who use the software are reasonably technically competent. If it were a user level piece of code, I'd put validation in.
