### ISSUE TITLE
Log file/display in Local time rather than UTC

### ISSUE THREAD

**Issue by yo6nam** [g4klx/MMDVMHost#334]
Hey guys,

Would you please consider making the log feature use the local time instead of UTC or at least add an option inside MMDVM.ini to switch between Local / UTC?

I have lot of errors in the syslog about MMDVMHost and YSFGateway logs not being available for use with MMDVM-Dashboard. The files are being created 3 hours later because I am on UTC+3 
Also, the live log display is off by the difference between UTC and the timezone users are.

Thanks

Razvan

**Comment by dg9vh** [comment]
Is this a Dashboard-issue or about the MMDVMHost? The Dashboard is able to be switched to your local timezone...

**Comment by dg9vh** [comment]
What kind of errors in the syslog you are talking about? Any examples to post here?

**Comment by yo6nam** [comment]
Might be the Dashboard. The log looks like : 

Oct 26 03:00:00 yo6nam lighttpd[579]: grep: /mnt/ramdisk/MMDVM-2017-10-26.log: No such file or directory
Oct 26 03:00:00 yo6nam lighttpd[579]: grep: /mnt/ramdisk/YSFGateway-2017-10-26.loggrep: /mnt/ramdisk/MMDVM-2017-10-26.log: No such file or directory
Oct 26 03:00:00 yo6nam lighttpd[579]: : No such file or directory
Oct 26 03:00:00 yo6nam lighttpd[579]: grep: /mnt/ramdisk/MMDVM-2017-10-26.log: No such file or directory
...
lots of similar lines
...
Oct 26 03:17:01 yo6nam CRON[14714]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct 26 03:17:08 yo6nam lighttpd[579]: grep: /mnt/ramdisk/YSFGateway-2017-10-26.log: No such file or directory
Oct 26 03:20:01 yo6nam CRON[14814]: (root) CMD (/usr/bin/nice /opt/vnstati.sh >/dev/null 2>&1)

**Comment by dg9vh** [comment]
First: this is not a MMDVMHost-issue, this is a dashboard-issue. Please open a corresponding issue there to get this tracked at the correct place. You can refer to this issue by link. Even if it is closed by Jonathan, it would be readable.

Second: What timezone you are running your system on? What timezone is configured in the system.

**Comment by yo6nam** [comment]
1. Will do that.
2. UTC+3 (Europe/Bucharest)

Thanks!

**Comment by dg9vh** [comment]
Jonathan: please close this issue
all further readers: please follow up to https://github.com/dg9vh/MMDVMHost-Dashboard/issues/166
