### ISSUE TITLE
Try to run OLEN without sudo -> ERROR

### ISSUE THREAD

**Issue by electrigga** [g4klx/MMDVMHost#336]
Hi folks,
I try to run MMDVM as normal user. If I do the OLED Display dosn't work: 
I: 2017-10-16 20:03:29.690     Type: OLED
bcm2835_init: Unable to open /dev/mem: Permission denied

Must I run MMDVMHost as root? Or is there a workaround?

**Comment by phl0** [comment]
There is no workaround for this as access to the GPIO pins requires root permissions.
