### ISSUE TITLE
Error compiling NetworkInfo.cpp

### ISSUE THREAD

**Issue by pjao** [g4klx/MMDVMHost#345]
g++ -g -O3 -Wall -std=c++0x -pthread -c -o NetworkInfo.o NetworkInfo.cpp
In file included from NetworkInfo.cpp:20:0:
NetworkInfo.cpp: In member function ‘void CNetworkInfo::getNetworkInterface(unsigned char*)’:
NetworkInfo.cpp:123:44: error: ‘dflt’ was not declared in this scope
  LogInfo("    Default interface is : %s" , dflt);
                                            ^
Log.h:26:42: note: in definition of macro ‘LogInfo’
 #define LogInfo(fmt, ...) Log(3U, fmt, ##__VA_ARGS__)
                                          ^
Makefile:22: recipe for target 'NetworkInfo.o' failed
make: *** [NetworkInfo.o] Error 1

**Comment by g4klx** [comment]
Try with a new pull please.

**Comment by pjao** [comment]
Fixed with https://github.com/g4klx/MMDVMHost/commit/30aa40313b07384608fc3b8c6833b77895f098a2

It's working!

**Comment by on7lds** [comment]
I always compiled it on a Pi with no errors.
Was this on another linux platform x86 ? x86_64 ?
