### ISSUE TITLE
Nextion Layout Code (Bug or Config mismatch)

### ISSUE THREAD

**Issue by AndyTaylorTweet** [g4klx/MMDVMHost#349]
In MMDVMHost.cpp the screen options (look around line 1112);

The options are 0U or 2U, but in the config the suggested options are "1" or "2"
So if you set ScreenLayout=2 - it works as expected, but
ScreenLayout=1 gives this output in the log:
I: 2017-11-23 11:21:52.535     Screen Layout: 1 (Unknown)

I have not submitted a patch, because there are a couple of ways to fix this, the simplest way is to update the documentation to be choices of 0 or 2 (rather than 1 or 2) - or MMDVMHost.cpp could be patched to check for 1U or 2U - I suspect that the option of 0U was chosen by design so that the field could be missing and not cause a failure.

**Comment by g4klx** [comment]
It sounds like a documentation bug. Thanks for spotting it.

**Comment by AndyTaylorTweet** [comment]
Thank you - that works as expected now the docs have caught up - this can be closed.


I: 2017-11-23 12:09:59.063     Screen Layout: G4KLX (Default)
I: 2017-11-23 12:10:55.463     Screen Layout: ON7LDS

**Comment by pjao** [comment]
The quick fix was rectify the documentation, but the original idea was different.

0 = auto (future use, for now it's G4KLX layout)
1 = G4KLX layout
2 = ON7LDS layout

https://github.com/g4klx/MMDVMHost/blob/master/Nextion_ON7LDS/README
