### ISSUE TITLE
Position error not known or position invalid when using Hytera PD785G

### ISSUE THREAD

**Issue by tajulon** [g4klx/MMDVMHost#351]
I  am located in GPS position: [28.488611,-16.3670609] but watching the log, every beacon with gps+voice packets looks litke this:

M: 2017-11-25 20:24:38.097 GPS position [28.488611,-163.670609] (Position error not known or position invalid)

So if you look at this, the decimal point in latitud parameter is wrong. I can not send my position to APRS.fi because is issue decoding the GPS coordinates.

I will post a log now a little long to check whats happening:

 2017-11-25 20:25:55.437 Debug: DMRSlotRX: csbk found slot/pos/centre/threshold 2 446 148 754
M: 2017-11-25 20:25:55.444 DMR Slot 2, received RF Data Preamble CSBK (6 to follow) from EA8II to 5057
M: 2017-11-25 20:25:55.498 Debug: DMRSlotRX: data header found slot/pos/centre/threshold 2 446 83 752
M: 2017-11-25 20:25:55.508 DMR Slot 2, received RF data header from EA8II to 5057, 5 blocks
M: 2017-11-25 20:25:55.561 Debug: DMRSlotRX: data payload found slot/pos/centre/threshold 2 446 74 751
M: 2017-11-25 20:25:55.621 Debug: DMRSlotRX: data payload found slot/pos/centre/threshold 2 446 66 751
M: 2017-11-25 20:25:55.679 Debug: DMRSlotRX: data payload found slot/pos/centre/threshold 2 446 53 751
M: 2017-11-25 20:25:55.741 Debug: DMRSlotRX: data payload found slot/pos/centre/threshold 2 446 50 751
M: 2017-11-25 20:25:55.798 Debug: DMRSlotRX: data payload found slot/pos/centre/threshold 2 446 57 751
M: 2017-11-25 20:25:55.803 DMR Slot 2, ended RF data transmission
M: 2017-11-25 20:25:56.123 DMR Slot 2, received network Data Preamble CSBK (1 to follow) from 5057 to EA8II
M: 2017-11-25 20:25:56.184 DMR Slot 2, received network data header from 5057 to EA8II, 0 blocks
M: 2017-11-25 20:25:56.184 DMR Slot 2, ended network data transmission
M: 2017-11-25 20:25:57.239 Debug: DMRSlotRX: csbk found slot/pos/centre/threshold 2 446 69 758
M: 2017-11-25 20:25:57.249 DMR Slot 2, received RF Data Preamble CSBK (7 to follow) from EA8II to 5057
M: 2017-11-25 20:25:57.296 Debug: DMRSlotRX: csbk found slot/pos/centre/threshold 2 446 54 748
M: 2017-11-25 20:25:57.302 DMR Slot 2, received RF Data Preamble CSBK (6 to follow) from EA8II to 5057
M: 2017-11-25 20:25:57.358 Debug: DMRSlotRX: data header found slot/pos/centre/threshold 2 446 28 744
M: 2017-11-25 20:25:57.368 DMR Slot 2, received RF data header from EA8II to 5057, 5 blocks
M: 2017-11-25 20:25:57.420 Debug: DMRSlotRX: data payload found slot/pos/centre/threshold 2 446 35 744
M: 2017-11-25 20:25:57.482 Debug: DMRSlotRX: data payload found slot/pos/centre/threshold 2 446 42 744
M: 2017-11-25 20:25:57.539 Debug: DMRSlotRX: data payload found slot/pos/centre/threshold 2 446 45 743
M: 2017-11-25 20:25:57.600 Debug: DMRSlotRX: data payload found slot/pos/centre/threshold 2 446 45 743
M: 2017-11-25 20:25:57.661 Debug: DMRSlotRX: data payload found slot/pos/centre/threshold 2 446 43 743
M: 2017-11-25 20:25:57.662 DMR Slot 2, ended RF data transmission
M: 2017-11-25 20:25:57.993 DMR Slot 2, received network Data Preamble CSBK (1 to follow) from 5057 to EA8II
M: 2017-11-25 20:25:58.045 DMR Slot 2, received network data header from 5057 to EA8II, 0 blocks
M: 2017-11-25 20:25:58.045 DMR Slot 2, ended network data transmission
M: 2017-11-25 20:27:25.079 Debug: DMRSlotRX: csbk found slot/pos/centre/threshold 2 446 -84 769
M: 2017-11-25 20:27:25.088 DMR Slot 2, received RF Data Preamble CSBK (7 to follow) from EA8II to 5057
M: 2017-11-25 20:27:25.140 Debug: DMRSlotRX: csbk found slot/pos/centre/threshold 2 446 -71 767
M: 2017-11-25 20:27:25.146 DMR Slot 2, received RF Data Preamble CSBK (6 to follow) from EA8II to 5057
M: 2017-11-25 20:27:25.197 Debug: DMRSlotRX: data header found slot/pos/centre/threshold 2 446 -15 760
M: 2017-11-25 20:27:25.203 DMR Slot 2, received RF data header from EA8II to 5057, 5 blocks
M: 2017-11-25 20:27:25.259 Debug: DMRSlotRX: data payload found slot/pos/centre/threshold 2 445 -28 771
M: 2017-11-25 20:27:25.320 Debug: DMRSlotRX: data payload found slot/pos/centre/threshold 2 445 -35 782
M: 2017-11-25 20:27:25.377 Debug: DMRSlotRX: data payload found slot/pos/centre/threshold 2 445 -37 791
M: 2017-11-25 20:27:25.440 Debug: DMRSlotRX: data payload found slot/pos/centre/threshold 2 445 -19 797
M: 2017-11-25 20:27:25.500 Debug: DMRSlotRX: data payload found slot/pos/centre/threshold 2 445 14 793
M: 2017-11-25 20:27:25.501 DMR Slot 2, ended RF data transmission
M: 2017-11-25 20:27:26.428 DMR Slot 2, received network Data Preamble CSBK (1 to follow) from 5057 to EA8II
M: 2017-11-25 20:27:26.491 DMR Slot 2, received network data header from 5057 to EA8II, 0 blocks
M: 2017-11-25 20:27:26.491 DMR Slot 2, ended network data transmission
M: 2017-11-25 20:27:26.820 Debug: DMRSlotRX: csbk found slot/pos/centre/threshold 2 446 25 761
M: 2017-11-25 20:27:26.829 DMR Slot 2, received RF Data Preamble CSBK (7 to follow) from EA8II to 5057
M: 2017-11-25 20:27:26.877 Debug: DMRSlotRX: csbk found slot/pos/centre/threshold 2 446 -2 771
M: 2017-11-25 20:27:26.883 DMR Slot 2, received RF Data Preamble CSBK (6 to follow) from EA8II to 5057
M: 2017-11-25 20:27:26.939 Debug: DMRSlotRX: data header found slot/pos/centre/threshold 2 446 15 760
M: 2017-11-25 20:27:26.949 DMR Slot 2, received RF data header from EA8II to 5057, 5 blocks
M: 2017-11-25 20:27:27.000 Debug: DMRSlotRX: data payload found slot/pos/centre/threshold 2 446 10 760
M: 2017-11-25 20:27:27.061 Debug: DMRSlotRX: data payload found slot/pos/centre/threshold 2 446 -10 761
M: 2017-11-25 20:27:27.119 Debug: DMRSlotRX: data payload found slot/pos/centre/threshold 2 446 -25 760
M: 2017-11-25 20:27:27.180 Debug: DMRSlotRX: data payload found slot/pos/centre/threshold 2 446 -18 755
M: 2017-11-25 20:27:27.237 Debug: DMRSlotRX: data payload found slot/pos/centre/threshold 2 446 -12 749
M: 2017-11-25 20:27:27.242 DMR Slot 2, ended RF data transmission
M: 2017-11-25 20:27:27.568 DMR Slot 2, received network Data Preamble CSBK (1 to follow) from 5057 to EA8II
M: 2017-11-25 20:27:27.626 DMR Slot 2, received network data header from 5057 to EA8II, 0 blocks
M: 2017-11-25 20:27:27.626 DMR Slot 2, ended network data transmission

Need to fix this bug to every hytera GPS user. 

73 from EA8II, Edu // Tenerife Island, Spain

**Comment by tajulon** [comment]
even the GPS position sended throw SMS to 5057 are rejected because comes with a invalid GPS data position.

**Comment by g4klx** [comment]
ON7LDS?

**Comment by tajulon** [comment]
Hi Jonathan. Do i not undrestand. What you mean with ON7LDS? Mi callsign is EA8II.

The mmdvmhost is updated and arduino too.

All works fine but gps position has the issue described. Only one position has been sended to APRS.fi yesterday.

Eduardo Díaz.

**Comment by g4klx** [comment]
Because ON7LDS wrote that code.

**Comment by g4klx** [comment]
I have modified the code myself. One part of the message was wrong, about the error. I have also changed the method of value calculation. Please try it again.

**Comment by on7lds** [comment]
I saw this post a bit too late.
Is it solved now ? If not, I'll see in to it this evening.

**Comment by g4klx** [comment]
Please test it on a new build. I can’t test it.

**Comment by on7lds** [comment]
I'll do, but it will be near the end of the week or even the week-end.
I have no radio with GPS and will have to borrow the one I used when I wrote the code (I meet that OM mostly on Fridays).

**Comment by tajulon** [comment]
I will try tomorrow. I have read the Messages now. Tomorrow i will tell you something about.

Un saludo,

Eduardo Díaz.

**Comment by on7lds** [comment]
If there is still something wrong, please set your loglevel high enough so I/we can see what is going on.
I'm not able to travel to the 'left' of the prime meridian on short notice to test that part myself :-))

**Comment by g4klx** [comment]
I modified the code. You were handling the 2's complement values as sign and magnitude. Also the message was incorrect. I've made untested changes which I hope will fix this.

**Comment by on7lds** [comment]
Thanks. I tested the conversion code first with some self-created values , so I clearly must have missed something there. Afterwards I used a radio to test it, but since I live in the '+' side of the coordinates, I clearly missed the error.
I'll test the new code this week anyway, and Eduardo Díaz also will. Should be sufficient then, I hope.

I see indeed you removed 'or position invalid' , I got that from the note under the table at ETSI TS 102 361-2  **7.2.15 Position Error** : (value 111) 'May be used to indicate the MS failed to acquire valid location data'.

**Comment by g4klx** [comment]
I've modified the code again to not print anything if that value is set. I could test for a negative longitude because I am also West of Greenwich but my Hytera doesn't include embedded data.

**Comment by on7lds** [comment]
I have made a detour after work to collect my mate's PD985 so I could do some test this evening.
 Although it also looked a good idea to me to drop the data in case of 0b111, the Hytera always seems to send 0b111 as position error (maybe meaning 'i do not want to do an effort of calculating the error so I'll say I do not know'), so we'll have to return to 'not known' (and indeed drop the 'not valid').
It might send other position error codes when moving (will try to test this tomorrow when riding to work) but in any case we can't drop the 0b111

**Comment by g4klx** [comment]
I've changed the code on the master branch to not drop the data and also fixed the compile issues that you raised in the PM. I hope it works.

**Comment by on7lds** [comment]
Compiling OK
Position calculation OK
Now I only have to make a trip to England for the West of Greenwich test... :-)
(hopefully Eduardo Díaz can do this test)
(note: The hytera keeps sending 0b111, even when moving)

**Comment by tajulon** [comment]
Ok sorry for my stand by time but my work is heavy. I have compiled the updated version and this is the ressult:




The gps position is fine but position error is logged and my position is not going to APRS.fi network




Un saludo,

Eduardo Díaz.

**Comment by on7lds** [comment]
So the position is correct. 'Position error is not known' is, as you can read in this thread, the way Hytera radios handle that field. So for MMDVMHost it is working fine.

It is not MMDVMHost that sends the GPS data to aprs.fi, the data are only decoded and logged for information. A local dashboard or display could then use this info to present position data to the user.

It is your radio who has to send the data. You have to do the correct settings in your radio. For a Hytera this is Conventional -> General Setting -> Network -> RSS & GPS Radio ID. The ID you have to put here depends on your local BM server, so please check there. 
http://www.brandmeister.es/2017/09/24/configuracion-hytera-para-aprs/ might be what you need.

**Comment by tajulon** [comment]
Hi !

Sorry but do not undrestand “Position error is not known' is, as you can read in this thread, the way Hytera radios handle that field. So for MMDVMHost it is working fine.”

I am sending the voice+gps frames. Why i read position error? Mmdvmhost can not decode my Hytera position?

Aniway i am sending the sms to 5057 private id as the tutorial explain and no way to see my position on aprs.fi

Do you want to see my hytera codeplug?

Eduardo Díaz.

**Comment by on7lds** [comment]
The Hytera always sends 'Position error is not known'. This is an Hytera issue.
This is not a problem, the position itsself is correct.

Voice + GPS goes to the receiving station, MMDVMHost decodes this for your information, but does not do anything with it.

For sending your position to the network, you better try to contact someone in your country who has a working codeplug. Sending the GPS data to aprs.fi is something your local BrandMeister server handles (the one you configure in MMDVM.ini) and is configured by the BrandMeister server sysop.
