### ISSUE TITLE
Dstar interruption" false end of transmission "

### ISSUE THREAD

**Issue by IK8JHL** [g4klx/MMDVMHost#354]
I have a random interruption during a reception  in Dstar mode , MMDVM receive end of transmission but its not real ,

This is a  log of repeater  MMDVM NTH of  IZ7AUH, but i test also with other 3 repeater MMDVM  as you can read, MMDVM receive end of transmission but its not real.

D: 2017-11-26 17:57:48.700 D-Star, audio sequence no. 20, errs: 0/48 (0.0%)
D: 2017-11-26 17:57:48.721 D-Star, audio sequence no. 0, errs: 0/48 (0.0%)
D: 2017-11-26 17:57:48.742 D-Star, audio sequence no. 1, errs: 0/48 (0.0%)
D: 2017-11-26 17:57:48.763 D-Star, audio sequence no. 2, errs: 0/48 (0.0%)
D: 2017-11-26 17:57:48.780 D-Star, audio sequence no. 3, errs: 0/48 (0.0%)

... i dont release PTT but system receive this  .....

M: 2017-11-26 17:57:48.785 D-Star, received RF end of transmission, 2.2 seconds, BER: 0.0%

... after MMDVM continue transmission.....

M: 2017-11-26 17:57:57.877 D-Star, received RF header from IZ7AUH /HOME to XRF020AL
D: 2017-11-26 17:57:57.894 D-Star, audio sequence no. 0, errs: 0/48 (0.0%)
D: 2017-11-26 17:57:57.916 D-Star, audio sequence no. 1, errs: 0/48 (0.0%)
D: 2017-11-26 17:57:57.935 D-Star, audio sequence no. 2, errs: 0/48 (0.0%)
D: 2017-11-26 17:57:57.956 D-Star, audio sequence no. 3, errs: 0/48 (0.0%)

Maybe a bug in the software ,some people have experience on this issue ?

**Comment by IW8ELN** [comment]
I noticed the same problem on my system being prepared. In DStar there are these interruptions even without leaving the PTT. Alignments have been made in the correct way, BER is 0.0 and software and firmware are up to date. How can it be resolved?

**Comment by ea7gwc** [comment]
This problem exists a long time ago.
But there is no solution at the moment ........ I hope someday
correct this.
