### ISSUE TITLE
Segfault:

### ISSUE THREAD

**Issue by jpronans** [g4klx/MMDVMHost#357]
Did a git pull today to update EI7CDD repeater. I got  commit 35629f87085720f499e7ffc9f10d5b7067750118

When It failed to start I reverted, but this evening I ran it through gdb and got
M: 2017-12-01 20:21:53.655 MMDVMHost-20170719 is running

Program received signal SIGSEGV, Segmentation fault.
CDisplay::clock (this=0x67c510, ms=1) at Display.cpp:321
321		clockInt(ms);

We don't have any displays defined.  I'll continue looking to see if I can find the root cause.

**Comment by jpronans** [comment]
Hmm, If I remove the virtual from clockInt declaration in Display.h, the issue goes away.  I'm not a C++ dev so I'm sure someone will quickly find the proper fix.

**Comment by g4klx** [comment]
Did you do a make clean before doing a make?

**Comment by jpronans** [comment]
On the Repeater/Pi (which I don't have access to now), I don't know, it was its own build script, so I cannot check.  I have gone back through my own command history, and I doubt I did a full make clean, mea culpa.
