### ISSUE TITLE
CW ID

### ISSUE THREAD

**Issue by r7rbb** [g4klx/MMDVMHost#362]
Hi.
Is it possible to make roaming beacons simultaneously with CW id enabled?

We had registred several repeaters officially and a rule of registration requries to transmit CW id  each 15 idle minutes.
But i need roaming beacons also...
Thanks

**Comment by g4klx** [comment]
The handling of the roaming beacons has now changed. They are usually every 60 seconds, so too quick for the CW beacon. Conversely a roaming beacon every 10 minutes would be useless.

**Comment by r7rbb** [comment]
I undertood this matter clearly. for transmitting  CWID, pause of 60 seconds will be enough as i asume.
so if repeater is idle. CWID counts its time even if every 60 secs beacon is transmitted.  i belive that will be  such case that timer of CWID will reset between 60 secs of beacons transmitting an i will hear CWID.

so, i another words... is it possibble to remove CW id transmitting lock when beacon string  in ini file is 1?

**Comment by g4klx** [comment]
CW Id was like that originally but people didn't like it, so we have what we have now. Most people seem happy with it, so it won't change.

**Comment by r7rbb** [comment]
Thanks. If most of people are happy i will not go against.

**Comment by UB1AAM** [comment]
Set the time for the CW ID in seconds, then the time will not match. For example 590 seconds.
