### ISSUE TITLE
Self Only Bug in YSFMode 

### ISSUE THREAD

**Issue by dg7abl** [g4klx/MMDVMHost#369]
There is a bug in YSF mode with  the option "Self Only = 1".

Home Call (Me) DG7ABL  -- Test Call = DG7ABM
If Self Only active in YSF Mode and a foreign Call sends on the freqeuncy the call was rejected first correctly. 

But after the reject, the home call is sending (DG7ABL) again, the call was also rejected. and the log show DG7ABL is DG7ABM: See the log please: 

I: 2018-01-08 21:15:13.426     TX Hang: 3s
I: 2018-01-08 21:15:13.426     Mode Hang: 20s
I: 2018-01-08 21:15:13.426 YSF RF Parameters
I: 2018-01-08 21:15:13.426     Low Deviation: no
I: 2018-01-08 21:15:13.426     Remote Gateway: no
I: 2018-01-08 21:15:13.426     Self Only: yes
I: 2018-01-08 21:15:13.426     DSQ: no
I: 2018-01-08 21:15:13.426     Mode Hang: 20s
M: 2018-01-08 21:15:13.426 MMDVMHost-20180103_Pi-Star is running
M: 2018-01-08 21:15:23.582 DMR, Logged into the master successfully
M: 2018-01-08 21:16:17.509 YSF, received RF late entry from DG7ABL     to ALL   
M: 2018-01-08 21:16:18.409 YSF, received RF end of transmission, 1.0 seconds, BER: 1.4%
M: 2018-01-08 21:17:10.924 YSF, invalid access attempt from DG7ABM
M: 2018-01-08 21:17:48.629 YSF, invalid access attempt from DG7ABM
_At this time the the Home Call DG7ABL is sending again but:_
M: 2018-01-08 21:17:51.729 YSF, invalid access attempt from DG7ABM 

It looks like it's in a loop after receiving a foreign call.

The bug is in the compiled version of MMDVM_Host and in the Pi-Star Image 

Please check and thank you very much for the great software. 

73 de DG7ABL

**Comment by g4klx** [comment]
I think I found the bug. I've pushed the fix to GitHub.

**Comment by dg7abl** [comment]
Nice. Thank You!!!!!
