### ISSUE TITLE
RRS issue

### ISSUE THREAD

**Issue by SA7BNT** [g4klx/MMDVMHost#371]
Hallo @all im running in at some new strange issue. Im using RRS since i started with DMR on my PD785 (NOT G) and it runs fine. Since yesterday (i´m running an update to the latest MMDVMHost) i have the issue that i´m getting a Private Call from 5057. I can verify this problem. When i go to a TG without RRS waiting some time then switch to an TG channel with RRS im getting an PC from 5057. Same is when i listning to an TG and some other TG is taken over and RRS is aktivated in this TG same thing is happend. If you want some video of the issue let me know that then i will fix it.

Now i have tested a little bit and the last commit version witch is working without issue is the 51e0bf0

Hope that can help you to finde the issue.

SA7BNT de Tim

BTW: thats the log

M: 2018-01-12 09:21:17.305 Downlink Activate received from SA7BNT
M: 2018-01-12 09:21:17.495 DMR Slot 2, received RF data header from SA7BNT to 5057, 2 blocks
M: 2018-01-12 09:21:17.615 DMR Slot 2, ended RF data transmission
M: 2018-01-12 09:21:18.416 DMR Slot 2, received network Data Preamble CSBK (3 to follow) from 5057 to SA7BNT
M: 2018-01-12 09:21:18.781 DMR Slot 2, received network late entry from 5057 to SA7BNT
M: 2018-01-12 09:21:20.279 DMR Slot 2, network watchdog has expired, 1.6 seconds, 96% packet loss, BER: 0.0%
M: 2018-01-12 09:21:21.175 DMR Slot 2, received network late entry from 5057 to SA7BNT

Packet loss 98%

**Comment by g0wfv** [comment]
Jon is currently looking into a bug in data transmission/reception - have a
look on the MMDVM Yahoo group where it is being discussed ...

https://groups.yahoo.com/neo/groups/mmdvm/conversations/topics/16026

73
Tony

>

-- 

A J Corbett
G0WFV

**Comment by dk5ras** [comment]
I can confirm this happening with Motorola radios and ARS, too. Both ARS and SMS are affected.

73
Ralph, dk5ras.

**Comment by SA7BNT** [comment]
Working for me after Update to cae6bed.

Thanks
73
