### ISSUE TITLE
README is in conflict with License

### ISSUE THREAD

**Issue by d235j** [g4klx/MMDVMHost#373]
I noticed that the README indicates:

> This software is licenced under the GPL v2 and is intended for amateur and educational use only. Use of this software for commercial purposes is strictly forbidden.

However, this is not the case under the GPL v2. The GPL v2 does not prohibit commercial use, but it does require release of source code alongside binaries, even if use is commercial. [And this restriction cannot be added on top of the GPL.](https://www.gnu.org/licenses/gpl-faq.en.html#NoMilitary)

(More generally, it is difficult to place restrictions on commercial use for Free and Open Source Software — as this makes the software no longer Free and Open Source! This is because portions of code, e.g. in this project, may be useful for some other GPLv2-compatible project which is more suited for something like general packet radio / repeaters, and that may fall under "commercial use" even if the software is not being sold. Most projects concerned about abuse by commercial groups use licenses such as the GPL and AGPL to force these groups to release their source code if they are using the software.)

Therefore I suggest that this statement be reworded to be more like:
> Use of this software for commercial purposes is very highly discouraged and might be illegal.

Or something similarly worded as not to indicate that commercial use is completely prohibited, but that it will probably get one into trouble.

**Comment by d235j** [comment]
@g4klx is there any plan to address this issue? It makes the software undistributable, as the GPL does not allow adding additional restrictions.

However, there are some source files that are licensed under noncommercial use and therefore cannot be combined with GPL software, which additionally makes this software undistributable. The source files in question include the following:
https://github.com/g4klx/MMDVMHost/blob/master/BCH.cpp
https://github.com/g4klx/MMDVMHost/blob/master/Golay24128.cpp (likely, same author as BCH.cpp)

**Comment by n8ohu** [comment]
I believe this will change when people that develop hardware solutions using his software start doing their own tech support on the software side, instead of expecting him to do so.

**Comment by d235j** [comment]
@n8ohu I don't see how software tech support is relevant to a license conflict?

**Comment by DL6AKU** [comment]
I have just noticed the same.

You cannot release software under a GPLv2 license and at the same time restrict its use further (eg. non-commercial, or "not for military use").

Why was this issue closed? This is not resolved.

**Comment by ccoors** [comment]
I agree. He also closed a similar issue in DMRGateway without any comment.
https://github.com/g4klx/DMRGateway/issues/72

This is not acceptable. Please fix it!

**Comment by d235j** [comment]
@g4klx 
There is a detailed discussion of Section 6 of the GPLv2 here that explains why this noncommercial term is useless.

> The second sentence of GPLv2 §6 does the opposite; it bounds from the top. It prohibits any licensor along the distribution chain from placing additional restrictions on the user. In other words, no additional requirements may trump the rights and freedoms given by GPLv2.

https://copyleft.org/guide/comprehensive-gpl-guidech8.html#x11-530007.3

The code in here that is in conflict with the GPL needs to be handled in other ways (by requesting that the authors relicense, or rewriting), not adding useless terms.

**Comment by TheButterZone** [comment]
If the intent is to prohibit commercial use, wouldn't Apache 2.0 with Commons Clause License Condition v1.0 be more appropriate?
