### ISSUE TITLE
JitterBuffer introduces DMR ghost private calls

### ISSUE THREAD

**Issue by dk5ras** [g4klx/MMDVMHost#377]
The JitterBuffer implemention introduced ghost calls on DMR Motorola radios when those use data services like ARS, GPS and SMS/TMS. Those calls appear coming from the data call destination and are quite irritating if not annoying. 

A maybe quick solution would be making this JitterBuffer switchable from the .ini, as many (if not most) installations also get along without it quite conveniently.

**Comment by mrickey** [comment]
Since turning on GPS/ARS on my MD782G, I am getting private calls from 310999. They don't happen too often, and mostly around the time I startup the radio.

**Comment by pjao** [comment]
After the last PR, that says "Make the jitter buffer switchable." (https://github.com/g4klx/MMDVMHost/commit/43fdb770a9e7818ff3d22bfd40c7305a7d41e267), any change? 
Remember to turn JitterEnabled=1 and JitterEnabled=0 to test.

**Comment by mrickey** [comment]
I have "jitter=300" in the DMR Configuration section. I don't see a "JitterEnabled" setting. Does it go into the same section?

**Comment by pjao** [comment]
@mrickey Yep, above!

Should be
JitterEnabled=1 or JitterEnabled=0
Jitter=500

**Comment by stefansaraev** [comment]
FYI. with and without JitterBuffer enabled in MMDVM.ini, I do still get ghost calls sometimes after sending an sms to brandmeister (received network late entry...). I didn't test voice to/from xlx yet

**Comment by lb5je** [comment]
Do you guys use the latest MMDVM modem firmware? Did help at my repeater, using Hytera radios to send GPS data. No Motorolas to test with...


LB5JE

**Comment by dk5ras** [comment]
Motorola, Duplex-MMDVM, BM network...with ARS the effect is gone, but with TMS/SMS I still receive a ghost call from the receiver right after sending the message. I am using a repeater builder STM32 board, don't know if the modem has some influence, too. However a big thumbs up that this issue is worked on!!

**Comment by juribeparada** [comment]
dk5ras, could you put the MMDVMHost log here with the problem?

**Comment by stefansaraev** [comment]
back to normal with JitterEnabled=0 after eed32c8cbe90d7d9fcb293d30167af72abe72d16 

thanks @g4klx @juribeparada

**Comment by SA7BNT** [comment]
Still problem with aktuell MMDVMHost commit and DMRGateway in XLX network. Downgrade MMDVMHost to "commit 51e0bf0" then are the "DMR ghost private calls" in the XLX Network gone.

**Comment by stefansaraev** [comment]
@SA7BNT did you test with JitterEnabled=0 ?

//cc @pjao

**Comment by SA7BNT** [comment]
@stefansaraev yes !!! Do not work for me. Still same problem as in #372

**Comment by stefansaraev** [comment]
@SA7BNT 
even before jitterbuffer rework I've had ghost calls on xlx at the end of my transmission. this is not a new issue.

so, please test with JitterEnabled=0 and check if you can hear others on your xlx reflector. ignore the "network late" entries in the log and the ghost calls. just check if audio is ok in both directions.

**Comment by SA7BNT** [comment]
@stefansaraev when my PD785 recive an PC after i stop transmitting, when i´m on XLX Network with JitterEnabled=0 then there is still a problem. It is not possible to make a QSO on XLX. Rollback to "commit 51e0bf0" resolv this issue. I can make a video if you do not trust me ;)

**Comment by stefansaraev** [comment]
works fine for me on xlx with JitterEnabled=0 (please double check if it's in your [DMR Network] section). as said, I still get ghost pc after my transmission and it's not new issue, it was there even before jitterbuffer rework. I can hear others just fine, and they also hear my voice ok-ish..

**Comment by SA7BNT** [comment]
Possible to get you on some messenger? will not spam here

**Comment by stefansaraev** [comment]
irc. seo on freenode

**Comment by SA7BNT** [comment]
Nothing what i´m using.

**Comment by lb5je** [comment]
@SA7BNT Could you give us a quick guide on how to rollback to the "commit 51e0bf0" ?

**Comment by SA7BNT** [comment]
@lb5je no secret. 
Just from the last MMDVMHost commit make a "git checkout 51e0bf0" and then "make clean all" 
With "git checkout master" you back in master commit
