### ISSUE TITLE
Feature Request: send raw data to modem (2FSK@1200/2400bps)

### ISSUE THREAD

**Issue by g2rHP7prvJqO** [g4klx/MMDVMHost#397]
I would like to implement a routine to transmit "raw" 2FSK at 1200 or 2400bps to ultimately implement POCSAG transmission function and happy to put my own hands in the dirt for the code.
Depending on the communication protocol between MMDVMHost and MMDVM modem, it seems to me that 2FSK@1200bps could be compared to 4FSK@9600bps: it's just 8 times slower and only uses the 2 extreme deviation levels instead of 4 (no inner deviation). In terms of information, 1 bit of 2FSK information at 1200bps becomes 2 bytes of repeated identical data in 4FSK at 9600bps.
I suppose the mods to implement this would have to go in Modem.h and Modem.cpp but is there any human readable description of the protocol between the MMDVM Modem and MMDVMHost to confirm whether my approach is valid or if any modification needs to be done in MMDVM itself?

**Comment by f4exb** [comment]
I second g2rHP7prvJqO in his request for a textual description of the split of responsibilities between MMDVM Modem (MMDVM_HS I suppose) and MMDVMHost pieces and also a detailed description of the communication between the two.

I think this is a preliminary to any useful collaboration to this project.

**Comment by f4exb** [comment]
Actually there is some documentation about the MMDVM communication protocol here: http://www.maze.io/media/posts/radio/MMDVM%20Specification%2020150922.pdf
