### ISSUE TITLE
OLED Makefile would not compile on Raspbian

### ISSUE THREAD

**Issue by phl0** [g4klx/MMDVMHost#400]
With https://github.com/g4klx/MMDVMHost/commit/0a101b48c3fe334f1a8bb40a96d49be8d83e1f38 @stefansaraev included "-li2c" in https://github.com/phl0/MMDVMHost/blob/master/Makefile.Pi.OLED. As far as I have researched this does not work on a Raspbian installation. Also installation of libi2c-dev did not fix it as @AndyTaylorTweet statet.
Would it be goot to use -lwiringPi instead? At least it does what it is supposed to do on my Raspbian. PR is prepared here: https://github.com/phl0/MMDVMHost/tree/wiringPiandOLED.
What do you think @stefansaraev @AndyTaylorTweet ?

**Comment by stefansaraev** [comment]
sure, it looks like raspbian ships i2c-tools 3.x that's missing the shared/static lib. if it works for you with wiringPi, please PR your change.

**Comment by phl0** [comment]
What version were you using?

**Comment by stefansaraev** [comment]
not using raspbian anymore, but I had libi2c0 and i2c-dev 4.0 (from buster)

**Comment by AndyTaylorTweet** [comment]
I'm using a modified Makefile here, my version of Raspbian is getting quite old so I put it down to that and didn't bother investigating any further. (its fully patched but its not been upgraded to Stretch yet).

Yes I reverted back to using the WiringPi libs and that is still working well for me.

**Comment by phl0** [comment]
I have PRed it: https://github.com/g4klx/MMDVMHost/pull/401
