### ISSUE TITLE
Feature Request: Remote Control Commands

### ISSUE THREAD

**Issue by onemikedelta** [g4klx/MMDVMHost#404]
Is it possible to implement a feature that allows sending remote stun/revive/monitor commands only by a spesific id(sysop)?

**Comment by g0wfv** [comment]
Is [this](https://github.com/g4klx/MMDVMHost/blob/master/linux/tg_shutdown.sh) what you're looking for ...?

**Comment by onemikedelta** [comment]
Unfortunately no. Currently we are using Hytera repeater and everybody can send remote stun command to everybody for example. I request that only sysop ids should be able to send these commands which are not used between amateurs usually but needed in case of lost radio, radio taken by childs etc. By the way these can also be used to remote turn off and then turn on repeaters. It is not halting system completely or rebooting but turning repeating on/off just like dtmf commands that we used to control analog repeaters.

**Comment by g4klx** [comment]
It sounds dangerous. This sounds like requirements for commercial use.

**Comment by onemikedelta** [comment]
It is not for commercial. It is for preventing nasty jokes but keeping this functions. In commercial world user devices cannot send these commands I believe.
