### ISSUE TITLE
make flash_D13

### ISSUE THREAD

**Issue by SA7SKY** [g4klx/MMDVMHost#406]
After latest update (2018-03-18)
make flash_D13
for my MD390 leads to an ERROR,
alternative usage of
make flash
ends up at the same point...
Never had that before. Was all fine by routine until now.
//Helge

**Comment by juribeparada** [comment]
This is MMDVMHost project, not md380tools. You need to see here: https://github.com/travisgoodspeed/md380tools/

**Comment by SA7SKY** [comment]
sorry
