### ISSUE TITLE
Overflow in the DMR Slot RF Queue - invoked from writeQueueNet()

### ISSUE THREAD

**Issue by r4d10n** [g4klx/MMDVMHost#418]
Hello!

I have been playing around with the modem code (g4klx/mmdvm) and while experimenting with it, I am facing this overflow error, almost as soon as the incoming traffic from the BM network comes in. First few transmissions pass through to the modem all right, but soon no more traffic gets forwarded. 

![screenshot from 2018-05-04 22-20-21](https://user-images.githubusercontent.com/192318/39640751-9cfaa4be-4fe9-11e8-9a73-2557d84a460a.png)

I was thinking there would be some problem with the modem access and buffering, but this error log is being  generated from the writeQueueNet(), not from the writeQueueRF() as I would have expected.

Could anybody elucidate the data flow path and the possible reasons for this error? I have tried my share of debugging with logging and gdb, but not quite able to follow the stream.

**Comment by iball** [comment]
I'm seeing the same thing and haven't even touched my mmdvmhost code at all.
I re-compiled from the latest source and still seeing it.

**Comment by d51r3verse** [comment]
He does not allow anybody to elucidate the data flow.
therefore he using same overflow messages for both rf2net, net2rf,
does not separate queue for net2rf, rf2net,
also lack of detailed RF(TX/RX)&NET(RX/TX) status tracking of both timeslots,
but supports duplex modes.(what a clever he is! :1st_place_medal: )

Only clever/smart ppl can understand his codes and data flow directions.

**Comment by shawnchain** [comment]
read the project https://github.com/LX3JL/xlxd/ before posting any comments here. ;-)
