### ISSUE TITLE
MMDVMHost_pocsag crash

### ISSUE THREAD

**Issue by f5bcb** [g4klx/MMDVMHost#431]
Hi,
MMDVMHost pocsag branch, compiled using Makefile.Pi.OLED crash : 

MMDVMHost: POCSAGControl.cpp:101: bool CPOCSAGControl::processData(): Assertion `m_network != __null' failed.

Hereunder complete startup.

73,
Jeff F5BCB

pi@f5zjh:~/Applications/MMDVMHost $ sudo ./MMDVMHost /home/pi/MMDVM.ini_pocsag
I: 2018-06-14 15:02:19.765 This software is for use on amateur radio networks only,
I: 2018-06-14 15:02:19.766 it is to be used for educational purposes only. Its use on
I: 2018-06-14 15:02:19.766 commercial networks is strictly prohibited.
I: 2018-06-14 15:02:19.766 Copyright(C) 2015-2018 by Jonathan Naylor, G4KLX and others
M: 2018-06-14 15:02:19.766 MMDVMHost-20180517 is starting
M: 2018-06-14 15:02:19.766 Built 16:38:58 Jun 14 2018 (GitID #0000000)
I: 2018-06-14 15:02:19.766 General Parameters
I: 2018-06-14 15:02:19.766     Callsign: F5ZJH
I: 2018-06-14 15:02:19.766     Id: 208501
I: 2018-06-14 15:02:19.766     Duplex: yes
I: 2018-06-14 15:02:19.766     Timeout: 180s
I: 2018-06-14 15:02:19.766     D-Star: enabled
I: 2018-06-14 15:02:19.768     DMR: enabled
I: 2018-06-14 15:02:19.770     YSF: enabled
I: 2018-06-14 15:02:19.771     P25: enabled
I: 2018-06-14 15:02:19.771     NXDN: disabled
I: 2018-06-14 15:02:19.772     POCSAG: enabled
I: 2018-06-14 15:02:19.773 Modem Parameters
I: 2018-06-14 15:02:19.773     Port: /dev/ttyACM0
I: 2018-06-14 15:02:19.774     RX Invert: yes
I: 2018-06-14 15:02:19.775     TX Invert: no
I: 2018-06-14 15:02:19.775     PTT Invert: no
I: 2018-06-14 15:02:19.776     TX Delay: 100ms
I: 2018-06-14 15:02:19.776     RX Offset: 0Hz
I: 2018-06-14 15:02:19.777     TX Offset: 0Hz
I: 2018-06-14 15:02:19.778     RX DC Offset: 0
I: 2018-06-14 15:02:19.778     TX DC Offset: 0
I: 2018-06-14 15:02:19.779     RF Level: 100.0%
I: 2018-06-14 15:02:19.779     DMR Delay: 0 (0.0ms)
I: 2018-06-14 15:02:19.780     RX Level: 100.0%
I: 2018-06-14 15:02:19.781     CW Id TX Level: 50.0%
I: 2018-06-14 15:02:19.782     D-Star TX Level: 50.0%
I: 2018-06-14 15:02:19.782     DMR TX Level: 51.0%
I: 2018-06-14 15:02:19.783     YSF TX Level: 50.0%
I: 2018-06-14 15:02:19.783     P25 TX Level: 50.0%
I: 2018-06-14 15:02:19.784     NXDN TX Level: 50.0%
I: 2018-06-14 15:02:19.785     POCSAG TX Level: 50.0%
I: 2018-06-14 15:02:19.785     RX Frequency: 439825000Hz (439825000Hz)
I: 2018-06-14 15:02:19.786     TX Frequency: 430425000Hz (430425000Hz)
M: 2018-06-14 15:02:19.787 Opening the MMDVM
I: 2018-06-14 15:02:21.802 MMDVM protocol version: 1, description: MMDVM 20180327 (D-Star/DMR/System Fusion/P25/NXDN) 12.0000MHz (Build: 16:51:26 Jun 10 2018)
I: 2018-06-14 15:02:21.824 Display Parameters
I: 2018-06-14 15:02:21.825     Type: OLED
I: 2018-06-14 15:02:22.203 D-Star Network Parameters
I: 2018-06-14 15:02:22.203     Gateway Address: 127.0.0.1
I: 2018-06-14 15:02:22.203     Gateway Port: 20010
I: 2018-06-14 15:02:22.203     Local Port: 20011
I: 2018-06-14 15:02:22.203     Mode Hang: 3s
M: 2018-06-14 15:02:22.204 Opening D-Star network connection
I: 2018-06-14 15:02:22.205 DMR Network Parameters
I: 2018-06-14 15:02:22.205     Address: 127.0.0.1
I: 2018-06-14 15:02:22.205     Port: 62031
I: 2018-06-14 15:02:22.206     Local: 62032
I: 2018-06-14 15:02:22.206     Jitter: 380ms
I: 2018-06-14 15:02:22.207     Slot 1: enabled
I: 2018-06-14 15:02:22.207     Slot 2: enabled
I: 2018-06-14 15:02:22.207     Mode Hang: 3s
I: 2018-06-14 15:02:22.207 Info Parameters
I: 2018-06-14 15:02:22.208     Callsign: F5ZJH
I: 2018-06-14 15:02:22.208     RX Frequency: 439825000Hz
I: 2018-06-14 15:02:22.208     TX Frequency: 430425000Hz
I: 2018-06-14 15:02:22.208     Power: 46W
I: 2018-06-14 15:02:22.208     Latitude: 47.252781deg N
I: 2018-06-14 15:02:22.208     Longitude: -1.574440deg E
I: 2018-06-14 15:02:22.208     Height: 12m
I: 2018-06-14 15:02:22.209     Location: "NANTES"
I: 2018-06-14 15:02:22.209     Description: "Multi-Mode Repeater"
I: 2018-06-14 15:02:22.210     URL: "arala.44.free.fr"
M: 2018-06-14 15:02:22.210 DMR, Opening DMR Network
I: 2018-06-14 15:02:22.210 System Fusion Network Parameters
I: 2018-06-14 15:02:22.210     Local Address: 127.0.0.1
I: 2018-06-14 15:02:22.210     Local Port: 3200
I: 2018-06-14 15:02:22.210     Gateway Address: 127.0.0.1
I: 2018-06-14 15:02:22.211     Gateway Port: 4200
I: 2018-06-14 15:02:22.211     Mode Hang: 3s
M: 2018-06-14 15:02:22.211 Opening YSF network connection
I: 2018-06-14 15:02:22.211 P25 Network Parameters
I: 2018-06-14 15:02:22.211     Gateway Address: 127.0.0.1
I: 2018-06-14 15:02:22.212     Gateway Port: 42020
I: 2018-06-14 15:02:22.212     Local Port: 32010
I: 2018-06-14 15:02:22.212     Mode Hang: 3s
M: 2018-06-14 15:02:22.213 Opening P25 network connection
I: 2018-06-14 15:02:22.213 CW Id Parameters
I: 2018-06-14 15:02:22.213     Time: 30 mins
I: 2018-06-14 15:02:22.213     Callsign: F5ZJH
I: 2018-06-14 15:02:22.213 RSSI
I: 2018-06-14 15:02:22.214     Mapping File: RSSI.dat
I: 2018-06-14 15:02:22.214 Loaded 0 RSSI data mapping points from RSSI.dat
I: 2018-06-14 15:02:22.214 DMR Id Lookups
I: 2018-06-14 15:02:22.215     File: DMRIds.dat
I: 2018-06-14 15:02:22.215     Reload: 24 hours
I: 2018-06-14 15:02:22.719 Loaded 89798 Ids to the DMR callsign lookup table
I: 2018-06-14 15:02:22.719 D-Star RF Parameters
I: 2018-06-14 15:02:22.719     Module: B
I: 2018-06-14 15:02:22.720     Self Only: no
I: 2018-06-14 15:02:22.720     Ack Reply: yes
I: 2018-06-14 15:02:22.720     Ack Time: 750ms
I: 2018-06-14 15:02:22.720     Error Reply: yes
I: 2018-06-14 15:02:22.720     Remote Gateway: no
I: 2018-06-14 15:02:22.720     Mode Hang: 10s
I: 2018-06-14 15:02:22.720 DMR RF Parameters
I: 2018-06-14 15:02:22.720     Id: 208501
I: 2018-06-14 15:02:22.720     Color Code: 1
I: 2018-06-14 15:02:22.721     Self Only: no
I: 2018-06-14 15:02:22.721     Embedded LC Only: no
I: 2018-06-14 15:02:22.721     Dump Talker Alias Data: yes
I: 2018-06-14 15:02:22.721     Prefixes: 0
I: 2018-06-14 15:02:22.721     Call Hang: 3s
I: 2018-06-14 15:02:22.721     TX Hang: 3s
I: 2018-06-14 15:02:22.721     Mode Hang: 10s
I: 2018-06-14 15:02:22.721 Started the DMR Id lookup reload thread
I: 2018-06-14 15:02:22.721 YSF RF Parameters
I: 2018-06-14 15:02:22.724     Low Deviation: no
I: 2018-06-14 15:02:22.724     Remote Gateway: no
I: 2018-06-14 15:02:22.724     TX Hang: 4s
I: 2018-06-14 15:02:22.724     Self Only: no
I: 2018-06-14 15:02:22.724     DSQ: no
I: 2018-06-14 15:02:22.725     Mode Hang: 10s
I: 2018-06-14 15:02:22.725 P25 RF Parameters
I: 2018-06-14 15:02:22.725     Id: 208501
I: 2018-06-14 15:02:22.725     NAC: $293
I: 2018-06-14 15:02:22.725     UID Override: no
I: 2018-06-14 15:02:22.725     Self Only: no
I: 2018-06-14 15:02:22.725     Remote Gateway: no
I: 2018-06-14 15:02:22.725     Mode Hang: 10s
I: 2018-06-14 15:02:22.726 POCSAG RF Parameters
I: 2018-06-14 15:02:22.726     Frequency: 430425000Hz
I: 2018-06-14 15:02:22.858 Interfaces Info
I: 2018-06-14 15:02:22.859     IPv4: lo:127.0.0.1
I: 2018-06-14 15:02:22.859     IPv4: eth0:192.168.1.6
I: 2018-06-14 15:02:22.859     IPv4: tun0:10.47.162.50
I: 2018-06-14 15:02:22.859     Default interface is : eth0
I: 2018-06-14 15:02:22.859     IP to show: eth0:192.168.1.6
M: 2018-06-14 15:02:22.860 MMDVMHost-20180517 is running
MMDVMHost: POCSAGControl.cpp:101: bool CPOCSAGControl::processData(): Assertion `m_network != __null' failed.
pi@f5zjh:~/Applications/MMDVMHost $

**Comment by g0wfv** [comment]
Can you post up your your MMDVM.ini - my first hunch is there may be an error in that.

**Comment by f5bcb** [comment]
Here is my MMDVM.ini for Pocsag

[General]
Callsign=F5ZJH
Id=208501
Timeout=180
Duplex=1
#ModeHang=10
RFModeHang=10
NetModeHang=3
#Display=HD44780
Display=OLED
Daemon=0
#
[Info]
RXFrequency=439825000
TXFrequency=430425000
Power=46
Latitude=47.25278
Longitude=-1.57444
Height=12
Location=NANTES
Description=Multi-Mode Repeater
URL=arala.44.free.fr

[Log]
# Logging levels, 0=No logging
DisplayLevel=2
FileLevel=2
FilePath=/home/pi/Applications/MMDVMHost
FileRoot=MMDVM

[CW Id]
Enable=1
Time=30
Callsign=F5ZJH

[DMR Id Lookup]
File=DMRIds.dat
Time=24

[NXDN Id Lookup]
File=NXDN.csv
Time=24

[Modem]
Port=/dev/ttyACM0
# Port=\\.\COM3
TXInvert=0
RXInvert=1
PTTInvert=0
TXDelay=100
RXOffset=0
TXOffset=0
DMRDelay=0
RXLevel=100
TXLevel=50
RXDCOffset=0
TXDCOffset=0
RFLevel=100
CWIdTXLevel=50
D-StarTXLevel=50
DMRTXLevel=51
YSFTXLevel=50
P25TXLevel=50
#NXDNTXLevel=50
POCSAGTXLevel=50
RSSIMappingFile=RSSI.dat
Trace=0
# afficher slot/pos/centre/threshold value for RX calibration 
Debug=0

[Transparent Data]
Enable=0
RemoteAddress=127.0.0.1
RemotePort=40094
LocalPort=40095

[UMP]
Enable=0
#Port=\\.\COM4
Port=/dev/ttyACM1


[D-Star]
Enable=1
Module=B
SelfOnly=0
AckReply=1
AckTime=750
ErrorReply=1
RemoteGateway=0
#ModeHang=3

[DMR]
Enable=1
# DMR Roaming beacon delay in minutes
Beacons=0
BeaconInterval=60
BeaconDuration=3
ColorCode=1
SelfOnly=0
EmbeddedLCOnly=0
DumpTAData=1
# Prefixes=234,235
# Slot1TGWhiteList=
# Slot2TGWhiteList=
CallHang=10
TXHang=10
#ModeHang=10



[System Fusion]
Enable=1
LowDeviation=0
SelfOnly=0
TXHang=4
#DGID=1
RemoteGateway=0
#ModeHang=3

[P25]
Enable=1
NAC=293
SelfOnly=0
OverrideUIDCheck=0
RemoteGateway=0
#ModeHang=3

[NXDN]
Enable=0
RAN=1
SelfOnly=0
RemoteGateway=0
# ModeHang=10

[POCSAG]
Enable=1
Frequency=430425000

[D-Star Network]
Enable=1
GatewayAddress=127.0.0.1
#GatewayAddress=51.255.35.215
GatewayPort=20010
LocalPort=20011
#ModeHang=3
Debug=0


[DMR Network]
Enable=1
#BM2281
#Address=164.132.195.103
#Port=55555
Address=127.0.0.1
Port=62031
Jitter=380
Local=62032
Password=passw0rd
# Options=
Slot1=1
Slot2=1
#ModeHang=10
Debug=0


[System Fusion Network]
Enable=1
LocalAddress=127.0.0.1
LocalPort=3200
GatewayAddress=127.0.0.1
GatewayPort=4200
#ModeHang=3
Debug=0


[P25 Network]
Enable=1
GatewayAddress=127.0.0.1
GatewayPort=42020
LocalPort=32010
#ModeHang=3
Debug=0

[NXDN Network]
Enable=0
LocalAddress=127.0.0.1
LocalPort=14021
GatewayAddress=127.0.0.1
GatewayPort=14020
# ModeHang=3
Debug=0

[POCSAG Network]
Enale=1
LocalAddress=127.0.0.1
LocalPort=3800
GatewayAddress=127.0.0.1
GatewayPort=4800
#ModeHang=3
Debug=0


[TFT Serial]
# Port=modem
Port=/dev/ttyAMA0
Brightness=50

[HD44780]
Rows=4
Columns=20

# For basic HD44780 displays (4 bits connection)
# rs, strb, d0, d1, d2, d3
# Pins=11,10,0,1,2,3
Pins=4,6,11,12,13,14

# Device address for I2C
#I2CAddress=0x3F
I2CAddress=0x78

# PWM backlight
PWM=0
PWMPin=21
PWMBright=100
PWMDim=16

DisplayClock=1
UTC=0

[Nextion]
# Port=modem
Port=/dev/ttyAMA0
Brightness=50
DisplayClock=1
UTC=0
#Screen Layout: 0=G4KLX 2=ON7LDS
ScreenLayout=2
IdleBrightness=20

[OLED]
# Type:voir ArduiPi_OLED_lib.h
Type=6
Brightness=0
Invert=0
Scroll=1

[LCDproc]
Address=localhost
Port=13666
#LocalPort=13667
DimOnIdle=0
DisplayClock=1
UTC=0

**Comment by g0wfv** [comment]
[POCSAG Network]
Enale=1 <------- there's your problem - change this to "Enable=1"

**Comment by f5bcb** [comment]
Thanks a lot Tony.  What a stupid mistake !
Host start is OK now but I,m experiencing some errors in pocsag (NAK from the MMDVM)
I checked for the MMDVM is up to date.

Here the host trace : 
I: 2018-06-14 19:13:13.769     Remote Gateway: no
I: 2018-06-14 19:13:13.769     Mode Hang: 10s
I: 2018-06-14 19:13:13.770 POCSAG RF Parameters
I: 2018-06-14 19:13:13.770     Frequency: 430425000Hz
I: 2018-06-14 19:13:13.905 Interfaces Info
I: 2018-06-14 19:13:13.906     IPv4: lo:127.0.0.1
I: 2018-06-14 19:13:13.906     IPv4: eth0:192.168.1.6
I: 2018-06-14 19:13:13.906     IPv4: tun0:10.47.162.50
I: 2018-06-14 19:13:13.906     Default interface is : eth0
I: 2018-06-14 19:13:13.906     IP to show: eth0:192.168.1.6
M: 2018-06-14 19:13:13.906 MMDVMHost-20180517 is running
M: 2018-06-14 19:13:23.793 DMR, Logged into the master successfully
M: 2018-06-14 19:14:00.344 POCSAG, transmitted 1 frame(s) of data from 1 message(s)
W: 2018-06-14 19:14:00.355 Received a NAK from the MMDVM, command = 0x03, reason = 4
W: 2018-06-14 19:14:00.365 Received a NAK from the MMDVM, command = 0x50, reason = 1
M: 2018-06-14 19:14:00.788 POCSAG, transmitted 1 frame(s) of data from 1 message(s)
W: 2018-06-14 19:14:00.805 Received a NAK from the MMDVM, command = 0x50, reason = 1
M: 2018-06-14 19:14:18.353 POCSAG, transmitted 1 frame(s) of data from 1 message(s)
W: 2018-06-14 19:14:18.370 Received a NAK from the MMDVM, command = 0x03, reason = 4
W: 2018-06-14 19:14:18.370 Received a NAK from the MMDVM, command = 0x50, reason = 1
M: 2018-06-14 19:14:18.828 POCSAG, transmitted 1 frame(s) of data from 1 message(s)
W: 2018-06-14 19:14:18.844 Received a NAK from the MMDVM, command = 0x50, reason = 1
M: 2018-06-14 19:15:00.473 POCSAG, transmitted 1 frame(s) of data from 1 message(s)
W: 2018-06-14 19:15:00.485 Received a NAK from the MMDVM, command = 0x03, reason = 4
W: 2018-06-14 19:15:00.491 Received a NAK from the MMDVM, command = 0x50, reason = 1

**Comment by g0wfv** [comment]
I: 2018-06-14 15:02:21.802 MMDVM protocol version: 1, description: MMDVM 20180327 (D-Star/DMR/System Fusion/P25/NXDN) 12.0000MHz (Build: 16:51:26 Jun 10 2018)

Looks like you're possibly still on the master branch on github - you need to recompile with the pocsag branch code.

**Comment by f5bcb** [comment]
I get the zip files of pocsag branch of MMDVM but the result is:
"Unable to read the firmware version after six attempts"

**Comment by phl0** [comment]
Are you sure that you took the firmware from the pocsag branch? 
What hardware are you using?

**Comment by f5bcb** [comment]
Here is the sum of the zip file:
pi@f5zjh:~ $ openssl dgst -md5 MMDVM-pocsag.zip
MD5(MMDVM-pocsag.zip)= 1b3fc66b569f29d25ad9d93b00a2af02
pi@f5zjh:~ $

The hardware is a raspberry Pi + DUE and NTH filter.
This hardware works fine with the master branch of MMDVM

**Comment by phl0** [comment]
Ok, maybe it does not work on an Arduino Due. The code is early beta state. I will investigate.

**Comment by f5bcb** [comment]
Ok I'll wait for some news
Thanks a lot
Jeff

**Comment by g4klx** [comment]
It should work on a Due. Not tested but POCSAG doesn’t add much extra processing requirements to the system.


Sent from Yahoo Mail for iPhone


On Friday, June 15, 2018, 08:06, Florian (DF2ET) <notifications@github.com> wrote:


Ok, maybe it does not work on an Arduino Due. The code is early beta state. I will investigate.

**Comment by gmagill** [comment]
Perhaps the wording of the README.md could be enhanced to state that a Pi Hat is required for POCSAG to work? At the moment, the sentence implies that DVMEGA is supported.

"..the program that interfaces to the MMDVM or DVMega ..."

**Comment by g4klx** [comment]
The software does work on the Due. However there have been quite a few changes to the host and firmware over the last few days, so please update.

gmagill: please don't use someone elses bug report for an unrelated issue. I have re-read the README.md and it appears obvious to me that the DV-Mega is only mentioned as supporting D-Star, DMR and System Fusion.

**Comment by f5bcb** [comment]
Hi all,
I'm just testing the last release of both Host and Modem ad they seem to work on a DUE/NTH filter
No crash encountered.
Pocsag messages well sent over the air.

Thanks to DEV team and contributors.
73
Jeff, F5BCB
