### ISSUE TITLE
Inconsistency of m_jitterSlots=6 and 

### ISSUE THREAD

**Issue by shawnchain** [g4klx/MMDVMHost#433]
https://github.com/g4klx/MMDVMHost/blob/34ceb912c96a4817dd22d3c8b1913f843ffa2dec/DMRSlot.cpp#L50

m_jitterSlots=6 (by default) which means jitter = 360, but currenty jitter=300(by default).

**Comment by juribeparada** [comment]
Default is 360 (see MMDVM.ini, this is the official configuration). I can't find 300, but anyway, if the user supply an incorrect value, the software will correct.

**Comment by shawnchain** [comment]
https://github.com/g4klx/MMDVMHost/blob/34ceb912c96a4817dd22d3c8b1913f843ffa2dec/Conf.cpp#L174

**Comment by juribeparada** [comment]
OK, thanks, I will change. But anyway this value is overwrite for a correct one at startup.

**Comment by shawnchain** [comment]
Sure. 
I'm running the BR5AL with old source code of MMDVMHost and outdated MMDVM.ini which has no Jitter setting entry. After upgraded to the latest source, the default values in constructor will be applied.
Any way this is what I found while reading the source ;)

**Comment by juribeparada** [comment]
It should be fixed now
