### ISSUE TITLE
Lots of "No reply from the modem for some time, resetting it" error message in the log

### ISSUE THREAD

**Issue by shawnchain** [g4klx/MMDVMHost#434]
I saw lots of "No reply from the modem for some time, resetting it" error messages in my repeater log.
By observation, I found that everytime a RF TX repeated, the inactivity timer inside Modem.cpp will be expired finally then we saw the error message.

Is this a by-design behavior or bug ?

**Comment by juribeparada** [comment]
I don't see that problem with my setup, what board are you using?, which firmware and what modes do you have enabled?

**Comment by shawnchain** [comment]
I'm using arduino due + NTH board with firmware version @78a51d4 and host version before NXDN is applied.
The host machine is an OpenWrt box with MT7620 with 128M memory and 32M flash.
Now I'm trying to reproduce the problem and will update the thread here if any found.

**Comment by shawnchain** [comment]
D: 2018-07-03 18:59:28.550 DMR, Sending authorisation
D: 2018-07-03 18:59:28.628 DMR, Sending configuration
M: 2018-07-03 18:59:28.711 DMR, Logged into the master successfully
E: 2018-07-03 19:00:06.914 No reply from the modem for some time, resetting it
M: 2018-07-03 19:00:06.915 Closing the MMDVM
M: 2018-07-03 19:00:08.933 Opening the MMDVM
D: 2018-07-03 19:00:08.935 Reading modem version
I: 2018-07-03 19:00:10.945 MMDVM protocol version: 1, description: MMDVM 20180327 (D-Star/DMR/System Fusion/P25/NXDN) 12.0000 MHz (Build: 14:43:03 Jul  3 2018)
D: 2018-07-03 19:00:10.946 Set modem frequency
D: 2018-07-03 19:00:10.956 Reading modem config
D: 2018-07-03 19:03:03.481 sending CW ID
E: 2018-07-03 19:10:06.908 No reply from the modem for some time, resetting it
M: 2018-07-03 19:10:06.909 Closing the MMDVM
M: 2018-07-03 19:10:08.928 Opening the MMDVM
D: 2018-07-03 19:10:08.930 Reading modem version
I: 2018-07-03 19:10:10.943 MMDVM protocol version: 1, description: MMDVM 20180327 (D-Star/DMR/System Fusion/P25/NXDN) 12.0000 MHz (Build: 14:43:03 Jul  3 2018)
D: 2018-07-03 19:10:10.944 Set modem frequency
D: 2018-07-03 19:10:10.954 Reading modem config
D: 2018-07-03 19:18:03.604 sending CW ID
E: 2018-07-03 19:20:06.868 No reply from the modem for some time, resetting it
M: 2018-07-03 19:20:06.868 Closing the MMDVM
M: 2018-07-03 19:20:06.930 Opening the MMDVM
D: 2018-07-03 19:20:06.931 Reading modem version
I: 2018-07-03 19:20:08.943 MMDVM protocol version: 1, description: MMDVM 20180327 (D-Star/DMR/System Fusion/P25/NXDN) 12.0000 MHz (Build: 14:43:03 Jul  3 2018)
D: 2018-07-03 19:20:08.944 Set modem frequency
D: 2018-07-03 19:20:08.954 Reading modem config

**Comment by juribeparada** [comment]
OK, are you porting MMDVMHost to OpenWrt?. It looks like some operations are slow than normal. You can try to adjust the timer and suggest some new values.

**Comment by shawnchain** [comment]
Will increase the timeout from 2 to 5 and see if the issue gone. 
Base on my test, the MT7620 is fast enough to handle the I/O loop, and  the main loop of MMDVMHost only elapses about 2ms.

**Comment by shawnchain** [comment]
D: 2018-07-04 00:03:57.807 <got STATUS RESPONSE from modem
D: 2018-07-04 00:03:59.772 main loop elapsed 5 ms
D: 2018-07-04 00:04:00.778 got ACK from modem
D: 2018-07-04 00:04:02.338 main loop elapsed 0 ms
D: 2018-07-04 00:04:03.082 >request STATUS from modem
D: 2018-07-04 00:04:03.088 <got STATUS RESPONSE from modem
D: 2018-07-04 00:04:03.775 got ACK from modem
D: 2018-07-04 00:04:04.776 got ACK from modem
D: 2018-07-04 00:04:04.910 main loop elapsed 5 ms
D: 2018-07-04 00:04:07.480 main loop elapsed 0 ms
D: 2018-07-04 00:04:08.368 >request STATUS from modem
D: 2018-07-04 00:04:08.374 <got STATUS RESPONSE from modem
D: 2018-07-04 00:04:10.052 main loop elapsed 5 ms
D: 2018-07-04 00:04:12.620 main loop elapsed 0 ms
D: 2018-07-04 00:04:13.651 >request STATUS from modem
D: 2018-07-04 00:04:13.657 <got STATUS RESPONSE from modem

The problem occurs more frequently when local RF and NET traffic goes in.

**Comment by shawnchain** [comment]
I modified the Modem.cpp to store the timestamp of each STATUS request/respones and dump it when error occurs. Here is the log.  
BTW seems duplication of #51 #77 

M: 2018-07-04 11:04:12.406 DMR, Logged into the master successfully
E: 2018-07-04 11:49:57.903 No reply from the modem for some time (3s), resetting it
E: 2018-07-04 11:49:57.904 >Latest STATUS Request Sent time: 2018-07-04 11:49:57.903 
E: 2018-07-04 11:49:57.904 >Latest STATUS Response Received time: 2018-07-04 11:49:58.114 
M: 2018-07-04 11:49:57.904 Closing the MMDVM
M: 2018-07-04 11:49:59.923 Opening the MMDVM
I: 2018-07-04 11:50:01.934 MMDVM protocol version: 1, description: MMDVM 20180107 TCXO (D-Star/DMR/System Fusion/P25/RSSI/CW Id) (Build: 00:55:25 Jun 23 2018)
E: 2018-07-04 12:19:57.989 No reply from the modem for some time (3s), resetting it
E: 2018-07-04 12:19:57.989 >Latest STATUS Request Sent time: 2018-07-04 12:19:57.989 
E: 2018-07-04 12:19:57.990 >Latest STATUS Response Received time: 2018-07-04 12:19:58.147 
M: 2018-07-04 12:19:57.990 Closing the MMDVM
M: 2018-07-04 12:20:00.008 Opening the MMDVM
I: 2018-07-04 12:20:02.022 MMDVM protocol version: 1, description: MMDVM 20180107 TCXO (D-Star/DMR/System Fusion/P25/RSSI/CW Id) (Build: 00:55:25 Jun 23 2018)
E: 2018-07-04 12:29:58.022 No reply from the modem for some time (3s), resetting it
E: 2018-07-04 12:29:58.023 >Latest STATUS Request Sent time: 2018-07-04 12:29:58.022 
E: 2018-07-04 12:29:58.023 >Latest STATUS Response Received time: 2018-07-04 12:29:58.035 
M: 2018-07-04 12:29:58.023 Closing the MMDVM
M: 2018-07-04 12:30:00.042 Opening the MMDVM
I: 2018-07-04 12:30:02.053 MMDVM protocol version: 1, description: MMDVM 20180107 TCXO (D-Star/DMR/System Fusion/P25/RSSI/CW Id) (Build: 00:55:25 Jun 23 2018)
E: 2018-07-04 12:59:58.070 No reply from the modem for some time (3s), resetting it
E: 2018-07-04 12:59:58.070 >Latest STATUS Request Sent time: 2018-07-04 12:59:58.070 
E: 2018-07-04 12:59:58.071 >Latest STATUS Response Received time: 2018-07-04 12:59:58.145 
M: 2018-07-04 12:59:58.071 Closing the MMDVM
M: 2018-07-04 13:00:00.090 Opening the MMDVM
I: 2018-07-04 13:00:02.101 MMDVM protocol version: 1, description: MMDVM 20180107 TCXO (D-Star/DMR/System Fusion/P25/RSSI/CW Id) (Build: 00:55:25 Jun 23 2018)
E: 2018-07-04 13:09:58.098 No reply from the modem for some time (3s), resetting it
E: 2018-07-04 13:09:58.098 >Latest STATUS Request Sent time: 2018-07-04 13:09:58.098 
E: 2018-07-04 13:09:58.099 >Latest STATUS Response Received time: 2018-07-04 13:09:58.116 
M: 2018-07-04 13:09:58.099 Closing the MMDVM
M: 2018-07-04 13:10:00.117 Opening the MMDVM
I: 2018-07-04 13:10:02.131 MMDVM protocol version: 1, description: MMDVM 20180107 TCXO (D-Star/DMR/System Fusion/P25/RSSI/CW Id) (Build: 00:55:25 Jun 23 2018)
E: 2018-07-04 13:19:58.122 No reply from the modem for some time (3s), resetting it
E: 2018-07-04 13:19:58.122 >Latest STATUS Request Sent time: 2018-07-04 13:19:58.122 
E: 2018-07-04 13:19:58.123 >Latest STATUS Response Received time: 2018-07-04 13:19:58.198 
M: 2018-07-04 13:19:58.123 Closing the MMDVM
M: 2018-07-04 13:20:00.142 Opening the MMDVM
I: 2018-07-04 13:20:02.156 MMDVM protocol version: 1, description: MMDVM 20180107 TCXO (D-Star/DMR/System Fusion/P25/RSSI/CW Id) (Build: 00:55:25 Jun 23 2018)

**Comment by shawnchain** [comment]
```
void CModem::clock(unsigned int ms)
{
	// Poll the modem status every 250ms
	m_statusTimer.clock(ms);
	if (m_statusTimer.hasExpired()) {
		readStatus();
		m_statusTimer.start();
		::gettimeofday(&_reqTime, NULL);
	}

	m_inactivityTimer.clock(ms);
	if (m_inactivityTimer.hasExpired()) {
		LogError("No reply from the modem for some time (%ds), resetting it",m_inactivityTimer.getTimeout());
		// Dump the request/response timestamp
		char buffer[300U];
		struct tm* tm;
		tm = ::localtime(&_reqTime.tv_sec);
		::sprintf(buffer, "%04d-%02d-%02d %02d:%02d:%02d.%03lu ", tm->tm_year + 1900, tm->tm_mon + 1, tm->tm_mday, tm->tm_hour, tm->tm_min, tm->tm_sec, _reqTime.tv_usec / 1000U);
		LogError(">Latest STATUS Request Sent time: %s",buffer);
		tm = ::localtime(&_respTime.tv_sec);
		::sprintf(buffer, "%04d-%02d-%02d %02d:%02d:%02d.%03lu ", tm->tm_year + 1900, tm->tm_mon + 1, tm->tm_mday, tm->tm_hour, tm->tm_min, tm->tm_sec, _respTime.tv_usec / 1000U);
		LogError(">Latest STATUS Response Received time: %s",buffer);

		m_error = true;
		close();

		CThread::sleep(2000U);		// 2s
		while (!open())
			CThread::sleep(5000U);	// 5s
	}

	RESP_TYPE_MMDVM type = getResponse();
```

I'm suspecting if the `m_inactivityTimer.clock(ms);` has wrong count inside. Based on my test the value of ms is like 0,5,0,6,0,5,0,5 which is determined by a `CThread:sleep(5)` in MMDVMHost giant loop

@juribeparada

**Comment by shawnchain** [comment]
CStopWatch uses gettimeofday() to measure time which may returns negative time if the wall time is changed/fixed by NTP or date command.
Unfortunately, unsigned int is used in the code the negative value will become a huge number then the timer gets expired.
Reference: https://blog.habets.se/2010/09/gettimeofday-should-never-be-used-to-measure-time.html
