### ISSUE TITLE
Warning with my dvmega version

### ISSUE THREAD

**Issue by ea8ii** [g4klx/MMDVMHost#437]
Today I have updated and I get this warning message every second:
“The length of the get status from the modem is too short. Maybe the Firmware is out of date?”
I have dvmega v3.17

**Comment by EA5SW** [comment]
Also people with Jumbospots Hats with MMDVM 1.3.7

**Comment by g4klx** [comment]
Sorry about that. It should be fixed in GitHub now. Please note that JumboSpots are not supported.

**Comment by kb8fk** [comment]
It's working now. Thanks for all your great work!
73,
Scott
KB8FK
