### ISSUE TITLE
Why not unify the DMRIds.dat /Call DB files to CSV format and simplify the code.

### ISSUE THREAD

**Issue by shawnchain** [g4klx/MMDVMHost#438]
https://github.com/g4klx/MMDVMHost/blob/3d1423f8193e306a5882ce2ab5d625e4676296c2/DMRLookup.cpp#L151

**Comment by g4klx** [comment]
The format chosen is the raw data format that is downloaded so that no additional external processing is needed.

**Comment by shawnchain** [comment]
don't think so, if we check the download script, there're awk convert logic.

**Comment by g4klx** [comment]
Any pull request must update the host as well as the script used to download the data. It needs to be a complete package.

**Comment by shawnchain** [comment]
I'm talking about the file format of DMRIds.dat, which is read and parsed by DMRLookup.cpp.

There is only one line to convert to CSV format:
`sed -e "s/\x09\x09/,/g" DMRIds.dat | sed -e "s/ /,/" >DMRIds.csv`

**Comment by g0wfv** [comment]
IIRC the original script I wrote converted the CSV formatted data to that which the host wanted.

If this is implemented the script would effectively not be needed (just a simple pipeline in cron could replace it) or it could be drastically simplified if you want to keep backups ......

**Comment by shawnchain** [comment]
FYI
https://github.com/shawnchain/MMDVMHost/commit/5da0f7aa81881cc4ec1646a0c1d89480a198601d
