### ISSUE TITLE
CW Ident (optionally) on POCSAG frequency

### ISSUE THREAD

**Issue by jruys** [g4klx/MMDVMHost#439]
When main MMDVM frequency and POCSAG frequency are different, CW ident is only sent on the main frequency. There may be a need to also identify on the POCSAG frequency. 

Add an .ini "CWId=1" option to the [POCSAG] section which only kicks in when "Frequency" != "TXFrequency"?

**Comment by phl0** [comment]
DAPNET has an implementation that sends out a transmitter identification on a regular basis in POCSAG. Transmissions are addressed to RIC. So you could subscribe to RIC 8 and see what transmitter you are receiving. An additional CW identification is not necessary I think.

**Comment by jruys** [comment]
In some countries (don't have the Dutch link handy) there's a limited number of modes you need to use to identify yourself, typically voice and CW. Don't think my local regulator will go through the trouble to decode the POCSAG signal to find out who is causing interference. That's why I would want to add a CW ident, so I can be easily traced.

In my local case I simply only enabled POCSAG and set all frequencies to the same value, so I do get CW ident on POCSAG.
