### ISSUE TITLE
Missing POCSAG Start Tone

### ISSUE THREAD

**Issue by robrobinette** [g4klx/MMDVMHost#441]
Another user and I, both using dual_hs_hat boards using 1.4.3 and Pi-Star 3.4.16 are seeing this behavior. It seems about 1 in 30 POCSAG transmissions are transmitted without the start tone. When this happens our SDR + PDW software will not decode the POCSAG page. The other guy even turned off all other modes and still had the problem. I monitor the hotspot's transmissions using a handi-talkie so I can hear the POCSAG tones.

**Comment by robrobinette** [comment]
Another user has reported the same issue using a standard simplex ZUMspot with 1.4.3 and 3.4.16.

**Comment by g4klx** [comment]
Firstly you are talking about a hotspot and that code is provided by Andy CA6JAU, and the start tone is created at the modem end and not the host end. Can you raise the issue on his GitHub please. https://github.com/juribeparada/MMDVM_HS I will be watching with interest though.

**Comment by robrobinette** [comment]
Thanks g4klx, I opened a new issue with them.

Rob K9OJ
