### ISSUE TITLE
Nextion: Assertion `m_fd != -1' failed.

### ISSUE THREAD

**Issue by marrold** [g4klx/MMDVMHost#452]
Hi,

I've noticed that when using a Nextion display with `Port=modem`, when MMDVMHost exits it throughs an error, and the Nextion display continues to show "MMDVM IDLE"

Heres the error:
`MMDVMHost: SerialController.cpp:489: virtual int CSerialController::write(const unsigned char*, unsigned int): Assertion 'm_fd != -1' failed`

When I plug the display into a separate USB UART adapter (`Port=/dev/ttyUSB0`) and exit MMDVMHost, the display shows "MMDVM Stopped" and I don't see such error in the logs.

Tested on `c9505b8` and `71a6f93`

Thanks again

**Comment by on7lds** [comment]
MMDVMHost can only send the "MMDVM Stopped" if is is running and doing a clean exit.
When it exits on error, then whatever is on the display, stays on the display (this is how the Nextion displays work)

**Comment by marrold** [comment]
The error only occurs when using `Port=modem`,  now when it's `Port=/dev/ttyUSB0` for example.

Anyway, looks like you've pushed a fix in #455

Thanks!
