### ISSUE TITLE
many problems

### ISSUE THREAD

**Issue by M6YRU** [g4klx/MMDVMHost#458]
right, lets start here, i havent used my MMDVM for a while (maybe a year) when i turned it on it didnt connect to anything...
i clicked in the MMDVM section to update ID's and other stuf etc and yes it downloaded a load of stuff...
still didnt connect, it said cannot load the lookup file, then closed and reopen looping..

i updated the rest of the software and now it dont boot!

it seems like the past 3 times i powered it on i cant ever get it to "just work" and its being a pain to get it going, ...

the sd card still reads in my laptop but i dont know why its not booting as i dont have a monitor for it and cant SSH/vnc into it

any ideas? do i need to re-flash my sd card? is there a way i can back up files that i had made in raspbian?

**Comment by M6YRU** [comment]
> Don't use raspberry pi ,or just bear with it.
> If you still want to stick to raspberry pi, I suggest you to prepare more tf cards or more pi boards for hardware failure backup.
> It has nothing to do with mmdvmhost

Hi thanks for your reply, my gripe was that if MMDVMHost "just worked for me" when i turned it on then i wouldnt have messed with it and done all the updates and stuff (it was only after i did updates when the Pi crashed and stopped working)
after i last used it i shut it down and not used it for like 8-12 months... i could understand if ip/usernames had changed but there was no documentation of brandmeister IP being changed from the one i was using at the time...
again the time before that (not used for 3-4 months) didnt work and needed updating but the ip was the same....
time before that the password was changed from passw0rd to passw1rd, so i changed it and it said the same about "cannot load the lookup file" and cllose and open looping... alas, it needed updating.
time before that it didnt work and someone kindly remote in to fix this for me....
is this is normal or is there something wrong???? it really takes too long to do what i want and that is turn on system and turn on radio when i want it...

sooo, my next question is too (as many people use raspbian on here who have more experiance than me) is there a way i can load the drive to get a backup of files and scripts i made?

**Comment by rogerclarkmelbourne** [comment]
> sooo, my next question is too (as many people use raspbian on here who have more experiance than me) is there a way i can load the drive to get a backup of files and scripts i made?

Mount a USB memory stick and copy them onto that.
(Use tar etc if you want a single archive file , including compression)

Just google how to do this.

I'd suggest that Jonathan close this issue as irrelevant, because like @shawnchain has said, this is not a MMDVMHost issue, its the lack of reliability of the RPi
