### ISSUE TITLE
MMDVMHost will not resync after transmission is lost for brief periods

### ISSUE THREAD

**Issue by yo6nam** [g4klx/MMDVMHost#463]
Hello guys,

A few days ago I was able to test and replicate the following issue. If a mobile or portable station starts a qso on a repeater running the latest version of MMDVMHost, everything is fine until the signal of the station drops/fades for a brief period. Once the transmission is lost it will not resync/recover. Here is a snip from the log :

> A -- DMR Slot 2, audio sequence no. 3, errs: 1/141 (0.7%)
A -- DMR Slot 2, audio sequence no. 4, errs: 0/141 (0.0%)
A -- DMR Slot 2, audio sequence no. 5, errs: 0/141 (0.0%)
A -- Debug: DMRDMORX: voice sync found pos/centre/threshold 761 246 574
A -- DMR Slot 2, raw RSSI: 2321, reported RSSI: -49 dBm
A -- DMR Slot 2, audio sequence no. 0, errs: 1/141 (0.7%)
A -- DMR Slot 2, audio sequence no. 1, errs: 1/141 (0.7%)
B -- DMR Slot 2, audio sequence no. 2, errs: 18/141 (12.8%)
B -- DMR Slot 2, audio sequence no. 3, errs: 17/141 (12.1%)
B -- DMR Slot 2, audio sequence no. 4, errs: 17/141 (12.1%)
B -- DMR Slot 2, audio sequence no. 5, errs: 19/141 (13.5%)
B -- DMR Slot 2, audio sequence no. 0, errs: 19/141 (13.5%)
B -- DMR Slot 2, audio sequence no. 1, errs: 17/141 (12.1%)
B -- DMR Slot 2, audio sequence no. 2, errs: 17/141 (12.1%)
B -- DMR Slot 2, audio sequence no. 3, errs: 17/141 (12.1%)
B -- DMR Slot 2, audio sequence no. 4, errs: 19/141 (13.5%)
B -- DMR Slot 2, audio sequence no. 5, errs: 20/141 (14.2%)
B -- DMR Slot 2, audio sequence no. 0, errs: 20/141 (14.2%)
B -- DMR Slot 2, RF voice transmission lost, 5.1 seconds, BER: 2.2%, RSSI: -49/-49/-49 dBm
C -- Debug: DMRDMORX: voice sync found pos/centre/threshold 761 211 551
C -- DMR Slot 2, raw RSSI: 1836, reported RSSI: -49 dBm
C -- Debug: DMRDMORX: voice sync found pos/centre/threshold 761 169 564
C -- DMR Slot 2, raw RSSI: 2312, reported RSSI: -49 dBm
C -- Debug: DMRDMORX: voice sync found pos/centre/threshold 761 154 565
C -- DMR Slot 2, raw RSSI: 2259, reported RSSI: -49 dBm
C -- Debug: DMRDMORX: voice sync found pos/centre/threshold 761 115 567
C -- DMR Slot 2, raw RSSI: 2323, reported RSSI: -49 dBm
C -- Debug: DMRDMORX: voice sync found pos/centre/threshold 761 116 567
C -- DMR Slot 2, raw RSSI: 2328, reported RSSI: -49 dBm
C -- Debug: DMRDMORX: voice sync found pos/centre/threshold 761 115 567
C -- DMR Slot 2, raw RSSI: 2326, reported RSSI: -49 dBm
C -- Debug: DMRDMORX: voice sync found pos/centre/threshold 761 118 556
C -- DMR Slot 2, raw RSSI: 2336, reported RSSI: -49 dBm
C -- Debug: DMRDMORX: voice sync found pos/centre/threshold 761 147 565
C -- DMR Slot 2, raw RSSI: 2338, reported RSSI: -49 dBm
C -- Debug: DMRDMORX: voice sync found pos/centre/threshold 761 112 575
C -- DMR Slot 2, raw RSSI: 2341, reported RSSI: -49 dBm
C -- Debug: DMRDMORX: voice sync found pos/centre/threshold 761 124 575
C -- DMR Slot 2, raw RSSI: 2343, reported RSSI: -49 dBm
C -- Debug: DMRDMORX: voice sync found pos/centre/threshold 761 181 574
C -- DMR Slot 2, raw RSSI: 2345, reported RSSI: -49 dBm
--- continues forever  --- <

A = normal transmission
B = drop/fade period
C = after the signal returns to normal strength

To overcome the problem I had to downgrade all my repeaters using MMDVMHost to commit a65fba4320a8cccf2e48730bc31af056ee117440
after going back randomly so this is NOT the last version that works correctly just one randomly selected from the older commits. The problem can be seen on Arduino shields or STM based PiHat. MMDVM fimware used for testing is 0ca06e2219f87d76755d6064c2524757d8aa3849

Regards and '73
Razvan / YO6NAM

**Comment by juribeparada** [comment]
Now should be fixed with latest commit

**Comment by yo6nam** [comment]
Thank you, Andy. We're back to normal operation.
