### ISSUE TITLE
QUESTION on RaspberryPi to DVMEGA comms

### ISSUE THREAD

**Issue by devinhedge** [g4klx/MMDVMHost#467]
I've been reading through the code trying to determine how MMDBMHost is communicating with the DVMEGA board. Is this through Serial TTY over GPIO, or Serial USB over GPIO? I'm asking because I saw instructions to disable Serial USB interface and I have other hats using that to talk.

**Comment by phl0** [comment]
It depends on how your DVmega is to connected to the RPi. If it sits on the GPIO header you have to disable the console on the GPIO UART. 
If it is connected via a USB serial adapter it does not matter.

**Comment by devinhedge** [comment]
Thanks for the response. I’m running the dual-band hat on the GPIOs. Disabling the console on the GPIO UART is messing with the GPS dongle attached to a USB port, and messes with the PiJuice UPS hat signaling also attached to the GPIO. I’m thinking I should with the Guus at DVMEGA. Again, thanks!
