### ISSUE TITLE
More of a feature request than issue...

### ISSUE THREAD

**Issue by citynetcomputing** [g4klx/MMDVMHost#474]
Can there be some way to inject a text/sms/tms message into the data stream and sent out the repeater to a radio?

example.. /MMDVMHostSMS -i 3120205 -m "Testing TMS"

so like -i for DMR ID to send to, and say -m for the message to send....

Thanks!!!

**Comment by g4klx** [comment]
No. The reason is that each DMR radio manufacturer has its own SMS standard. There is no standardisation. You'd need to know the format of each and some way to know what type of radio you're addressing. It's not as easy as you might think....

**Comment by citynetcomputing** [comment]
Ok, I see your response and raise you a:What about adding a -p switch then for the protocol. Say,-p MotorolaOr -p HyteraEtc.I agree its definately not easy and the work you guys do really is amazing and to be commended!<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: Jonathan Naylor <notifications@github.com> </div><div>Date: 11/23/18  3:19 AM  (GMT-05:00) </div><div>To: g4klx/MMDVMHost <MMDVMHost@noreply.github.com> </div><div>Cc: Jay <jay@cidcomm.com>, Author <author@noreply.github.com> </div><div>Subject: Re: [g4klx/MMDVMHost] More of a feature request than issue... (#474) </div><div>
</div>No. The reason is that each DMR radio manufacturer has its own SMS standard. There is no standardisation. You'd need to know the format of each and some way to know what type of radio you're addressing. It's not as easy as you might think....

**Comment by citynetcomputing** [comment]
This can be closed. Thanks.

**Comment by tomasbrincil** [comment]
I am interested in this topic too.
However I completely understand the compatibilty issue there could be option to send plain/raw message.

**Comment by citynetcomputing** [comment]
@tomasbrincil

Lookup Arsed on git. Has a great spooling feature to inject SMS messages. You need a control radio but otherwise works great. I'm using one control radio shared between linux and windows for arsed/OTAP. Love it.

73,
