### ISSUE TITLE
Pocsag gw does not transmit on freq. 

### ISSUE THREAD

**Issue by geiraage** [g4klx/MMDVMHost#485]
Hi. 

I have a problem. I have tested the pocsag/dapnet system.  Get this error msg in log

==> /var/log/pi-star/DAPNETGateway-2019-01-02.log <==
D: 2019-01-02 23:59:00.042 Queueing message to 0000208, type 6, func Alphanumeric: "XTIME=0059030119XTIME=0059030119"
D: 2019-01-02 23:59:00.083 Queueing message to 0000224, type 6, func Alphanumeric: "YYYYMMDDHHMMSS190103005900"
M: 2019-01-02 23:59:08.803 Sending message in slot 12 to 0000208, type 6, func Alphanumeric: "XTIME=0059030119XTIME=0059030119"
M: 2019-01-02 23:59:08.813 Sending message in slot 12 to 0000224, type 6, func Alphanumeric: "YYYYMMDDHHMMSS190103005900"

==> /var/log/pi-star/MMDVM-2019-01-02.log <==
M: 2019-01-02 23:59:08.992 POCSAG, transmitted 1 frame(s) of data from 1 message(s)
M: 2019-01-02 23:59:09.189 POCSAG, transmitted 1 frame(s) of data from 1 message(s)
W: 2019-01-02 23:59:09.190 Received a NAK from the MMDVM, command = 0x03, reason = 4

What could be the reason?

I have this configuration 

=> /var/log/pi-star/MMDVM-2019-01-02.log <==
I: 2019-01-02 23:42:05.642 MMDVM protocol version: 1, description: MMDVM_HS_Hat-v1.3.3 20180224 ADF7021 FW by CA6JAU (Build: 09:50:25 Feb 27 2018)
I: 2019-01-02 23:42:05.662 Display Parameters
I: 2019-01-02 23:42:05.662     Type: OLED
I: 2019-01-02 23:42:06.012 POCSAG Network Parameters
I: 2019-01-02 23:42:06.013     Gateway Address: 127.0.0.1
I: 2019-01-02 23:42:06.014     Gateway Port: 4800
I: 2019-01-02 23:42:06.014     Local Address: 127.0.0.1
I: 2019-01-02 23:42:06.015     Local Port: 3800
I: 2019-01-02 23:42:06.015     Mode Hang: 5s
M: 2019-01-02 23:42:06.015 Opening POCSAG network connection
I: 2019-01-02 23:42:06.017 RSSI
I: 2019-01-02 23:42:06.018     Mapping File: /usr/local/etc/RSSI.dat
I: 2019-01-02 23:42:06.019 Loaded 14 RSSI data mapping points from /usr/local/etc/RSSI.dat
I: 2019-01-02 23:42:06.020 POCSAG RF Parameters
I: 2019-01-02 23:42:06.021     Frequency: 432575000Hz
I: 2019-01-02 23:42:06.143 Interfaces Info
I: 2019-01-02 23:42:06.144     IPv4: lo:127.0.0.1
I: 2019-01-02 23:42:06.145     IPv4: wlan0:172.24.1.22
I: 2019-01-02 23:42:06.145     Default interface is : wlan0
I: 2019-01-02 23:42:06.146     IP to show: wlan0:172.24.1.22
M: 2019-01-02 23:42:06.147 MMDVMHost-20181107_Pi-Star is running
M: 2019-01-02 23:42:16.328 Closing the MMDVM
M: 2019-01-02 23:42:16.459 Closing POCSAG network connection
I: 2019-01-02 23:42:16.459 MMDVMHost-20181107_Pi-Star exited on receipt of SIGTERM
I: 2019-01-02 23:42:33.868 This software is for use on amateur radio networks only,
I: 2019-01-02 23:42:33.871 it is to be used for educational purposes only. Its use on
I: 2019-01-02 23:42:33.871 commercial networks is strictly prohibited.
I: 2019-01-02 23:42:33.873 Copyright(C) 2015-2018 by Jonathan Naylor, G4KLX and others
M: 2019-01-02 23:42:33.873 MMDVMHost-20181107_Pi-Star is starting
M: 2019-01-02 23:42:33.873 Built 09:24:10 Nov 12 2018 (GitID #9444eca)
I: 2019-01-02 23:42:33.875 General Parameters
I: 2019-01-02 23:42:33.876     Callsign: LA4ZUA
I: 2019-01-02 23:42:33.877     Id: 2420074
I: 2019-01-02 23:42:33.877     Duplex: no
I: 2019-01-02 23:42:33.878     Timeout: 240s
I: 2019-01-02 23:42:33.880     D-Star: disabled
I: 2019-01-02 23:42:33.881     DMR: disabled
I: 2019-01-02 23:42:33.881     YSF: disabled
I: 2019-01-02 23:42:33.881     P25: disabled
I: 2019-01-02 23:42:33.882     NXDN: disabled
I: 2019-01-02 23:42:33.882     POCSAG: enabled
I: 2019-01-02 23:42:33.882 Modem Parameters
I: 2019-01-02 23:42:33.883     Port: /dev/ttyAMA0
I: 2019-01-02 23:42:33.883     Protocol: uart
I: 2019-01-02 23:42:33.884     RX Invert: no
I: 2019-01-02 23:42:33.884     TX Invert: yes
I: 2019-01-02 23:42:33.884     PTT Invert: no
I: 2019-01-02 23:42:33.885     TX Delay: 100ms
I: 2019-01-02 23:42:33.885     RX Offset: 450Hz
I: 2019-01-02 23:42:33.890     TX Offset: 450Hz
I: 2019-01-02 23:42:33.890     RX DC Offset: 0
I: 2019-01-02 23:42:33.900     TX DC Offset: 0
I: 2019-01-02 23:42:33.900     RF Level: 100.0%
I: 2019-01-02 23:42:33.901     DMR Delay: 0 (0.0ms)
I: 2019-01-02 23:42:33.901     RX Level: 50.0%
I: 2019-01-02 23:42:33.901     CW Id TX Level: 50.0%
I: 2019-01-02 23:42:33.901     D-Star TX Level: 50.0%
I: 2019-01-02 23:42:33.902     DMR TX Level: 50.0%
I: 2019-01-02 23:42:33.902     YSF TX Level: 50.0%
I: 2019-01-02 23:42:33.902     P25 TX Level: 50.0%
I: 2019-01-02 23:42:33.903     NXDN TX Level: 50.0%
I: 2019-01-02 23:42:33.903     POCSAG TX Level: 50.0%
I: 2019-01-02 23:42:33.903     RX Frequency: 432532500Hz (432532950Hz)
I: 2019-01-02 23:42:33.904     TX Frequency: 432532500Hz (432532950Hz)
M: 2019-01-02 23:42:33.904 Opening the MMDVM
I: 2019-01-02 23:42:35.918 MMDVM protocol version: 1, description: MMDVM_HS_Hat-v1.3.3 20180224 ADF7021 FW by CA6JAU (Build: 09:50:25 Feb 27 2018)
I: 2019-01-02 23:42:35.939 Display Parameters
I: 2019-01-02 23:42:35.939     Type: OLED
I: 2019-01-02 23:42:36.309 POCSAG Network Parameters
I: 2019-01-02 23:42:36.309     Gateway Address: 127.0.0.1
I: 2019-01-02 23:42:36.309     Gateway Port: 4800
I: 2019-01-02 23:42:36.309     Local Address: 127.0.0.1
I: 2019-01-02 23:42:36.309     Local Port: 3800
I: 2019-01-02 23:42:36.310     Mode Hang: 5s
M: 2019-01-02 23:42:36.310 Opening POCSAG network connection
I: 2019-01-02 23:42:36.310 RSSI
I: 2019-01-02 23:42:36.310     Mapping File: /usr/local/etc/RSSI.dat
I: 2019-01-02 23:42:36.312 Loaded 14 RSSI data mapping points from /usr/local/etc/RSSI.dat
I: 2019-01-02 23:42:36.313 POCSAG RF Parameters
I: 2019-01-02 23:42:36.313     Frequency: 432575000Hz
I: 2019-01-02 23:42:36.482 Interfaces Info
I: 2019-01-02 23:42:36.483     IPv4: lo:127.0.0.1
I: 2019-01-02 23:42:36.483     IPv4: wlan0:172.24.1.22
I: 2019-01-02 23:42:36.483     Default interface is : wlan0
I: 2019-01-02 23:42:36.483     IP to show: wlan0:172.24.1.22
M: 2019-01-02 23:42:36.483 MMDVMHost-20181107_Pi-Star is running

‹
==> /var/log/pi-star/DAPNETGateway-2019-01-02.log <==
M: 2019-01-02 23:42:37.325 Opening POCSAG network connection
I: 2019-01-02 23:42:37.330 Opening UDP port on 4800
M: 2019-01-02 23:42:37.332 Opening DAPNET connection
M: 2019-01-02 23:42:37.470 Starting DAPNETGateway-20181107_Pi-Star
M: 2019-01-02 23:42:37.475 Logging into DAPNET
M: 2019-01-02 23:42:37.575 Logged into the DAPNET network
M: 2019-01-02 23:42:37.894 Schedule information received: 048C
M: 2019-01-02 23:42:43.202 Loaded new schedule: *---*---*---*---
D: 2019-01-02 23:43:00.049 Queueing message to 0000208, type 6, func Alphanumeric: "XTIME=0043030119XTIME=0043030119"
D: 2019-01-02 23:43:00.091 Queueing message to 0000224, type 6, func Alphanumeric: "YYYYMMDDHHMMSS190103004300"
D: 2019-01-02 23:43:21.609 Rejecting message to 0000208, type 6, func Alphanumeric: "XTIME=0043030119XTIME=0043030119"
M: 2019-01-02 23:43:21.619 Sending message in slot 8 to 0000224, type 6, func Alphanumeric: "YYYYMMDDHHMMSS190103004300"

==> /var/log/pi-star/MMDVM-2019-01-02.log <==
M: 2019-01-02 23:43:21.806 POCSAG, transmitted 1 frame(s) of data from 1 message(s)
W: 2019-01-02 23:43:21.817 Received a NAK from the MMDVM, command = 0x03, reason = 4

==> /var/log/pi-star/DAPNETGateway-2019-01-02.log <==
D: 2019-01-02 23:44:00.040 Queueing message to 0002504, type 5, func Numeric: "234400   020119"
D: 2019-01-02 23:44:00.081 Queueing message to 0000200, type 6, func Alphanumeric: "XTIME=2344020119XTIME=2344020119"
D: 2019-01-02 23:44:00.132 Queueing message to 0000216, type 6, func Alphanumeric: "YYYYMMDDHHMMSS190102234400"
M: 2019-01-02 23:44:12.809 Sending message in slot 0 to 0002504, type 5, func Numeric: "234400   020119"
M: 2019-01-02 23:44:12.819 Sending message in slot 0 to 0000200, type 6, func Alphanumeric: "XTIME=2344020119XTIME=2344020119"
M: 2019-01-02 23:44:12.830 Sending message in slot 0 to 0000216, type 6, func Alphanumeric: "YYYYMMDDHHMMSS190102234400"

**Comment by juribeparada** [comment]
Your firmware for your MMDVM_HS_Hat is too old (v1.3.3) and doesn't support POCSAG. You need to update to latest firmware.
