### ISSUE TITLE
Modem lost connection many times when update Pi-Star to Dashboard_3.4.16_20190114

### ISSUE THREAD

**Issue by bi7jta** [g4klx/MMDVMHost#488]
Hi ,
Just feedback this problem in my hotspot, I change difference Raspberry Pi ,difference HAT(Duplex and Simplex), will happen the same problem. Is the error formate data made the connection down? I notice there is a warning message in log:
"  Unknown message, type: 09
    Buffer dump " 

Detail logs as follow,
de bi7jta,

M: 2019-01-15 06:46:05.686 DMR Slot 2, received network end of voice transmission, 5.4 seconds, 6% packet loss, BER: 0.0%
M: 2019-01-15 06:46:10.032 DMR Slot 2, received RF voice header from BI7JTA to TG 46001
M: 2019-01-15 06:46:35.771 DMR Slot 2, received RF end of voice transmission, 25.3 seconds, BER: 0.3%, RSSI: -47/-47/-47 dBm
M: 2019-01-15 06:46:38.717 DMR Slot 2, received network voice header from 46001 to TG 46001
M: 2019-01-15 06:46:39.345 DMR Talker Alias (Data Format 1, Received 6/10 char): 'BD7NMC'
M: 2019-01-15 06:46:39.345 DMR Slot 2, Embedded Talker Alias Header
M: 2019-01-15 06:46:39.345 0000:  04 00 54 42 44 37 4E 4D 43                         *..TBD7NMC*
01-15 06:46:54.635 0020:  7F 77 FD 75 7A C8 42 14 A8 69 38 C9 E1 D6 83 51    *.w.uz.B..i8....Q*
M: 2019-01-15 06:46:54.635 0030:  A7 7C E0 25 18 C3 0A EA 8A 6A 2C A2 76 E8 F1 08    *.|.%.....j,.v...*
M: 2019-01-15 06:46:54.635 0040:  E7 91 C4 CD 5D 7F 77 FD 75 7A C8 42 14 A8 69 38    *....].w.uz.B..i8*
M: 2019-01-15 06:46:54.635 0050:  C9 E1 D6 83 51 A7 7C E0 25 18 C3 0E CC 9C 7A 3C    *....Q.|.%.....z<*
M: 2019-01-15 06:46:54.635 0060:  80 77 E8 F1 08 E7 11 C4 CD 5D 7F 77 FD 75 7A C8    *.w.......].w.uz.*
M: 2019-01-15 06:46:54.635 0070:  42 14 A8 69 38 C9 E1 D6 83 51 A7 7C E0 25 18 C3    *B..i8....Q.|.%..*
M: 2019-01-15 06:46:54.636 0080:  2E 8C 9D 3A 3C 80 77 E8 F1 08 E7 11 C4 CD 5D 7F    *...:<.w.......].*
M: 2019-01-15 06:46:54.636 0090:  77 FD 75 7A C8 42 14 A8 69 38 C9 E1 D6 83 51 A7    *w.uz.B..i8....Q.*
M: 2019-01-15 06:46:54.636 00A0:  7C E0 25 18 C3 0E CC 9C 7A 3C 80 77 E8 F1 08 E7    *|.%.....z<.w....*
M: 2019-01-15 06:46:54.636 00B0:  11 C4 CD 5D 7F 77 FD 75 7A C8 42 14 A8 69 38 C9    *...].w.uz.B..i8.*
M: 2019-01-M: 2019-01-15 06:46:40.048 DMR Talker Alias (Data Format 1, Received 6/10 char): 'BD7NMC'
M: 2019-01-15 06:46:40.049 DMR Slot 2, Embedded Talker Alias Block 1
M: 2019-01-15 06:46:40.050 0000:  05 00 00 20 20 20 00 00 00                         *...   ...*
M: 2019-01-15 06:46:54.634 Unknown message, type: 09
M: 2019-01-15 06:46:54.634 Buffer dump
M: 2019-01-15 06:46:54.634 0000:  E0 F8 09 09 05 01 71 59 01 01 01 01 FF E0 25 18    *......qY......%.*
M: 2019-01-15 06:46:54.635 0010:  C3 0E CC 9C 7A 3C 80 77 E8 F1 08 E7 11 C4 CD 5D    *....z<.w.......]*
M: 2019-15 06:46:54.636 00C0:  E1 D6 83 51 A7 7C E0 25 18 C3 0E CC 9C 7A 3C 80    *...Q.|.%.....z<.*
M: 2019-01-15 06:46:54.636 00D0:  77 E8 F1 08 E7 11 C4 CD 5D 7F 77 FD 75 7A C8 42    *w.......].w.uz.B*
M: 2019-01-15 06:46:54.636 00E0:  14 A8 69 38 C9 E1 D6 83 51 A7 7C E0 25 18 C3 0E    *..i8....Q.|.%...*
M: 2019-01-15 06:46:54.636 00F0:  CC 9C 7A 3C 80 77 E8 F1                            *..z<.w..*
M: 2019-01-15 06:46:54.637 DMR Slot 2, network watchdog has expired, 6.2 seconds, 0% packet loss, BER: 0.0%
E: 2019-01-15 06:46:54.637 No reply from the modem for some time, resetting it
M: 2019-01-15 06:46:54.637 Closing the MMDVM
M: 2019-01-15 06:46:56.659 Opening the MMDVM
I: 2019-01-15 06:46:58.670 MMDVM protocol version: 1, description: Nano_hotSPOT-v1.4.14 20181209 14.7456MHz dual ADF7021 FW by CA6JAU GitID #8d77ff3
M: 2019-01-15 06:46:58.703 DMR Slot 2, received network late entry from 46001 to TG 46001
M: 2019-01-15 06:46:58.715 DMR Slot 2, received network end of voice transmission, 0.4 seconds, 0% packet loss, BER: 0.0%
M: 2019-01-15 06:46:59.208 DMR Slot 2, received RF voice header from BI7JTA to TG 46001
M: 2019-01-15 06:47:14.088 DMR Slot 2, received RF end of voice transmission, 14.8 seconds, BER: 0.3%, RSSI: -47/-47/-47 dBm
M: 2019-01-15 06:47:17.263 DMR Slot 2, received network voice header from 46001 to TG 46001
M: 2019-01-15 06:47:17.901 DMR Talker Alias (Data Format 1, Received 6/10 char): 'BD7NMC'
M: 2019-01-15 06:47:17.901 DMR Slot 2, Embedded Talker Alias Header
M: 2019-01-15 06:47:17.901 0000:  04 00 54 42 44 37 4E 4D 43                         *..TBD7NMC*
M: 2019-01-15 06:47:18.595 DMR Talker Alias (Data Format 1, Received 6/10 char): 'BD7NMC'
M: 2019-01-15 06:47:18.597 DMR Slot 2, Embedded Talker Alias Block 1
M: 2019-01-15 06:47:18.597 0000:  05 00 00 20 20 20 00 00 00                         *...   ...*
M: 2019-01-15 06:47:23.081 DMR Slot 2, received network end of voice transmission, 5.8 seconds, 0% packet loss, BER: 0.0%
M: 2019-01-15 06:47:25.668 DMR Slot 2, received RF voice header from BI7JTA to TG 46001
M: 2019-01-15 06:47:30.168 DMR Slot 2, received RF end of voice transmission, 4.3 seconds, BER: 0.3%, RSSI: -47/-47/-47 dBm
M: 2019-01-15 06:47:33.386 DMR Slot 2, received network voice header from 46001 to TG 46001
M: 2019-01-15 06:47:34.019 DMR Talker Alias (Data Format 1, Received 6/10 char): 'BD7NMC'
M: 2019-01-15 06:47:34.020 DMR Slot 2, Embedded Talker Alias Header
M: 2019-01-15 06:47:34.021 0000:  04 00 54 42 44 37 4E 4D 43                         *..TBD7NMC*
M: 2019-01-15 06:47:34.718 DMR Talker Alias (Data Format 1, Received 6/10 char): 'BD7NMC'
M: 2019-01-15 06:47:34.720 DMR Slot 2, Embedded Talker Alias Block 1
M: 2019-01-15 06:47:34.720 0000:  05 00 00 20 20 20 00 00 00                         *...   ...*
M: 2019-01-15 06:47:37.224 DMR Slot 2, received network end of voice transmission, 3.8 seconds, 0% packet loss, BER: 0.0%
E: 2019-01-15 06:49:58.062 No reply from the modem for some time, resetting it
M: 2019-01-15 06:49:58.063 Closing the MMDVM
M: 2019-01-15 06:50:00.064 Opening the MMDVM
E: 2019-01-15 06:50:12.893 Unable to read the firmware version after six attempts
M: 2019-01-15 06:50:17.893 Opening the MMDVM
I: 2019-01-15 06:56:32.076 This software is for use on amateur radio networks only,
I: 2019-01-15 06:56:32.080 it is to be used for educational purposes only. Its use on
I: 2019-01-15 06:56:32.081 commercial networks is strictly prohibited.
I: 2019-01-15 06:56:32.081 Copyright(C) 2015-2018 by Jonathan Naylor, G4KLX and others
M: 2019-01-15 06:56:32.082 MMDVMHost-20181107_Pi-Star is starting
M: 2019-01-15 06:56:32.082 Built 09:24:10 Nov 12 2018 (GitID #9444eca)

**Comment by g4klx** [comment]
Message type 09 is the result of running in RSSI Calibration mode. This implies that a suitable message has been sent to the modem from somewhere. This message is never sent from the host software, but can be sent from MMDVMCal. It may be an issue with the hotspot firmware too, and that is Andy CA6JAU's domain.

**Comment by bi7jta** [comment]
Thanks you G4KLX reply, 
why I ask here, the reason is just happen after Jun 14th when the Pi-Star update, not happen before.
The firmware is build by VR2VYE , recently day not change. 
>  Nano_hotSPOT-v1.4.14 20181209 14.7456MHz dual ADF7021 FW by CA6JAU GitID #8d77ff3 

I also find the "overflow in the DMR slot RF queue" in another duplex HS, when connection down.
=========================
M: 2019-01-15 11:32:49.855 DMR Talker Alias (Data Format 1, Received 18/18 char): 'BH7KCJ DMR TG46073'
M: 2019-01-15 11:32:49.855 DMR Slot 2, Embedded Talker Alias Block 2
M: 2019-01-15 11:32:49.855 0000:  06 00 34 36 30 37 33 00 00                         *..46073..*
E: 2019-01-15 11:32:57.114 DMR Slot 2, overflow in the DMR slot RF queue
E: 2019-01-15 11:32:57.186 DMR Slot 2, overflow in the DMR slot RF queue
E: 2019-01-15 11:32:57.232 DMR Slot 2, overflow in the DMR slot RF queue
...
E: 2019-01-15 11:33:13.376 DMR Slot 2, overflow in the DMR slot RF queue
M: 2019-01-15 11:33:13.376 DMR Slot 2, received network end of voice transmission, 25.5 seconds, 0% packet loss, BER: 0.0%
E: 2019-01-15 11:33:14.473 No reply from the modem for some time, resetting it
M: 2019-01-15 11:33:14.473 Closing the MMDVM
M: 2019-01-15 11:33:16.473 Opening the MMDVM
E: 2019-01-15 11:33:29.289 Unable to read the firmware version after six attempts
M: 2019-01-15 11:33:34.289 Opening the MMDVM

**Comment by shawnchain** [comment]
Everything works fine here in my environment, So I think you'd better find out what's changed inside PI-Star...

**Comment by bi7jta** [comment]
All normal when I reflash pi-star to 3.4.17 or 4.0RC  .
I guess some config files be damaged, not matter how I recovery factory or upgrade, implicit bug cause “overflow in the DMR slot RF queue”, I will continue trace the log in debug code.
TKS all.
