### ISSUE TITLE
DMR Beacon will never triggered under fixed mode

### ISSUE THREAD

**Issue by shawnchain** [g4klx/MMDVMHost#490]
https://github.com/g4klx/MMDVMHost/blob/6b7dba92aa6be12213b20da82c160f896fc9ba0f/MMDVMHost.cpp#L999

See above code.

**Comment by shawnchain** [comment]
I'm not tested yet, but there're several places where checking if 
```if (m_mode == MODE_IDLE)```
and may also possibly broken under the fixed mode ?

**Comment by g4klx** [comment]
The fixed mode setting has now been removed. So beacons should operate as before. Just need to test build it and merge to master.

**Comment by phl0** [comment]
Compiles cleanly on my Linux system. Cannot test at this very moment. Sri.
