### ISSUE TITLE
ModeHang...

### ISSUE THREAD

**Issue by dl1bz** [g4klx/MMDVMHost#493]
One question: Is it possible without any defined hangup value stay constantly in selected mode (if only one mode in mmdvm.ini) ? If I not define any hangup values, you set default values I see. But what I ask is initialisation > stay in mode the whole time mmdvmhost running and **not** fall back in listening mode after expiration of ModeHang, I mean without timeout (as an additional option as one mode lock).
Is it possible to implement such behavior ?

73 Heiko, DL1BZ

**Comment by phl0** [comment]
I have tested the situation with YSF being the only mode enabled in MMDVM.ini. MMDVM_HS firmware was compiled with ENABLE_SCAN_MODE disabled. I can key up in YSF directly. And even the "X" command for Wires-X is being decoded on the first try in idle mode. 
Whereas if the box is scanning modes it mostly misses the first YSF Wires-X command. I had to press PTT for severeal seconds to get the unit into YSF mode and then press "X".
Disabling SCAN MODE in MMDVM_HS and disabling all but YSF in MMDVM.ini seems to achieve what you ask for.
