### ISSUE TITLE
issue sending SMS from MOTO SL4000

### ISSUE THREAD

**Issue by DL2MF** [g4klx/MMDVMHost#5]
I had the following issue when using MMDVMhost.exe (compiled with VS2013 for windows 32bit, running on Windows 10, 64-Bit) with a raw control panel for the DVMEGA on an arduino and trying to send SMS from a MOTO SL4000:

Debug Error!
Program: C:\MMDVMHost\mmdvmhost.exe
Module: C:\MMDVMHost\mmdvmhost.exe
File: C:\my_path\mmdvmhost-master\dmrslot.cpp  Line: 1100

Run-Time Check Failure #2 - Stack around the variable 'payload' was corrupted.

73 de Meinhard "Mike", DL2MF

**Comment by g0wfv** [comment]
Is this problem still ongoing?

**Comment by DL2MF** [comment]
Hi Jonathan & contributors,

after a couple of months I did just configure a new hotspot with MMDVM and DVMEGA.
Messaging now works like a charm between MOTO SL4000, Hytera and Chinese radio MD390G.
This issue should be closed, mni tnx fr all your work on MMDVM.

73 Mike, DL2MF
