### ISSUE TITLE
Error Compiler "CMMDVMHost"

### ISSUE THREAD

**Issue by YV5OF** [g4klx/MMDVMHost#50]
Hi,
Today clone repository and make, but this step show error : 

++ -g -O3 -Wall -std=c++0x -c -o MMDVMHost.o MMDVMHost.cpp
MMDVMHost.cpp: In member function ‘int CMMDVMHost::run()’:
MMDVMHost.cpp:165:24: warning: NULL used in arithmetic [-Wpointer-arith]
       if (mmdvm_uid == NULL) {
                        ^
MMDVMHost.cpp:171:24: warning: NULL used in arithmetic [-Wpointer-arith]
       if (mmdvm_gid == NULL) {
                        ^
I'm installing a raspberry, with the latest version of jezzy and all updated components.

73

**Comment by g0wfv** [comment]
Fixed by commit 06825c

Please close if it works for you :-)

**Comment by YV5OF** [comment]
Working my friend, many thank for your fast replay and fix.

73.
