### ISSUE TITLE
MMDVHost don't works with MobileGPS

### ISSUE THREAD

**Issue by sp2ong** [g4klx/MMDVMHost#502]
After many times monitoring UDP port 7834 it is look like MMDVMHost not working with MobileGPS despite the [MobileGPS] option enabled, because not send request data to MobileGPS , when  YSFGateway which send request to MobileGPS if in configuration we setup MobileGPS and APRS enable but when we disable APRS YSFGateway don't send request to MbileGPS.

It will be nice to use coordinates from Mobile GPS or other application (for example Android "Share GPS") to update coordinates in MMDVMHost and send to Brandmeister server

**Comment by g4klx** [comment]
MobileGPS works well. Maybe there is a bug in MMDVM Host with MobileGPS. Mobile GPS is based on the applications pulling data fromMobileGPS regularly but MobileGPS being intelligent enough to only provide data when something has changed, either some movement or a period of time has elapsed.

**Comment by sp2ong** [comment]
Yes, I confirm that MobileGPS works well because I have used MobileGPS with own script to get coordinates and next send to APRS.fi
But MMDVMHost doesn't send pulling data to MobileGPS to get data like to do this YSFGateway.

I have very long listened to on port 7834 by tcpdump and MMDVMHost never sent the string "MMDVMHost" on port 7834 ( https://github.com/g4klx/MMDVMHost/blob/master/MobileGPS.cpp#L74 )

**Comment by sp2ong** [comment]
The question is what will MMDVMHost do when receiving the coordinates from MobileGPS. Will it be able to send them to BM Network and update the data in the BM database ? because it would be valuable to retrieve data via BM API e.g. display the current location of the hotspot on the map. Data to APRS can be transferred independently e.g. by a script

**Comment by g4klx** [comment]
It sends the data to BM, any questions beyond the host or the gateway should be addressed to the people who control the masters, not me.
