### ISSUE TITLE
No reply from the modem for some time, resetting it. Closing the MMDVM.

### ISSUE THREAD

**Issue by s-s-s** [g4klx/MMDVMHost#51]
Helps only restart (stop\start) the service or reboot RaspberryPi

```
M: 2016-05-06 16:56:33.526 Mode set to Idle
M: 2016-05-06 17:00:04.331 DMR Slot 2, received network voice header from 2509001 to TG 2501
M: 2016-05-06 17:00:04.337 Mode set to DMR
M: 2016-05-06 17:00:10.558 DMR Slot 2, received network end of voice transmission, 6.2 seconds, 5% packet loss, BER: 0.0%
M: 2016-05-06 17:00:16.952 DMR Slot 2, received network voice header from 2501001 to TG 2501
M: 2016-05-06 17:00:17.595 DMR Slot 2, received network end of voice transmission, 0.5 seconds, 0% packet loss, BER: 0.0%
M: 2016-05-06 17:00:24.042 DMR Slot 2, received network voice header from 2501001 to TG 2501
M: 2016-05-06 17:00:29.357 DMR Slot 2, received network end of voice transmission, 5.2 seconds, 1% packet loss, BER: 0.0%
M: 2016-05-06 17:00:39.368 Mode set to Idle
M: 2016-05-06 17:00:55.227 DMR Slot 2, received network voice header from 2501001 to TG 2501
M: 2016-05-06 17:00:55.233 Mode set to DMR
M: 2016-05-06 17:00:59.732 DMR Slot 2, received network end of voice transmission, 4.4 seconds, 4% packet loss, BER: 0.0%
M: 2016-05-06 17:01:02.594 DMR Slot 2, received network voice header from 2509001 to TG 2501
M: 2016-05-06 17:01:05.581 DMR Slot 2, received network end of voice transmission, 3.0 seconds, 4% packet loss, BER: 0.0%
M: 2016-05-06 17:01:14.591 DMR Slot 2, received network voice header from 2509001 to TG 2501
M: 2016-05-06 17:01:27.299 DMR Slot 2, received network end of voice transmission, 12.7 seconds, 2% packet loss, BER: 0.0%
M: 2016-05-06 17:01:37.307 Mode set to Idle
M: 2016-05-06 17:19:28.149 Mode set to DMR
M: 2016-05-06 17:19:38.164 Mode set to Idle
E: 2016-05-06 17:55:21.499 No reply from the modem for some time, resetting it
M: 2016-05-06 17:55:21.499 Closing the MMDVM
M: 2016-05-06 17:55:23.500 Opening the MMDVM
I: 2016-05-06 17:55:25.511 MMDVM protocol version: 1, description: DVMEGA HR2.28
E: 2016-05-06 17:55:25.531 No reply from the modem for some time, resetting it
M: 2016-05-06 17:55:25.531 Closing the MMDVM
M: 2016-05-06 17:55:27.532 Opening the MMDVM
I: 2016-05-06 17:55:29.542 MMDVM protocol version: 1, description: DVMEGA HR2.28
E: 2016-05-06 17:55:29.563 No reply from the modem for some time, resetting it
M: 2016-05-06 17:55:29.564 Closing the MMDVM
```

MMDVMHost-20160428
DVMEGA HR2.28
RaspberryPi2 Linux raspberrypi 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux

**Comment by g0wfv** [comment]
I'm getting a similar error, probably due to network issues.  What happens in my case is the host loses its connection to the master (I suspect due to network latency/loss as I am currently on a "public" wifi in a hotel - I have no problem at home!) but reconnects within 4-5 seconds however, the modem then gets closed and reopened as above.

I have made a slight addition to the code to (hopefully) reset a timer that is triggering the modem reset and I am monitoring the logs for a re-occurrence, but sod's law says it won't happen again for a while (It happened twice yesterday but otherwise ran for most of the day!)

I have tried forcing a DOS attack on my RPi (naughty!) to simulate a slow network, but MMDVMHost seems to be rather resilient when it comes to network latency (a bonus I suppose) but only makes me think that when my RPi loses the network, it's a complete cut-off rather than a slowing down of network traffic.

We shall see ...

**Comment by s-s-s** [comment]
It is probably due to network issues on the BM side, I think.
I have a very good ethernet connection

**Comment by g0wfv** [comment]
Could be a mixture of both in my case then ;-)

On Sat, May 14, 2016 at 9:00 AM s-s-s <notifications@github.com> wrote:

> It is probably due to network issues on the BM side, I think.
> I have a very good ethernet connection
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/g4klx/MMDVMHost/issues/51#issuecomment-219207149>
>
-- 

A J Corbett

G0WFV

**Comment by s-s-s** [comment]
I think the main reason is the lack of activity for a long time
`M: 2016-05-06 **17:19:38.164** Mode set to Idle
E: 2016-05-06 **17:55:21.499**`

**Comment by g0wfv** [comment]
Interestingly, when I lost the master connection, it came up with quite a
few errors in some sort of sequence which leads me to believe it's a spiral
of death!

Here's what I think is happening from the log segments I have pasted below
...

First it can't find the target address of the master (that's the err 101 -
something to do with local routing tables - ie, the Rpi has lost its
network connection!)

Then it reconnects to the network (after retrying every millisecond!) and
in turn the master, but then goes into the modem loop that we are all
experiencing.

It then receives network data, but can't write it to the modem as it's
stuck in our a;ll too familiar loop.

Then the network watchdog times out, then the RF queue overflows, by this
time it's all gone Pete Tong!

Anyway, for what it's worth, log extracts below (bit if bedtime reading!)
....

2016-05-14 02:49:41.209 Error returned from sendto, err: 101
E: 2016-05-14 02:49:41.209 Socket has failed when writing data to the
master, retrying connection
M: 2016-05-14 02:49:41.209 Closing DMR IPSC
E: 2016-05-14 02:49:41.210 Error returned from sendto, err: 101
E: 2016-05-14 02:49:41.210 Socket has failed when writing data to the
master, retrying connection
M: 2016-05-14 02:49:41.210 Closing DMR IPSC

.....

M: 2016-05-14 02:49:44.066 Closing DMR IPSC
E: 2016-05-14 02:49:44.066 Error returned from sendto, err: 101
E: 2016-05-14 02:49:44.066 Socket has failed when writing data to the
master, retrying connection
M: 2016-05-14 02:49:44.067 Closing DMR IPSC
M: 2016-05-14 02:49:44.082 Opening DMR IPSC
M: 2016-05-14 02:49:44.083 Opening DMR IPSC

.....

M: 2016-05-14 02:49:45.798 Opening DMR IPSC
M: 2016-05-14 02:49:45.798 Opening DMR IPSC
E: 2016-05-14 02:49:45.799 No reply from the modem for some time, resetting
it
M: 2016-05-14 02:49:45.799 Closing the MMDVM
M: 2016-05-14 02:49:47.800 Opening the MMDVM
I: 2016-05-14 02:49:49.810 MMDVM protocol version: 1, description: DVMEGA
HR2.28
E: 2016-05-14 02:49:49.831 No reply from the modem for some time, resetting
it
M: 2016-05-14 02:49:49.832 Closing the MMDVM
M: 2016-05-14 02:49:51.832 Opening the MMDVM
I: 2016-05-14 02:49:53.843 MMDVM protocol version: 1, description: DVMEGA
HR2.28
E: 2016-05-14 02:49:53.864 No reply from the modem for some time, resetting
it
M: 2016-05-14 02:49:53.864 Closing the MMDVM
M: 2016-05-14 02:49:55.865 Opening the MMDVM

.....

E: 2016-05-14 02:53:47.764 No reply from the modem for some time, resetting
it
M: 2016-05-14 02:53:47.765 Closing the MMDVM
M: 2016-05-14 02:53:49.765 Opening the MMDVM
I: 2016-05-14 02:53:51.776 MMDVM protocol version: 1, description: DVMEGA
HR2.28
M: 2016-05-14 02:53:51.851 DMR Slot 2, received network voice header from
VK7JD to TG 9
M: 2016-05-14 02:53:51.851 DMR Slot 2, network watchdog has expired, 0.1
seconds, 0% packet loss, BER: 0.0%
E: 2016-05-14 02:53:51.868 No reply from the modem for some time, resetting
it
M: 2016-05-14 02:53:51.869 Closing the MMDVM
M: 2016-05-14 02:53:53.870 Opening the MMDVM
I: 2016-05-14 02:53:55.881 MMDVM protocol version: 1, description: DVMEGA
HR2.28
M: 2016-05-14 02:53:55.930 DMR Slot 2, received network voice header from
VK7JD to TG 9
M: 2016-05-14 02:53:55.930 DMR Slot 2, network watchdog has expired, 0.1
seconds, 0% packet loss, BER: 0.0%
E: 2016-05-14 02:53:55.948 No reply from the modem for some time, resetting
it
M: 2016-05-14 02:53:55.949 Closing the MMDVM
M: 2016-05-14 02:53:57.950 Opening the MMDVM

.....

E: 2016-05-14 03:00:19.568 No reply from the modem for some time, resetting
it
M: 2016-05-14 03:00:19.569 Closing the MMDVM
M: 2016-05-14 03:00:21.570 Opening the MMDVM
I: 2016-05-14 03:00:23.581 MMDVM protocol version: 1, description: DVMEGA
HR2.28
M: 2016-05-14 03:00:23.656 DMR Slot 2, received network voice header from
G4XLM to TG 9
M: 2016-05-14 03:00:23.657 DMR Slot 2, network watchdog has expired, 0.1
seconds, 0% packet loss, BER: 0.0%
E: 2016-05-14 03:00:23.674 No reply from the modem for some time, resetting
it
M: 2016-05-14 03:00:23.674 Closing the MMDVM
M: 2016-05-14 03:00:25.675 Opening the MMDVM
I: 2016-05-14 03:00:27.687 MMDVM protocol version: 1, description: DVMEGA
HR2.28
M: 2016-05-14 03:00:27.736 DMR Slot 2, received network voice header from
G4XLM to TG 9
M: 2016-05-14 03:00:27.736 DMR Slot 2, network watchdog has expired, 0.1
seconds, 0% packet loss, BER: 0.0%
E: 2016-05-14 03:00:27.754 No reply from the modem for some time, resetting
it

.....

E: 2016-05-14 03:33:12.273 No reply from the modem for some time, resetting
it
M: 2016-05-14 03:33:12.274 Closing the MMDVM
M: 2016-05-14 03:33:14.274 Opening the MMDVM
I: 2016-05-14 03:33:16.285 MMDVM protocol version: 1, description: DVMEGA
HR2.28
E: 2016-05-14 03:33:16.306 DMR Slot 2, overflow in the DMR slot RF queue
E: 2016-05-14 03:33:16.306 DMR Slot 2, overflow in the DMR slot RF queue
E: 2016-05-14 03:33:16.306 DMR Slot 2, overflow in the DMR slot RF queue
E: 2016-05-14 03:33:16.306 DMR Slot 2, overflow in the DMR slot RF queue
E: 2016-05-14 03:33:16.307 DMR Slot 2, overflow in the DMR slot RF queue
E: 2016-05-14 03:33:16.307 DMR Slot 2, overflow in the DMR slot RF queue
E: 2016-05-14 03:33:16.307 DMR Slot 2, overflow in the DMR slot RF queue
M: 2016-05-14 03:33:16.335 DMR Slot 2, received network late entry from
M6XTB to TG 9
E: 2016-05-14 03:33:16.336 DMR Slot 2, overflow in the DMR slot RF queue
M: 2016-05-14 03:33:16.337 DMR Slot 2, network watchdog has expired, 0.1
seconds, 0% packet loss, BER: 13.4%
E: 2016-05-14 03:33:16.337 DMR Slot 2, overflow in the DMR slot RF queue
E: 2016-05-14 03:33:16.338 DMR Slot 2, overflow in the DMR slot RF queue
E: 2016-05-14 03:33:16.339 DMR Slot 2, overflow in the DMR slot RF queue
E: 2016-05-14 03:33:16.356 No reply from the modem for some time, resetting
it
M: 2016-05-14 03:33:16.356 Closing the MMDVM
M: 2016-05-14 03:33:18.357 Opening the MMDVM
I: 2016-05-14 03:33:20.369 MMDVM protocol version: 1, description: DVMEGA
HR2.28
E: 2016-05-14 03:33:20.390 No reply from the modem for some time, resetting
it
M: 2016-05-14 03:33:20.391 Closing the MMDVM
M: 2016-05-14 03:33:22.391 Opening the MMDVM
I: 2016-05-14 03:33:24.402 MMDVM protocol version: 1, description: DVMEGA
HR2.28
E: 2016-05-14 03:33:24.424 No reply from the modem for some time, resetting
it
M: 2016-05-14 03:33:24.424 Closing the MMDVM
M: 2016-05-14 03:33:26.424 Opening the MMDVM
I: 2016-05-14 03:33:28.435 MMDVM protocol version: 1, description: DVMEGA
HR2.28
E: 2016-05-14 03:33:28.456 Connection to the master has timed out, retrying
connection
M: 2016-05-14 03:33:28.456 Closing DMR IPSC
M: 2016-05-14 03:33:28.457 Opening DMR IPSC




On Sat, May 14, 2016 at 9:05 AM Tony Corbett <tonyc.uk@gmail.com> wrote:

> Could be a mixture of both in my case then ;-)
>
> On Sat, May 14, 2016 at 9:00 AM s-s-s <notifications@github.com> wrote:
>
>> It is probably due to network issues on the BM side, I think.
>> I have a very good ethernet connection
>>
>> —
>> You are receiving this because you commented.
>>
>>
>> Reply to this email directly or view it on GitHub
>> <https://github.com/g4klx/MMDVMHost/issues/51#issuecomment-219207149>
>>
> --
>
> A J Corbett
>
> G0WFV
>
-- 

A J Corbett

G0WFV

**Comment by s-s-s** [comment]
As I see in your log you have only a trouble of lost connection with the master  because a common network connection is lost. 
I have only a timeout of activity.
But a error of mmdmv about modem in logs is the same.

**Comment by g0wfv** [comment]
It all seems to lead to the same death spiral!

On Sat, 14 May 2016 12:04 s-s-s, <notifications@github.com> wrote:

> As I see in your log you have only a trouble of lost connection with the
> master because a common network connection is lost.
> I have only a timeout of activity.
> But a error of mmdmv about modem in logs is the same.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/g4klx/MMDVMHost/issues/51#issuecomment-219209413>
>
-- 

A J Corbett

G0WFV

**Comment by g0wfv** [comment]
I've submitted a pull request which Jon has merged which should solve this
problem.

In Modem.cpp, I've captured the spiral by stopping an inactivity timer if
the firmware is read successfully.  This allows the modem to be read as
normal without resetting it again.

I've also alterred DMRIPSC.cpp to tell the host to retry a connect if it
times out in the master connection.  This *may* keep the IPSC trying to
connect even if the master is down at the far end, but it seems to work in
my case here.

I think we still need to capture the "err 101" (Network unreachable) error
in the socket and cope with it in more graceful manner, but what
DMRIPSC.cpp does currently works (albeit with a bit of overkill retrying as
quickly as possible!)

Please keep an eye on it and let me know if it works for you.  If not, post
your log in here and I'll see if I can trace what causes your problem.

On Sat, May 14, 2016 at 10:11 AM Tony Corbett <tonyc.uk@gmail.com> wrote:

> It all seems to lead to the same death spiral!
>
> On Sat, 14 May 2016 12:04 s-s-s, <notifications@github.com> wrote:
>
>> As I see in your log you have only a trouble of lost connection with the
>> master because a common network connection is lost.
>> I have only a timeout of activity.
>> But a error of mmdmv about modem in logs is the same.
>>
>> —
>> You are receiving this because you commented.
>>
>>
>> Reply to this email directly or view it on GitHub
>> <https://github.com/g4klx/MMDVMHost/issues/51#issuecomment-219209413>
>>
> --
>
> A J Corbett
>
> G0WFV
>
-- 

A J Corbett

G0WFV

**Comment by g0wfv** [comment]
Sorry, yes, the causes of our problems are not the same, but the end result is, which one of the alterations I have made attempts to solve.  Let me know if it works for you.

**Comment by s-s-s** [comment]
Ok, I'll write.

**Comment by iw9grl** [comment]
I have the same issue before update, it was very frustrating , during a day I needed to verify remotely if it went down .
Now it seems to work very fine, I have not any reset of the connection, no this kind of fault ..... other fault to solve :+1: 
73 de IW9GRL

**Comment by s-s-s** [comment]
> I had the same issue before update, it was very frustrating , during a day I needed to verify remotely if it went down .

What version you upgraded?

**Comment by g0wfv** [comment]
I applied a fix to the MMDVMHost source code 2 days ago which seems to have
solved this problem for a lot of people.

You need to update to that version of the code.

On Tue, 17 May 2016 15:05 s-s-s, <notifications@github.com> wrote:

> I had the same issue before update, it was very frustrating , during a day
> I needed to verify remotely if it went down .
>
> What version you upgraded?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/g4klx/MMDVMHost/issues/51#issuecomment-219697949>
>
-- 

A J Corbett

G0WFV

**Comment by iw9grl** [comment]
Hi Tony ... yes I confirm ... before this update I had the problem, now all works very well !!!!!!!

The other problem that I highlighted regarding the : Received a NAK from the MMDVM, command = 0x11, reason = 5 during DSTAR receiption ; I just opened a ticket some days ago ......

thank you for your appreciated support !
73 de IW9GRL

**Comment by Giorgiofox** [comment]
I think that this can be closed.

**Comment by g0wfv** [comment]
Since I submitted the fix, it's been running continuously here on a very
dodgy hotel wifi for days and has recovered gracefully with no apparent
issues each time it's been booted off.

I agree; it can be closed (unless s-s-s is still getting problems?!)

On Mon, May 23, 2016 at 8:35 PM Giorgio Campiotti <notifications@github.com>
wrote:

> I think that this can be closed.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/g4klx/MMDVMHost/issues/51#issuecomment-221071714>
>
-- 

A J Corbett

G0WFV

**Comment by s-s-s** [comment]
The problem no longer occurs.

**Comment by MikhailR2AADR** [comment]
Hi!
**1-problem:**
[root@orangepizero3](mailto:root@orangepizero3):/opt# git clone https://github.com/g4klx/MMDVMHost.git
fatal: целевой путь «MMDVMHost» уже существует и не является пустым каталогом.
[root@orangepizero3](mailto:root@orangepizero3):/opt# git clone https://github.com/g4klx/MMDVMHost.git
Клонирование в «MMDVMHost»…
remote: Enumerating objects: 13513, done.
remote: Counting objects: 100% (1773/1773), done.
remote: Compressing objects: 100% (513/513), done.
remote: Total 13513 (delta 1317), reused 1673 (delta 1260), pack-reused 11740
Получение объектов: 100% (13513/13513), 21.22 MiB | 6.37 MiB/s, готово.
Определение изменений: 100% (9971/9971), готово.
[root@orangepizero3](mailto:root@orangepizero3):/opt# cd MMDVMHost
[root@orangepizero3](mailto:root@orangepizero3):/opt/MMDVMHost# make
echo "const char *gitversion = \"f02cbcb141e53f1aeac5d0b6ee6dfc9d3b6e2b61\";" > GitVersion.h
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o AMBEFEC.o AMBEFEC.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o BCH.o BCH.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o AX25Control.o AX25Control.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o AX25Network.o AX25Network.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o BPTC19696.o BPTC19696.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o CASTInfo.o CASTInfo.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o Conf.o Conf.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o CRC.o CRC.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o Display.o Display.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DMRControl.o DMRControl.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DMRCSBK.o DMRCSBK.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DMRData.o DMRData.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DMRDataHeader.o DMRDataHeader.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DMRDirectNetwork.o DMRDirectNetwork.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DMREMB.o DMREMB.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DMREmbeddedData.o DMREmbeddedData.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DMRFullLC.o DMRFullLC.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DMRGatewayNetwork.o DMRGatewayNetwork.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DMRLookup.o DMRLookup.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DMRLC.o DMRLC.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DMRNetwork.o DMRNetwork.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DMRShortLC.o DMRShortLC.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DMRSlot.o DMRSlot.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DMRSlotType.o DMRSlotType.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DMRAccessControl.o DMRAccessControl.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DMRTA.o DMRTA.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DMRTrellis.o DMRTrellis.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DStarControl.o DStarControl.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DStarHeader.o DStarHeader.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DStarNetwork.o DStarNetwork.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o DStarSlowData.o DStarSlowData.cpp
c++ -g -O3 -Wall -std=c++0x -pthread -DHAVE_LOG_H -I/usr/local/include -c -o FMControl.o FMControl.cpp
In file included from FMControl.h:22,
                 from FMControl.cpp:19:
FMNetwork.h:25:10: fatal error: samplerate.h: Нет такого файла или каталога
   25 | #include <samplerate.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:29: FMControl.o] Ошибка 1
[root@orangepizero3](mailto:root@orangepizero3):/opt/MMDVMHost#
File not exist!

**2 problem**
Make I2C-address for OLED Type=6 How make address for OLED? i2c/**0x3c**
By Orange Pi zero 3
Mikhail
R2AADR

Thanks! 73 :)
