### ISSUE TITLE
Processing messaging (SMS) ( I'm not sure if it is an issue of MMDVMHost )

### ISSUE THREAD

**Issue by YV5OF** [g4klx/MMDVMHost#52]
Hi, I'm not sure if this is a side issue MMDVM, processing of outgoing SMS sometimes succeeds in being sent, they arrive garbage characters. But sometimes he can not even sending out and fails.

In the case of reception I observe arriving packets (via log), but not end up being processed and never become despatched to the radio.

In the case of courier on APRS, works 100% in both vias (APRS <-> DMR).

73!

**Comment by s-s-s** [comment]
```

"M: 2016-05-06 13:47:17.145 DMR Slot 2, received RF Preamble CSBK from 2502007 to 2501
D: 2016-05-06 13:47:17.205 Unconfirmed Data Header
D: 2016-05-06 13:47:17.205 0000:  02 4A 00 09 C5 26 2D 77 85 00 F9 09                *.J...&-w....*
M: 2016-05-06 13:47:17.205 DMR Slot 2, received RF data header from 2502007 to 2501, 5 blocks
M: 2016-05-06 13:47:17.505 DMR Slot 2, ended RF data transmission
M: 2016-05-06 13:47:27.519 Mode set to Idle
```


```
D: 2016-05-06 16:37:28.040 Defined Short Data Header
D: 2016-05-06 16:37:28.041 0000:  8D A3 00 09 C5 26 48 C9 01 50 43 07                *.....&H..PC.*
M: 2016-05-06 16:37:28.041 DMR Slot 2, received network data header from 2509001 to TG 2501, 3 blocks
M: 2016-05-06 16:37:28.046 Mode set to DMR
M: 2016-05-06 16:37:28.208 DMR Slot 2, ended network data transmission
M: 2016-05-06 16:37:38.217 Mode set to Idle
```

**Comment by YV5OF** [comment]
Hi Team,

Today try again send SMS, but not working : 

M: 2016-05-10 20:37:27.126 DMR Slot 2, received RF Preamble CSBK from YV5OF to 214990
D: 2016-05-10 20:37:27.215 IPSC Transmitted
D: 2016-05-10 20:37:27.219 0000:  44 4D 52 44 00 70 13 6F 03 47 CE 00 70 13 6F E3    *DMRD.p.o.G..p.o.*
D: 2016-05-10 20:37:27.225 0010:  D6 8D 49 43 46 98 06 1F 8D 14 0E F4 75 59 DE F1    *..ICF.......uY..*
D: 2016-05-10 20:37:27.230 0020:  04 CD FF 57 D7 5D F5 DA CB 0A 23 F8 96 19 7C 61    *...W.]....#...|a*
D: 2016-05-10 20:37:27.236 0030:  CD 9B 2D 9A 44 00 00                               *..-.D..*
M: 2016-05-10 20:37:27.243 DMR Slot 2, received RF Preamble CSBK from YV5OF to 214990
D: 2016-05-10 20:37:27.276 IPSC Transmitted
D: 2016-05-10 20:37:27.279 0000:  44 4D 52 44 00 70 13 6F 03 47 CE 00 70 13 6F E3    *DMRD.p.o.G..p.o.*
D: 2016-05-10 20:37:27.286 0010:  D3 44 44 11 46 D8 06 9D 8C 08 0C EC 77 68 52 B1    *.DD.F.......whR.*
D: 2016-05-10 20:37:27.292 0020:  04 CD FF 57 D7 5D F5 DA CB 7A 03 C8 D6 F9 7F C1    *...W.]...z......*
D: 2016-05-10 20:37:27.298 0030:  C8 5B 24 9A 72 00 00                               *.[$.r..*
M: 2016-05-10 20:37:27.305 DMR Slot 2, received RF Preamble CSBK from YV5OF to 214990
D: 2016-05-10 20:37:27.334 IPSC Transmitted
D: 2016-05-10 20:37:27.337 0000:  44 4D 52 44 00 70 13 6F 03 47 CE 00 70 13 6F E3    *DMRD.p.o.G..p.o.*
D: 2016-05-10 20:37:27.344 0010:  93 CC 8E 6D 46 DF 06 1F 8C 80 0C CC 75 29 5E 13    *...mF.......u)^.*
D: 2016-05-10 20:37:27.349 0020:  04 CD FF 57 D7 5D F5 DA CB B2 63 50 D4 78 7D 21    *...W.]....cP.x}!*
D: 2016-05-10 20:37:27.356 0030:  CC 9F 35 12 44 00 00                               *..5.D..*
M: 2016-05-10 20:37:27.362 DMR Slot 2, received RF Preamble CSBK from YV5OF to 214990
D: 2016-05-10 20:37:27.395 Unconfirmed Data Header
D: 2016-05-10 20:37:27.399 0000:  02 48 03 47 CE 70 13 6F 86 00 32 48                *.H.G.p.o..2H*
D: 2016-05-10 20:37:27.405 IPSC Transmitted
D: 2016-05-10 20:37:27.408 0000:  44 4D 52 44 00 70 13 6F 03 47 CE 00 70 13 6F E6    *DMRD.p.o.G..p.o.*
D: 2016-05-10 20:37:27.414 0010:  81 06 7C 6F 4B C5 02 26 57 F6 6A E1 C0 D3 A4 CB    *..|oK..&W.j.....*
D: 2016-05-10 20:37:27.421 0020:  C5 8D FF 57 D7 5D F5 D3 3A 44 7C 78 83 A5 20 26    *...W.]..:D|x.. &*
D: 2016-05-10 20:37:27.427 0030:  43 86 13 35 82 00 00                               *C..5...*
M: 2016-05-10 20:37:27.434 DMR Slot 2, received RF data header from YV5OF to 214990, 6 blocks
D: 2016-05-10 20:37:27.456 IPSC Transmitted
D: 2016-05-10 20:37:27.459 0000:  44 4D 52 44 01 70 13 6F 03 47 CE 00 70 13 6F E7    *DMRD.p.o.G..p.o.*
D: 2016-05-10 20:37:27.466 0010:  81 06 7C 6F 10 AF A9 17 02 A0 01 FC 22 80 46 00    *..|o........".F.*
D: 2016-05-10 20:37:27.471 0020:  85 ED FF 57 D7 5D F5 D0 95 B0 00 64 83 90 06 A0    *...W.].....d....*
D: 2016-05-10 20:37:27.478 0030:  1E 84 5A 08 68 00 00                               *..Z.h..*
D: 2016-05-10 20:37:27.515 IPSC Transmitted
D: 2016-05-10 20:37:27.519 0000:  44 4D 52 44 02 70 13 6F 03 47 CE 00 70 13 6F E7    *DMRD.p.o.G..p.o.*
D: 2016-05-10 20:37:27.525 0010:  81 06 7C 6F 4A FD 25 C8 42 28 10 C5 3A BB 30 63    *..|oJ.%.B(..:.0c*
D: 2016-05-10 20:37:27.531 0020:  45 ED FF 57 D7 5D F5 D0 97 F1 4F D3 CE A4 46 62    *E..W.]....O...Fb*
D: 2016-05-10 20:37:27.538 0030:  4F 1D A3 BF 1E 00 00                               *O......*
D: 2016-05-10 20:37:27.576 IPSC Transmitted
D: 2016-05-10 20:37:27.579 0000:  44 4D 52 44 03 70 13 6F 03 47 CE 00 70 13 6F E7    *DMRD.p.o.G..p.o.*
D: 2016-05-10 20:37:27.585 0010:  81 06 7C 6F 34 58 69 9E 52 2C 10 78 00 C2 52 0C    *..|o4Xi.R,.x..R.*
D: 2016-05-10 20:37:27.591 0020:  85 ED FF 57 D7 5D F5 D0 96 50 41 02 24 33 56 E0    *...W.]...PA.$3V.*
D: 2016-05-10 20:37:27.598 0030:  8F C8 06 1A EF 00 00                               *.......*
D: 2016-05-10 20:37:27.635 IPSC Transmitted
D: 2016-05-10 20:37:27.639 0000:  44 4D 52 44 04 70 13 6F 03 47 CE 00 70 13 6F E7    *DMRD.p.o.G..p.o.*
D: 2016-05-10 20:37:27.645 0010:  81 06 7C 6F 68 98 D0 12 21 02 42 91 24 2A 53 85    *..|oh...!.B.$*S.*
D: 2016-05-10 20:37:27.650 0020:  05 ED FF 57 D7 5D F5 D0 94 08 65 19 A8 E3 07 02    *...W.]....e.....*
D: 2016-05-10 20:37:27.657 0030:  2E D8 41 80 0C 00 00                               *..A....*
D: 2016-05-10 20:37:27.694 IPSC Transmitted
D: 2016-05-10 20:37:27.698 0000:  44 4D 52 44 05 70 13 6F 03 47 CE 00 70 13 6F E7    *DMRD.p.o.G..p.o.*
D: 2016-05-10 20:37:27.704 0010:  81 06 7C 6F 60 09 44 94 2E 68 42 6C 35 E0 93 F1    *..|o`.D..hBl5...*
D: 2016-05-10 20:37:27.710 0020:  85 ED FF 57 D7 5D F5 D0 94 42 A4 85 61 93 45 61    *...W.]...B..a.Ea*
D: 2016-05-10 20:37:27.717 0030:  22 C8 4B 81 20 00 00                               *".K. ..*
D: 2016-05-10 20:37:27.754 IPSC Transmitted
D: 2016-05-10 20:37:27.757 0000:  44 4D 52 44 06 70 13 6F 03 47 CE 00 70 13 6F E7    *DMRD.p.o.G..p.o.*
D: 2016-05-10 20:37:27.763 0010:  81 06 7C 6F 00 46 01 9C 01 28 06 F0 04 D0 0C C0    *..|o.F...(......*
D: 2016-05-10 20:37:27.770 0020:  05 ED FF 57 D7 5D F5 D0 94 10 00 30 06 A0 1C C0    *...W.].....0....*
D: 2016-05-10 20:37:27.776 0030:  1B C0 12 00 16 00 00                               *.......*
M: 2016-05-10 20:37:27.782 DMR Slot 2, ended RF data transmission

**Comment by YV5OF** [comment]
Hi tean,

Today testing again TX and RX SMS over DVMEGA + MMVDMHost  : 

I noticed that 4 attempts, it was able to send and receive 1. When checking the log and dashboard mutiples transmissions simultaneously which generates as a blockage observed, but seeing the log with "tail -f" there is nothing procesing.

The only way to recover is by rebooting the system.

Attach printscreen :  

![captura de pantalla 2016-05-17 a las 7 39 40 p m](https://cloud.githubusercontent.com/assets/19210807/15343306/a967bd78-1c69-11e6-9412-6205d238be8b.png)


![captura de pantalla 2016-05-17 a las 7 50 59 p m](https://cloud.githubusercontent.com/assets/19210807/15343318/c00e57bc-1c69-11e6-9406-c9a43608427f.png)

**Comment by dg9vh** [comment]
The problem with "transmitting" zombies is that SMS-transmissions does not send an end-of-transmission-logline so the algorithm in the Dashboard is thinking the one is still transmitting.

I am going to fix this in Dashboard.

**Comment by dg9vh** [comment]
Issue https://github.com/dg9vh/MMDVMHost-Dashboard/issues/14 would be closed with https://github.com/dg9vh/MMDVMHost-Dashboard/commit/44446bc6422e17c0b8ea53b7e524e95491277a24 so this display-part in Dashboard of issue would be resolved
