### ISSUE TITLE
network initiated DMR roaming beacon is not sent 

### ISSUE THREAD

**Issue by dk5ras** [g4klx/MMDVMHost#529]
As the subject says, it appears the network initiated roaming beacon has been killed some day - in earlier MMDVM times this used to work... This behavior kills roaming in BM...

Edit: When MMDVM is in idel mode without being in a mode hang period, it should transmit a network initiated beacon without triggering a new DMR mode hang period, just fire and forget - of course no beacon shall be transmitted when a different mode is actually used.

**Comment by phl0** [comment]
This should be a config option I guess? If hard-coded I think it would keep the MMDVM stuck in DMR mode?

**Comment by g4klx** [comment]
DMR beacons only operate when in Idle mode, and don't change the mode from Idle. The MMDVM used to accept beacon information from the network via the RPTSBKN network packet but that was changed to being a local timer a while ago.  This is particularly useful for BM networks that don't have roaming (eg UK BM) so you can enable it locally along with your friends in a local cluster for example.

There are other ways for networks to simulate beacons that breaks this behaviour, if I see any networks that break the beaconing rule I will be very unhappy indeed.

**Comment by g4klx** [comment]
I've reintroduced DMR network beacons. In the MMDVM.ini:

For timed beacons:

Beacons=1
BeaconInterval=60`
BeaconDuration=3

For network controlled beacons:

Beacons=1
BeaconDuration=3

The BeaconInterval parameter must be missing for the network option to work. The log will say which beacon mode is in use at startup time.

**Comment by g4klx** [comment]
Forgot to say, it's in the dmr_beacons branch for now. I can't even compile the code currently so you're welcome to have a play and fix any compile issues :-)

**Comment by phl0** [comment]
![Bildschirmfoto vom 2019-11-05 12-52-25](https://user-images.githubusercontent.com/7112907/68205657-21ade800-ffcb-11e9-890b-35cf27f5f6b7.png)

Fixed this issue with https://github.com/g4klx/MMDVMHost/commit/4be7ccd9246f045b6db93c3a0461fffd5bade0e3

**Comment by phl0** [comment]
I can confirm that the code compiles cleanly with the latest commits.
For tests I started 2 configs: one with local beacons and one with network based beacons. Both configurations at least pull the PTT and indicate DMR mode after either local beacon timer expired or BM network sends beacon command.

**Comment by shawnchain** [comment]
No one would tell the difference of config BeaconInterval/BeaconDuration without reading this thread or the source code in the future.

**Comment by g4klx** [comment]
That is true for a lot of the functionality in the code. That is why there are support groups. I have learnt log ago that people don't read documentation.

**Comment by shawnchain** [comment]
> That is true for a lot of the functionality in the code. That is why there are support groups. I have learnt log ago that people don't read documentation.

How about introduce a new  config item BeaconType and keeps the Beacons  for compatible.

**Comment by g4klx** [comment]
I wanted existing configurations to keep working as they did before. By doing it this way it is backwards compatible with people using the original network beacon configuration and people using the newer timer based. I upgraded the logging to show which one was in operation to remove any guesswork from it.

I did think about having a new configuration option while driving into work and decided to go this way. There are a lot of installed systems and I didn't want to break their systems.

**Comment by g4klx** [comment]
If this implementation works correctly, then I'd like to get it into the master branch.

**Comment by pjao** [comment]
Testing for a few days. Looks like it's working very well. 
Ready to apply to the master branch?

**Comment by g4klx** [comment]
Will do.
