### ISSUE TITLE
Why sending DT_TERMINATOR_WITH_LC packet twice on RF EOT received in DMRSlot

### ISSUE THREAD

**Issue by shawnchain** [g4klx/MMDVMHost#535]
I'm just curious why MMDVMHost send the DT_TERMINATOR_WITH_LC twice in DMRSlot.cpp 
https://github.com/g4klx/MMDVMHost/blob/de88f09b684f4aa531b37a24fcceccef6e968a98/DMRSlot.cpp#L340

Is this a by-design behavior for preventing UDP packet loss? Or defined in some protocol document ?

**Comment by g4klx** [comment]
There is no good reason. It needs changing to only one.

**Comment by g4klx** [comment]
Fixed in the master branch.

**Comment by shawnchain** [comment]
One more, for start call, In https://github.com/g4klx/MMDVMHost/blob/ed7f593e0715ae56c7edf3e9b1afbb8ca11156e5/DMRNetwork.cpp#L284

if `dataType == DT_VOICE_LC_HEADER`, the Homebrew packet will be sent twice.

**Comment by shawnchain** [comment]
Has been fixed in commit ed7f593
