### ISSUE TITLE
CDMRLookup::findWithName() not called when receiving network late entry

### ISSUE THREAD

**Issue by jg1uaa** [g4klx/MMDVMHost#554]
Normally, receive data starts with network voice header like this, and it can lookup operator name calling findWithName().

```
D: 2020-02-15 00:03:09.050 FindWithName =4S6CBD Chaminda Dissanayake
M: 2020-02-15 00:03:09.050 DMR Slot 2, received network voice header from 4S6CBD to TG 91
M: 2020-02-15 00:03:09.450 DMR Slot 2, received network end of voice transmission from 4S6CBD to TG 91, 0.5 seconds, 0% packet loss, BER: 0.0%
```

Today I found starting sequence with network late entry.  It cannot lookup operator name.

```
M: 2020-02-15 02:52:47.544 DMR Slot 2, received network late entry from KE8KHA to TG 91
M: 2020-02-15 02:52:48.064 DMR Talker Alias (Data Format 1, Received 6/22 char): 'KE8KHA'
M: 2020-02-15 02:52:48.064 DMR Slot 2, Embedded Talker Alias Header
M: 2020-02-15 02:52:48.064 0000:  04 00 6C 4B 45 38 4B 48 41                         *..lKE8KHA*
M: 2020-02-15 02:52:48.184 DMR Slot 2, received network end of voice transmission from KE8KHA to TG 91, 0.8 seconds, 0% packet loss, BER: 0.0%
```

I don't know who makes these changes and what is these differences.
I am testing my own enhancement (display user name and place to Surenoo LCD) version of MMDVMHost but calling findWithName() is same as original so I opened this issue.

postscript
I hope my pull request #551 will be merged.

**Comment by g4klx** [comment]
I have added findWithName to network late entry, I hope this fixes the bug.

**Comment by jg1uaa** [comment]
Sorry for no information to debug. I saw "late entry" from BrandMeister Master 2042 (NL, 213.222.29.197).  On the other hand, Master 2321 (AT, 94.199.173.125) didn't send late entry. I don't know why NL master works that and these differences.

Anyway I will test new fix later. Thanks.

**Comment by jg1uaa** [comment]
Tested with new code, I had to add more fix.
PR #555, fix for dataType == DT_VOICE_SYNC and m_netState == RS_NET_IDLE situation is needed.

(thanks to merging PR #551)

**Comment by g4klx** [comment]
Is it OK now?

**Comment by jg1uaa** [comment]
yes, two patches fixed the problem so I close this issue. thanks.
