### ISSUE TITLE
Modem.cpp: In member function ‘bool CModem

### ISSUE THREAD

**Issue by YV5OF** [g4klx/MMDVMHost#56]
Hi Team,

This version with the CW identifier, has an error in the modem module at compile : 

g++ -g -O3 -Wall -std=c++0x -c -o Modem.o Modem.cpp
Modem.cpp: In member function ‘bool CModem::sendCWId(const string&)’:
Modem.cpp:1035:45: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  return m_serial.write(buffer, length + 3U) == (length + 3U);

Raspberry B+ ( Jezzy OS version )

73!

**Comment by phl0** [comment]
Should be eliminated with commit 35632e025560daacac1508bad6e9e0614f2c2e72

**Comment by YV5OF** [comment]
Done my friend, working.

Thank,

73!
