### ISSUE TITLE
Overflow in the DMR slot RF queue .... and stop MMDVM !!!!

### ISSUE THREAD

**Issue by iw9grl** [g4klx/MMDVMHost#57]
Overflow in the DMR slot RF queue and after that, No reply from the modem for some time, resetting it ...................
Closing the MMDVM
Opening the MMDVM

In an infinite loop , the TX radio go keying continuosly .... please help me !

**Comment by g0wfv** [comment]
Any logs available?

**Comment by iw9grl** [comment]
Sorry, I have not any log due to new raspi installation

**Comment by s-s-s** [comment]
> Sorry, I have not any log due to new raspi installation

Try to look a log in /opt/MMDVMHost directory
