### ISSUE TITLE
MMDVMHost: Modem.cpp:166 Assertion `!port.empty()' failed

### ISSUE THREAD

**Issue by photochap** [g4klx/MMDVMHost#571]
Hello

On star service : /usr/local/sbin/mmdvmhost_service start

I'have an error :
MMDVMHost: Modem.cpp:166: CModem::CModem(const string&, bool, bool, bool, bool, unsigned int, unsigned int, bool, bool): Assertion `!port.empty()' failed.
Abandon
MMDVMHost started as PID 

I'm use an Raspberry Pi B+
With an MMDVM pog WK (see picture)
![s-l1600](https://user-images.githubusercontent.com/6159635/80274873-f5ebff00-86dd-11ea-9cec-d9176bd02c98.jpg)

>uname -a
Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

>cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

The MMDVM.ini
>[Modem]
Port=/dev/ttyAMA0 i use same with pi-star app
#Protocol=uart
#Address=0x22
TXInvert=1
RXInvert=1
PTTInvert=0
TXDelay=100
RXOffset=0
TXOffset=0
DMRDelay=0
RXLevel=50
TXLevel=50
RXDCOffset=0
TXDCOffset=0
RFLevel=100
CWIdTXLevel=50
D-StarTXLevel=50
DMRTXLevel=50
YSFTXLevel=50
P25TXLevel=50
NXDNTXLevel=50
POCSAGTXLevel=50
RSSIMappingFile=/usr/local/etc/RSSI.dat
Trace=0
Debug=0

[MMDVM.ini.txt](https://github.com/g4klx/MMDVMHost/files/4532623/MMDVM.ini.txt)

The process to install
>git clone
/usr/src/MMDVMHost
make -f Makefile.Pi

>cp /usr/src/MMDVMHost/MMDVMHost /usr/local/bin/
cp /usr/src/MMDVMHost/linux/init/mmdvmhost /etc/init.d
cp /usr/src/MMDVMHost/linux/systemd/mmdvmhost_service /usr/local/sbin
cp /usr/src/MMDVMHost/linux/systemd/mmdvmhost.* /lib/systemd/system
cp /usr/src/MMDVMHost/MMDVM.ini /etc/mmdvmhost/

>chmod 750 /usr/local/bin/MMDVMHost
chmod 750 /etc/init.d/mmdvmhost
chmod 700 /usr/local/sbin/mmdvmhost_service
chown root:mmdvm /etc/mmdvmhost/MMDVM.ini

>-rwxr-xr-x  1 root staff 5393028 avril 25 00:48 /usr/local/bin/MMDVMHost
-rwxr-xr-x 1 root root 3073 avril 25 00:26 /etc/init.d/mmdvmhost
-rwx------  1 root staff 3157 avril 25 00:13 /usr/local/sbin/mmdvmhost_service
-rwxr-xr-x 1 root root 290 avril 24 22:31 /lib/systemd/system/mmdvmhost.service
-rwxr-xr-x 1 root root  62 avril 24 22:31 /lib/systemd/system/mmdvmhost.timer
-rw-r--r-- 1 root mmdvm 3286 avril 25 00:20 /etc/mmdvmhost/MMDVM.ini

with this parameter when start mmdvmhost_service 
error : **This account is currently not available**.
>groupadd mmdvm
useradd mmdvm -g mmdvm -s /usr/sbin/nologin
usermod mmdvm -G dialout
in passwd user is

mmdvm: x :1001:1001::/home/mmdvm:/usr/sbin/nologin
-rwxr-xr-x 1 root root 5580 mai   17  2017 /usr/sbin/nologin

I do :
>adduser mmdvm

mmdvm: x :1001:1001:,,,:/home/mmdvm:/bin/bash

>mkdir -p /var/log/mmdvmhost
chown root:mmdvm /var/log/mmdvmhost
chmod 775 /var/log/mmdvmhost

drwxrwxr-x  2 root mmdvm   4096 avril 25 00:27 mmdvmhost

File /usr/local/sbin/mmdvmhost_service
>##################################
# Service Config
DAEMON=MMDVMHost
DAEMON_PATH=/usr/local/bin/
CONFIG=/etc/mmdvmhost
DAEMON_OPTS=$CONFIG
PGREP=/usr/bin/pgrep
KILL=/bin/kill
SLEEP=/bin/sleep
USER=mmdvm
GROUP=mmdvm
LOGDIR=/var/log/mmdvmhost
##################################

-rwxr-xr-x 1 root root 22028 mai   17  2018 /usr/bin/pgrep
-rwxr-xr-x 1 root root 22020 mai   17  2018 /bin/kill
-rwxr-xr-x 1 root root 26416 févr. 22  2017 /bin/sleep

>./DMRIDUpdate.sh
DMRIDPATH=/etc/mmdvmhost
DMRIDFILE=${DMRIDPATH}/DMRIds.dat

>systemctl daemon-reload

>systemctl enable mmdvmhost.service
Synchronizing state of mmdvmhost.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable mmdvmhost

>systemctl enable mmdvmhost.timer
Created symlink /etc/systemd/system/multi-user.target.wants/mmdvmhost.timer → /lib/systemd/system/mmdvmhost.timer.

>/usr/local/sbin/mmdvmhost_service start

**Comment by photochap** [comment]
On file Modem.cpp
m_port(port),
m_rxInvert(rxInvert),
m_txInvert(txInvert),
m_pttInvert(pttInvert),
m_txDelay(txDelay),
m_dmrDelay(dmrDelay),

on MMDVM.ini
Port=/dev/ttyAMA0
TXInvert=1
RXInvert=1
PTTInvert=0
TXDelay=100
DMRDelay=0

Change by 

on MMDVM.ini
port =/dev/ttyAMA0
rxInvert=1
txInvert=1
pttInvert=0
txDelay=100
dmrDelay=0

**Comment by g4klx** [comment]
This is a Pi-Star issue. Please raise it in the Pi-Star forum.


Sent from Yahoo Mail for iPhone


On Saturday, April 25, 2020, 09:31, Christophe CHAPPAT <notifications@github.com> wrote:




Hello

On star service : /usr/local/sbin/mmdvmhost_service start

I'have an error :
MMDVMHost: Modem.cpp:166: CModem::CModem(const string&, bool, bool, bool, bool, unsigned int, unsigned int, bool, bool): Assertion `!port.empty()' failed.
Abandon
MMDVMHost started as PID

I'm use an Raspberry Pi B+
With an MMDVM pog WK (see picture)



uname -a
Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux



cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"


The parameter with pi-star which work
Pi-Star - Digital Voice Dashboard - Expert Editor.pdf

The MMDVM.ini


[Modem]
Port=/dev/ttyAMA0 i use same with pi-star app
#Protocol=uart
#Address=0x22
TXInvert=1
RXInvert=1
PTTInvert=0
TXDelay=100
RXOffset=0
TXOffset=0
DMRDelay=0
RXLevel=50
TXLevel=50
RXDCOffset=0
TXDCOffset=0
RFLevel=100
CWIdTXLevel=50
D-StarTXLevel=50
DMRTXLevel=50
YSFTXLevel=50
P25TXLevel=50
NXDNTXLevel=50
POCSAGTXLevel=50
RSSIMappingFile=/usr/local/etc/RSSI.dat
Trace=0
Debug=0


MMDVM.ini.txt

The process to install


git clone
/usr/src/MMDVMHost
make -f Makefile.Pi



cp /usr/src/MMDVMHost/MMDVMHost /usr/local/bin/
cp /usr/src/MMDVMHost/linux/init/mmdvmhost /etc/init.d
cp /usr/src/MMDVMHost/linux/systemd/mmdvmhost_service /usr/local/sbin
cp /usr/src/MMDVMHost/linux/systemd/mmdvmhost.* /lib/systemd/system
cp /usr/src/MMDVMHost/MMDVM.ini /etc/mmdvmhost/



chmod 750 /usr/local/bin/MMDVMHost
chmod 750 /etc/init.d/mmdvmhost
chmod 700 /usr/local/sbin/mmdvmhost_service
chown root:mmdvm /etc/mmdvmhost/MMDVM.ini



-rwxr-xr-x 1 root staff 5393028 avril 25 00:48 /usr/local/bin/MMDVMHost
-rwxr-xr-x 1 root root 3073 avril 25 00:26 /etc/init.d/mmdvmhost
-rwx------ 1 root staff 3157 avril 25 00:13 /usr/local/sbin/mmdvmhost_service
-rwxr-xr-x 1 root root 290 avril 24 22:31 /lib/systemd/system/mmdvmhost.service
-rwxr-xr-x 1 root root 62 avril 24 22:31 /lib/systemd/system/mmdvmhost.timer
-rw-r--r-- 1 root mmdvm 3286 avril 25 00:20 /etc/mmdvmhost/MMDVM.ini


with this parameter when start mmdvmhost_service
error : This account is currently not available.


groupadd mmdvm
useradd mmdvm -g mmdvm -s /usr/sbin/nologin
usermod mmdvm -G dialout
in passwd user is


mmdvm: x :1001:1001::/home/mmdvm:/usr/sbin/nologin
-rwxr-xr-x 1 root root 5580 mai 17 2017 /usr/sbin/nologin

I do :


adduser mmdvm


mmdvm: x :1001:1001:,,,:/home/mmdvm:/bin/bash


mkdir -p /var/log/mmdvmhost
chown root:mmdvm /var/log/mmdvmhost
chmod 775 /var/log/mmdvmhost


drwxrwxr-x 2 root mmdvm 4096 avril 25 00:27 mmdvmhost

File /usr/local/sbin/mmdvmhost_service


##################################


Service Config

DAEMON=MMDVMHost
DAEMON_PATH=/usr/local/bin/
CONFIG=/etc/mmdvmhost
DAEMON_OPTS=$CONFIG
PGREP=/usr/bin/pgrep
KILL=/bin/kill
SLEEP=/bin/sleep
USER=mmdvm
GROUP=mmdvm
LOGDIR=/var/log/mmdvmhost
##################################

-rwxr-xr-x 1 root root 22028 mai 17 2018 /usr/bin/pgrep
-rwxr-xr-x 1 root root 22020 mai 17 2018 /bin/kill
-rwxr-xr-x 1 root root 26416 févr. 22 2017 /bin/sleep


./DMRIDUpdate.sh
DMRIDPATH=/etc/mmdvmhost
DMRIDFILE=${DMRIDPATH}/DMRIds.dat



systemctl daemon-reload



systemctl enable mmdvmhost.service
Synchronizing state of mmdvmhost.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable mmdvmhost



systemctl enable mmdvmhost.timer
Created symlink /etc/systemd/system/multi-user.target.wants/mmdvmhost.timer → /lib/systemd/system/mmdvmhost.timer.



/usr/local/sbin/mmdvmhost_service start

**Comment by photochap** [comment]
Hello
I'm not use pi-star. The file is juste for compare the MMDVM.ini
Thanks

**Comment by photochap** [comment]
On file MMDVM.ini
[Modem]
Port=/dev/ttyAMA0 i use same with pi-star app
#Protocol=uart
#Address=0x22
TXInvert=1
RXInvert=1
PTTInvert=0
TXDelay=100
RXOffset=0
TXOffset=0
DMRDelay=0
RXLevel=50
TXLevel=50
RXDCOffset=0
TXDCOffset=0
RFLevel=100
CWIdTXLevel=50
D-StarTXLevel=50
DMRTXLevel=50
YSFTXLevel=50
P25TXLevel=50
NXDNTXLevel=50
POCSAGTXLevel=50
RSSIMappingFile=/usr/local/etc/RSSI.dat
Trace=0
Debug=0
