### ISSUE TITLE
DMR IDs are not loaded anymore

### ISSUE THREAD

**Issue by yo6nam** [g4klx/MMDVMHost#583]
Since the last change to the DMR ID Lookup files, the IDs are not loaded :
**Loaded 1 IDs to lookup table - /mnt/ramdisk/DMRIds.dat**

**Comment by g4klx** [comment]
This looks like a Pi-Star issue. Please ask on an appropriate Pi-Star forum.

**Comment by yo6nam** [comment]
I'm not using Pi-Star. Clean OS (Stretch) and clean compile from this repo.

**Comment by g4klx** [comment]
Please ask on opendv@groups.io which is the best place for support.

    On Saturday, 9 May 2020, 15:06:09 BST, yo6nam <notifications@github.com> wrote:  
 
 


I'm not using Pi-Star. Clean OS (Stretch) and clean compile from this repo.
