### ISSUE TITLE
Version 20200518 segfaults on TRX

### ISSUE THREAD

**Issue by cfenell** [g4klx/MMDVMHost#597]
Dear all

Yesterday May 31 I updated MMDVM repeater SK2RGJ to the latest commit, version 20200518.
It starts but segfaults on transmission. At first I thought it was related to an empty DMRid file but I fixed that issue.  
I rolled back to the commit from 20200426 and it works again.

System: Raspberry Pi 3, raspbian stretch. This may have to be updated to buster.

Best 73s de Fredrik SM2YHP

**Comment by iddq** [comment]
can you please create a core dump?

**Comment by ik4nzd** [comment]
I found that the CTCSS Threshold values go up to 255; from 256 it restarts from 0.
Unfortunately, in my opinion, the recognition of the CTCSS is not yet at its best; with low threshold values the system also activates with different subtones.
As the threshold rises, the system becomes more precise on the CTCSS frequencies, but - if too high - it may also not let some radios pass.To solve the situation 85%, I connected the COS contact on SQL, and now the unwanted hooks have reducedHi

**Comment by cfenell** [comment]
Hi, sorry for the late reply!
Today I have compiled the latest version (20200608) and also made sure to add missing entries to MMDVM.ini according to the template in the git source. Whichever it was it works again so I will close this issue.
