### ISSUE TITLE
UserDB display for Nextion

### ISSUE THREAD

**Issue by jg1uaa** [g4klx/MMDVMHost#603]
Now I am started experiment of UserDB display code for Nextion LCD.
Test code is at my repo. For details, please see commit message of https://github.com/jg1uaa/MMDVMHost/commit/b301f28c2eabf51c209357aa654e9925ea321a4b

**Comment by jg1uaa** [comment]
@on7lds I think this extension affects to your NextionDriver.
I am trying to keep compatibility with old configuration and software but my experimental code needs some discussion to send pull request.
Almost all is written in my commit message, I cannot judge assignment of Nextion object and status (event) is suitable for your application. Please give me your opinion.

**Comment by jg1uaa** [comment]
I will move testing Nextion.cpp code from my master branch to another branch.
Now creating new branch and merging current code.
testing Nextion.cpp and commit comment is not available temporally .

**Comment by jg1uaa** [comment]
Now testing Nextion.cpp is moved at my MMDVMHost repo, nextion-userdb branch. https://github.com/jg1uaa/MMDVMHost/tree/nextion-userdb

**Comment by jg1uaa** [comment]
Well, Nextion has its own culture provided by NextionDriver. We have to do for other (not userDB supported) display.

**Comment by on7lds** [comment]
Somehow I missed this issue, I just saw it now, when you closed it.

It seems to me you are complicating things, by changing the goal of the 'ScreenLayout' setting by using it as a bit mask.
It wil make thing very difficult for a lot of users.
It could be, indeed, interesting to other than Nextion displays to have some extra data. 
But why not just take another ScreenLayout number, which will add userdbdata. Which then, in turn can be procesed (or not) in the corresponding display driver files (OLED.cpp, LCDproc.cpp, ... etc)

**Comment by jg1uaa** [comment]
The advantage of using Nextion Display is separating HMI design from program code.
So, coders are required to add extension from designers easily.
Previous code was too difficult to add new feature, so I disassembled already-existing designs into bitmap and reassmbled as "feature set" (see feature_set in Nextion.cpp).
If you think using bitmaps in ScreenLayout is ugly, how about this?

ScreenLayout >= 0 uses conventional display style (feature set), no bitmap.
ScreenLayout < 0 disables using feature set, use bitmap by another property (ScreenFeature?)

At least current code has backward compatibility, keeping unchange is also a choice.
