### ISSUE TITLE
A Question or Request ( Not Issues )

### ISSUE THREAD

**Issue by YV5OF** [g4klx/MMDVMHost#62]
Hi Team,

I am not sure if, there are possibilities to program or configure for MMDVMHost operate to DMR (BrandMeister):

- Duplex mode 100%.
- Both operate slot (Slot 1 and Slot 2) transparently

Thank,

73!

**Comment by g4klx** [comment]
This is exactly what the MMDVMHost and the MMDVM firmware do!
