### ISSUE TITLE
missing file samplerate.h

### ISSUE THREAD

**Issue by iddq** [g4klx/MMDVMHost#625]
https://github.com/g4klx/MMDVMHost/blob/8a6f14e6e61b2a775bb7b305ba249dabbc253d15/FMNetwork.h#L26

**Comment by g4klx** [comment]
You need to install libsamplerate and its development files.


Sent from Yahoo Mail for iPhone


On Saturday, August 8, 2020, 09:49, Gabor <notifications@github.com> wrote:




https://github.com/g4klx/MMDVMHost/blob/8a6f14e6e61b2a775bb7b305ba249dabbc253d15/FMNetwork.h#L26

**Comment by iddq** [comment]
Thanks
