### ISSUE TITLE
FMNetwork.h:61:2: error: ‘SRC_STATE’ does not name a type;

### ISSUE THREAD

**Issue by iddq** [g4klx/MMDVMHost#626]
https://github.com/g4klx/MMDVMHost/blob/8a6f14e6e61b2a775bb7b305ba249dabbc253d15/FMNetwork.h#L61

make
c++ -g -O3 -Wall -std=c++0x -pthread -c -o FMControl.o FMControl.cpp
In file included from FMControl.h:22,
                 from FMControl.cpp:19:
FMNetwork.h:61:2: error: ‘SRC_STATE’ does not name a type; did you mean ‘SIOCGSTAMP’?
  SRC_STATE*     m_incoming;
  ^~~~~~~~~
  SIOCGSTAMP
FMNetwork.h:62:2: error: ‘SRC_STATE’ does not name a type; did you mean ‘SIOCGSTAMP’?
  SRC_STATE*     m_outgoing;
  ^~~~~~~~~
  SIOCGSTAMP
make: *** [Makefile:36: FMControl.o] Error 1

**Comment by g4klx** [comment]
That's very odd. Can you add the word "struct" in front of SRC_STATE and try again.
Can you ensure that libsamplerate.h is the correct file?

    On Saturday, 8 August 2020, 21:02:54 BST, Gabor <notifications@github.com> wrote:  
 
 


https://github.com/g4klx/MMDVMHost/blob/8a6f14e6e61b2a775bb7b305ba249dabbc253d15/FMNetwork.h#L61

make
c++ -g -O3 -Wall -std=c++0x -pthread -c -o FMControl.o FMControl.cpp
In file included from FMControl.h:22,
from FMControl.cpp:19:
FMNetwork.h:61:2: error: ‘SRC_STATE’ does not name a type; did you mean ‘SIOCGSTAMP’?
SRC_STATE* m_incoming;
^~~~~~~~~
SIOCGSTAMP
FMNetwork.h:62:2: error: ‘SRC_STATE’ does not name a type; did you mean ‘SIOCGSTAMP’?
SRC_STATE* m_outgoing;
^~~~~~~~~
SIOCGSTAMP
make: *** [Makefile:36: FMControl.o] Error 1

**Comment by iddq** [comment]
sorry, it was my mistake. #include <samplerate.h> was commented out.
