### ISSUE TITLE
Frequency resolution reported to t30 t32 (nextion.cpp) 

### ISSUE THREAD

**Issue by vk7hse** [g4klx/MMDVMHost#632]
Hi Jonathan,

I have a question about the frequency resolution being reported in nextion.cpp

```
::sprintf(command, "t30.txt=\"%3.4f\"",m_fl_rxFrequency);  // RX freq
		sendCommand(command);
		sendCommandAction(20U);
		
		::sprintf(command, "t32.txt=\"%3.4f\"",m_fl_txFrequency);  // TX freq
		sendCommand(command);
		sendCommandAction(21U);
```
Is the following "%3.4f" responsible for limiting the resolution to 4 decimal places?

So what I mean is that as it stands the frequency the Nextion screen will display is for example 438.8000MHz but if you are using a frequency that is say 438.80125MHz it will be rounded up to the nearest whole number, so 438.8013MHz. If "%3.4f" was altered to say "%3.5f" would this then resolve to the 5th decimal place?

Now if I am on the correct path, would it be possible to have the frequency being reported adjusted from the 4th decimal to the 5th? (I realise that this would become a separate feature request) 

I'm most likely in the minority, but I do use frequencies that fall on the 6.25KHz spacing! (yes most people would just stick to either 12.5KHz or 25KHz frequency step)

**Comment by on7lds** [comment]
Sadly, this wil probably to work since float has only a precision of 7.225 decimal digits
(https://en.wikipedia.org/wiki/Single-precision_floating-point_format)
so the chosen format (%3.4f) is the maximum achievable.
It will require some more programming :-)

**Comment by on7lds** [comment]
It was only a little bit of work, so I did a PR to solve this.
You can already play with it if you use https://github.com/on7lds/MMDVMHost/tree/dev

**Comment by vk7hse** [comment]
> It was only a little bit of work, so I did a PR to solve this.
> You can already play with it if you use https://github.com/on7lds/MMDVMHost/tree/dev

Awesome! I'll give it a go on one of my hotspots...

**Comment by vk7hse** [comment]
As there was a patch provided by ON7LDS I'm going to close this thread, however if the patch provides any future issues then by all means reopen!
