### ISSUE TITLE
M17 project support?

### ISSUE THREAD

**Issue by jg1uaa** [g4klx/MMDVMHost#637]
I heard that there is M17, that builds their own digital-voice transceiver project. https://m17project.org/
Draft specification is ready at https://m17-protocol-specification.readthedocs.io/_/downloads/en/latest/pdf/ and they looks using ADF7021 (same as MMDVM) for developing.
What should we do for coming new digital protocol?

**Comment by g4klx** [comment]
I looked at M17 about a year ago and was very unimpressed with the radio protocol design, it was extremely bad. It was obvious that no-one with any experience of digital voice had designed it. I raised some specific technical issues and was told that they weren't important. Unless things have changed, then I will not support it.

**Comment by picchiosat** [comment]
Hi Jonathan, are you planning to build a "client" like NXDN or YSF for M17 too?

**Comment by g4klx** [comment]
At some stage. It’s too early so far. I don’t know if the host support for M17 is correct yet.


Sent from Yahoo Mail for iPhone


On Monday, October 26, 2020, 12:51, Roby <notifications@github.com> wrote:




Hi Jonathan, are you planning to build a "client" like NXDN or YSF for M17 too?

**Comment by g4klx** [comment]
As you can see the MMDVM and MMDVM Host now support M17. I am sure its on-air interface will change again, but it follows the specification as of now.
