### ISSUE TITLE
No master connection

### ISSUE THREAD

**Issue by f1iwq2** [g4klx/MMDVMHost#653]
Hello
With the new commits, The MMDVMHost don't connect to the master anymore.
I downgrade back to the commit #f71c8ce (sept 5) and this version connects to the master.
( #ff19408 oct 13 don't connect neither).... Or maybe I missed something :/

**Comment by dk5ras** [comment]
See https://github.com/g4klx/MMDVMHost/issues/651

**Comment by f1iwq2** [comment]
Thks. Both MMDVMHost and DMRGateway must run.
