### ISSUE TITLE
MMDVMHost can't connect any master anymore

### ISSUE THREAD

**Issue by f1rmb** [g4klx/MMDVMHost#655]
Hi Jonathan,

  I got some reports from some guys who experienced connection problems to BM.

After looking closer, I just notice that MMDVMHost doesn't connect BM of DMR+ masters anymore.
I never had any problem because I'm using DMRGateway all the time, but does MMDVMHost now requires DMRGateway for accessing to any DMR network ?

Cheers.
...
Daniel

**Comment by iddq** [comment]
can't connect to brandmaister from commit 66a17f4849ac92f6e1e82c51bc5851162db4b291    Simplify the Host to DMR Gateway protocol.

Is DMRC command supported by BM?

before this commit the first command to DMR master server was RPTL.

**Comment by f1rmb** [comment]
Okay, It's what I saw reviewing git log diffs.

Anyway I set DMRGateway as mandatory when using DMR network in my Pi-Star fork.

Thanks.
...
Daniel

**Comment by iddq** [comment]
Can you please help me in DMRGateway configuration?

I got M: 2020-11-20 19:56:50.846 MMDVM packet received from an invalid source

[General]
Timeout=10
# RFTimeout=10
# NetTimeout=7
RptAddress=127.0.0.1
RptPort=62032
LocalAddress=127.0.0.1
LocalPort=62031

[DMR Network 1]
Enabled=1
Name=BM
Address=master.brandmeister.hu
Port=62031

**Comment by iddq** [comment]
```
/*
        if (!CUDPSocket::match(m_rptAddr, address)) {
                LogMessage("MMDVM packet received from an invalid source");
                return;
        }
*/
```

I commented out this part but it is still not working.

DMRgateway is able to connect to BM but MMDVMHost remains unconnected just sending the DMRC commands again and again.

**Comment by f1rmb** [comment]
I think you missed what I wrote above (and it's just an assumption since Jonathan didn't replied yet), it looks like MMDVMHost **requires** DMRGateway if you need DMR Network. It's quite logic, as this rule applies for the other modes (YSF/P25 and NXDN), and it avoids to have the same code in both MMDVMHost and DMRGateway.

My 2 cents.

Cheers.
...
Daniel

**Comment by iddq** [comment]
I'm trying to connect through DMRGateway...

**Comment by iddq** [comment]
I had to set Local in DMR Network section.

```
[DMR Network]
Local=62032
```

**Comment by zarya** [comment]
Just see #651

**Comment by f1rmb** [comment]
@zarya thanks for the link. I guess the README.md needs an update ;-)
So, yeah, it follows the whole MMDVMHost logic, one *Gateway for every mode, and MMDVMHost between RF and these gateway softwares.

I'm closing this non-issue.
