### ISSUE TITLE
Problems connecting to brandmeister network

### ISSUE THREAD

**Issue by dl1hrc** [g4klx/MMDVMHost#659]
Hi,
I've compiled and installed the MMDVMHost version 20201031 git #1b0caaa and can not connect to the brandmeister network. No error message is shown. Some configuration parameters from the [Info] section are not displayed in the log. 

MMDVM.ini:

[General]
Callsign=DL1XXX
Id=1234567
Timeout=180
Duplex=0
RFModeHang=10
NetModeHang=3
Display=OLED
Daemon=0

[Info]
RXFrequency=433625000
TXFrequency=433625000
Power=1
Height=20
Location=home
Latitude=50.3
Longitude=10.1
Description=mydescription
URL=mywebsite

[DMR]
Id=1234567
Enable=1
Beacons=0
BeaconInterval=60
BeaconDuration=3
ColorCode=1
SelfOnly=0
EmbeddedLCOnly=1
DumpTAData=0
CallHang=3
TXHang=4
OVCM=0

[DMR Network]
Enable=1
Address=master.bm262.de
Port=62031
Password=passw0rd
Jitter=360
Slot1=0
Slot2=1
Debug=1

Log:
IMMDVMHost version 20201031 git #1b0caaa
root@raspberrypi:/etc# MMDVMHost
I: 2020-12-03 13:06:49.117 This software is for use on amateur radio networks only,
I: 2020-12-03 13:06:49.121 it is to be used for educational purposes only. Its use on
I: 2020-12-03 13:06:49.123 commercial networks is strictly prohibited.
I: 2020-12-03 13:06:49.125 Copyright(C) 2015-2020 by Jonathan Naylor, G4KLX and others
M: 2020-12-03 13:06:49.127 MMDVMHost-20201031 is starting
M: 2020-12-03 13:06:49.128 Built 09:43:44 Dec  2 2020 (GitID #1b0caaa)
I: 2020-12-03 13:06:49.130 General Parameters
I: 2020-12-03 13:06:49.130     Callsign: DL1XXX
I: 2020-12-03 13:06:49.132     Id: xxxxxxxx
I: 2020-12-03 13:06:49.133     Duplex: no
I: 2020-12-03 13:06:49.134     Timeout: 180s
I: 2020-12-03 13:06:49.135     D-Star: disabled
I: 2020-12-03 13:06:49.136     DMR: enabled
I: 2020-12-03 13:06:49.137     YSF: disabled
I: 2020-12-03 13:06:49.138     P25: disabled
I: 2020-12-03 13:06:49.139     NXDN: disabled
I: 2020-12-03 13:06:49.140     POCSAG: disabled
I: 2020-12-03 13:06:49.141     FM: disabled
I: 2020-12-03 13:06:49.145 Modem Parameters
I: 2020-12-03 13:06:49.149     Port: /dev/ttyAMA0
I: 2020-12-03 13:06:49.151     Protocol: uart
I: 2020-12-03 13:06:49.151     RX Invert: no
I: 2020-12-03 13:06:49.151     TX Invert: yes
I: 2020-12-03 13:06:49.151     PTT Invert: no
I: 2020-12-03 13:06:49.151     TX Delay: 100ms
I: 2020-12-03 13:06:49.152     RX Offset: 0Hz
I: 2020-12-03 13:06:49.152     TX Offset: 0Hz
I: 2020-12-03 13:06:49.152     RX DC Offset: 0
I: 2020-12-03 13:06:49.152     TX DC Offset: 0
I: 2020-12-03 13:06:49.152     RF Level: 100.0%
I: 2020-12-03 13:06:49.152     DMR Delay: 0 (0.0ms)
I: 2020-12-03 13:06:49.153     RX Level: 100.0%
I: 2020-12-03 13:06:49.153     CW Id TX Level: 52.0%
I: 2020-12-03 13:06:49.153     D-Star TX Level: 52.0%
I: 2020-12-03 13:06:49.153     DMR TX Level: 50.0%
I: 2020-12-03 13:06:49.153     YSF TX Level: 52.0%
I: 2020-12-03 13:06:49.153     P25 TX Level: 52.0%
I: 2020-12-03 13:06:49.159     NXDN TX Level: 52.0%
I: 2020-12-03 13:06:49.161     POCSAG TX Level: 50.0%
I: 2020-12-03 13:06:49.164     FM TX Level: 50.0%
I: 2020-12-03 13:06:49.165     TX Frequency: 433625000Hz (433625000Hz)
I: 2020-12-03 13:06:49.166     Use COS as Lockout: no
M: 2020-12-03 13:06:49.167 Opening the MMDVM
I: 2020-12-03 13:06:51.182 MMDVM protocol version: 1, description: MMDVM_HS_Hat-v1.4.6 20180720 14.7456MHz ADF7021 FW by CA6JAU GitID #10c725c
I: 2020-12-03 13:06:51.202 Display Parameters
I: 2020-12-03 13:06:51.203     Type: OLED
W: 2020-12-03 13:06:51.203 No valid display found, disabling
I: 2020-12-03 13:06:51.203 DMR Network Parameters
I: 2020-12-03 13:06:51.203     Address: master.bm262.de
I: 2020-12-03 13:06:51.203     Port: 62031
I: 2020-12-03 13:06:51.203     Local: random
I: 2020-12-03 13:06:51.204     Jitter: 360ms
I: 2020-12-03 13:06:51.204     Slot 1: disabled
I: 2020-12-03 13:06:51.204     Slot 2: enabled
I: 2020-12-03 13:06:51.204     Mode Hang: 3s
I: 2020-12-03 13:06:51.262 Info Parameters
I: 2020-12-03 13:06:51.265     Callsign: DL1xxx
I: 2020-12-03 13:06:51.267     RX Frequency: 433625000Hz
I: 2020-12-03 13:06:51.269     TX Frequency: 433625000Hz
I: 2020-12-03 13:06:51.277     Power: 1W
M: 2020-12-03 13:06:51.277 DMR, Opening DMR Network
I: 2020-12-03 13:06:51.279 RSSI
I: 2020-12-03 13:06:51.281     Mapping File: /etc/RSSI.dat
I: 2020-12-03 13:06:51.282 Loaded 3 RSSI data mapping points from /etc/RSSI.dat
I: 2020-12-03 13:06:51.283 DMR Id Lookups
I: 2020-12-03 13:06:51.284     File: /etc/DMRIds.dat
I: 2020-12-03 13:06:51.285     Reload: 24 hours
I: 2020-12-03 13:07:03.348 Loaded 145242 IDs to lookup table - /etc/DMRIds.dat
I: 2020-12-03 13:07:03.361 DMR RF Parameters
I: 2020-12-03 13:07:03.363     Id: 1234567
I: 2020-12-03 13:07:03.365     Color Code: 1
I: 2020-12-03 13:07:03.367     Self Only: no
I: 2020-12-03 13:07:03.372     Embedded LC Only: yes
I: 2020-12-03 13:07:03.373     Dump Talker Alias Data: no
I: 2020-12-03 13:07:03.375     Prefixes: 0
I: 2020-12-03 13:07:03.376     Call Hang: 3s
I: 2020-12-03 13:07:03.378     TX Hang: 3s
I: 2020-12-03 13:07:03.369 Started the DMR Id lookup reload thread
I: 2020-12-03 13:07:03.381     Mode Hang: 10s
I: 2020-12-03 13:07:03.382     OVCM: off
I: 2020-12-03 13:07:03.384     DMR Roaming Beacons Type: off
M: 2020-12-03 13:07:03.385 MMDVMHost-20201031 is running

73s Adi / DL1HRC

**Comment by SA7BNT** [comment]
> Hi,
> I've compiled and installed the MMDVMHost version 20201031 git #1b0caaa and can not connect to the brandmeister network. No error message is shown. Some configuration parameters from the [Info] section are not displayed in the log.
> 
> MMDVM.ini:
> 
> [General]
> Callsign=DL1XXX
> Id=1234567
> Timeout=180
> Duplex=0
> RFModeHang=10
> NetModeHang=3
> Display=OLED
> Daemon=0
> 
> [Info]
> RXFrequency=433625000
> TXFrequency=433625000
> Power=1
> Height=20
> Location=home
> Latitude=50.3
> Longitude=10.1
> Description=mydescription
> URL=mywebsite
> 
> [DMR]
> Id=1234567
> Enable=1
> Beacons=0
> BeaconInterval=60
> BeaconDuration=3
> ColorCode=1
> SelfOnly=0
> EmbeddedLCOnly=1
> DumpTAData=0
> CallHang=3
> TXHang=4
> OVCM=0
> 
> [DMR Network]
> Enable=1
> Address=master.bm262.de
> Port=62031
> Password=passw0rd
> Jitter=360
> Slot1=0
> Slot2=1
> Debug=1
> 
> Log:
> IMMDVMHost version 20201031 git #1b0caaa
> root@raspberrypi:/etc# MMDVMHost
> I: 2020-12-03 13:06:49.117 This software is for use on amateur radio networks only,
> I: 2020-12-03 13:06:49.121 it is to be used for educational purposes only. Its use on
> I: 2020-12-03 13:06:49.123 commercial networks is strictly prohibited.
> I: 2020-12-03 13:06:49.125 Copyright(C) 2015-2020 by Jonathan Naylor, G4KLX and others
> M: 2020-12-03 13:06:49.127 MMDVMHost-20201031 is starting
> M: 2020-12-03 13:06:49.128 Built 09:43:44 Dec 2 2020 (GitID #1b0caaa)
> I: 2020-12-03 13:06:49.130 General Parameters
> I: 2020-12-03 13:06:49.130 Callsign: DL1XXX
> I: 2020-12-03 13:06:49.132 Id: xxxxxxxx
> I: 2020-12-03 13:06:49.133 Duplex: no
> I: 2020-12-03 13:06:49.134 Timeout: 180s
> I: 2020-12-03 13:06:49.135 D-Star: disabled
> I: 2020-12-03 13:06:49.136 DMR: enabled
> I: 2020-12-03 13:06:49.137 YSF: disabled
> I: 2020-12-03 13:06:49.138 P25: disabled
> I: 2020-12-03 13:06:49.139 NXDN: disabled
> I: 2020-12-03 13:06:49.140 POCSAG: disabled
> I: 2020-12-03 13:06:49.141 FM: disabled
> I: 2020-12-03 13:06:49.145 Modem Parameters
> I: 2020-12-03 13:06:49.149 Port: /dev/ttyAMA0
> I: 2020-12-03 13:06:49.151 Protocol: uart
> I: 2020-12-03 13:06:49.151 RX Invert: no
> I: 2020-12-03 13:06:49.151 TX Invert: yes
> I: 2020-12-03 13:06:49.151 PTT Invert: no
> I: 2020-12-03 13:06:49.151 TX Delay: 100ms
> I: 2020-12-03 13:06:49.152 RX Offset: 0Hz
> I: 2020-12-03 13:06:49.152 TX Offset: 0Hz
> I: 2020-12-03 13:06:49.152 RX DC Offset: 0
> I: 2020-12-03 13:06:49.152 TX DC Offset: 0
> I: 2020-12-03 13:06:49.152 RF Level: 100.0%
> I: 2020-12-03 13:06:49.152 DMR Delay: 0 (0.0ms)
> I: 2020-12-03 13:06:49.153 RX Level: 100.0%
> I: 2020-12-03 13:06:49.153 CW Id TX Level: 52.0%
> I: 2020-12-03 13:06:49.153 D-Star TX Level: 52.0%
> I: 2020-12-03 13:06:49.153 DMR TX Level: 50.0%
> I: 2020-12-03 13:06:49.153 YSF TX Level: 52.0%
> I: 2020-12-03 13:06:49.153 P25 TX Level: 52.0%
> I: 2020-12-03 13:06:49.159 NXDN TX Level: 52.0%
> I: 2020-12-03 13:06:49.161 POCSAG TX Level: 50.0%
> I: 2020-12-03 13:06:49.164 FM TX Level: 50.0%
> I: 2020-12-03 13:06:49.165 TX Frequency: 433625000Hz (433625000Hz)
> I: 2020-12-03 13:06:49.166 Use COS as Lockout: no
> M: 2020-12-03 13:06:49.167 Opening the MMDVM
> I: 2020-12-03 13:06:51.182 MMDVM protocol version: 1, description: MMDVM_HS_Hat-v1.4.6 20180720 14.7456MHz ADF7021 FW by CA6JAU GitID #10c725c
> I: 2020-12-03 13:06:51.202 Display Parameters
> I: 2020-12-03 13:06:51.203 Type: OLED
> W: 2020-12-03 13:06:51.203 No valid display found, disabling
> I: 2020-12-03 13:06:51.203 DMR Network Parameters
> I: 2020-12-03 13:06:51.203 Address: master.bm262.de
> I: 2020-12-03 13:06:51.203 Port: 62031
> I: 2020-12-03 13:06:51.203 Local: random
> I: 2020-12-03 13:06:51.204 Jitter: 360ms
> I: 2020-12-03 13:06:51.204 Slot 1: disabled
> I: 2020-12-03 13:06:51.204 Slot 2: enabled
> I: 2020-12-03 13:06:51.204 Mode Hang: 3s
> I: 2020-12-03 13:06:51.262 Info Parameters
> I: 2020-12-03 13:06:51.265 Callsign: DL1xxx
> I: 2020-12-03 13:06:51.267 RX Frequency: 433625000Hz
> I: 2020-12-03 13:06:51.269 TX Frequency: 433625000Hz
> I: 2020-12-03 13:06:51.277 Power: 1W
> M: 2020-12-03 13:06:51.277 DMR, Opening DMR Network
> I: 2020-12-03 13:06:51.279 RSSI
> I: 2020-12-03 13:06:51.281 Mapping File: /etc/RSSI.dat
> I: 2020-12-03 13:06:51.282 Loaded 3 RSSI data mapping points from /etc/RSSI.dat
> I: 2020-12-03 13:06:51.283 DMR Id Lookups
> I: 2020-12-03 13:06:51.284 File: /etc/DMRIds.dat
> I: 2020-12-03 13:06:51.285 Reload: 24 hours
> I: 2020-12-03 13:07:03.348 Loaded 145242 IDs to lookup table - /etc/DMRIds.dat
> I: 2020-12-03 13:07:03.361 DMR RF Parameters
> I: 2020-12-03 13:07:03.363 Id: 1234567
> I: 2020-12-03 13:07:03.365 Color Code: 1
> I: 2020-12-03 13:07:03.367 Self Only: no
> I: 2020-12-03 13:07:03.372 Embedded LC Only: yes
> I: 2020-12-03 13:07:03.373 Dump Talker Alias Data: no
> I: 2020-12-03 13:07:03.375 Prefixes: 0
> I: 2020-12-03 13:07:03.376 Call Hang: 3s
> I: 2020-12-03 13:07:03.378 TX Hang: 3s
> I: 2020-12-03 13:07:03.369 Started the DMR Id lookup reload thread
> I: 2020-12-03 13:07:03.381 Mode Hang: 10s
> I: 2020-12-03 13:07:03.382 OVCM: off
> I: 2020-12-03 13:07:03.384 DMR Roaming Beacons Type: off
> M: 2020-12-03 13:07:03.385 MMDVMHost-20201031 is running
> 
> 73s Adi / DL1HRC

Hey Adi,

https://github.com/g4klx/MMDVMHost/issues/651

73 Tim SA7BNT

**Comment by iddq** [comment]
put Enable=1 into Info section

**Comment by dl1hrc** [comment]
ok, tnx
