### ISSUE TITLE
DMRIDUpdateBM.sh

### ISSUE THREAD

**Issue by iddq** [g4klx/MMDVMHost#661]
sed command makes the DB wrong

I: 2020-12-06 09:05:01.225 Loaded 1 IDs to lookup table - DMRIds.dat

debian linux.

it looks like works well without sed

**Comment by s-s-s** [comment]
The file format has changed 
https://github.com/g4klx/MMDVMHost/issues/672

**Comment by s-s-s** [comment]
fixed
https://github.com/g4klx/MMDVMHost/pull/674

**Comment by randybuildsthings** [comment]
@iddq can you confirm that this is now fixed on your end?

**Comment by iddq** [comment]
it's ok. you could use RESTARTCOMMAND="./RemoteCommand 7642 reload"
