### ISSUE TITLE
New MMDVMHost 12/06/2020 problem connect brandmeister

### ISSUE THREAD

**Issue by hp3icc** [g4klx/MMDVMHost#662]
yesterday, and installed the new compilation of mmdvmhost, using the same command lines and configurations that always worked perfectly, this new version of mmdvmhost in dmr network, you must select if it is direct or gateway, following the instructions I put Direct and I enable the password to connect hotspot to brandmeister but it does not advance from sending configuration.

Could someone inform me the correct way to connect brandmeister with this new version of mmdvmhost

[DMR]
Enable=1
Beacons=0
BeaconInterval=60
BeaconDuration=3
ColorCode=1
SelfOnly=0
EmbeddedLCOnly=0
DumpTAData=1
# Prefixes=234,235
# Slot1TGWhiteList=
# Slot2TGWhiteList=
CallHang=3
TXHang=4
# ModeHang=10
# OVCM Values, 0=off, 1=rx_on, 2=tx_on, 3=both_on
# OVCM=0

[DMR Network]
Enable=1
# Type may be either 'Direct' or 'Gateway'. When Direct you must provide the Ma$
# address as well as the Password, and for DMR+, Options also.
Type=Direct
Address=74.91.114.19
Port=62031
#Local=62032
Password=**********
Jitter=360
Slot1=1
Slot2=1
# Options=
# ModeHang=3
Debug=0

 ./MMDVMHost MMDVM.ini

M: 2020-12-07 15:23:57.234 MMDVMHost-20201206 is running
D: 2020-12-07 15:24:07.342 DMR, Sending authorisation
D: 2020-12-07 15:24:07.461 DMR, Sending configuration
E: 2020-12-07 15:25:07.474 DMR, Connection to the master has timed out, retrying connection
M: 2020-12-07 15:25:07.475 Closing DMR Network
M: 2020-12-07 15:25:07.475 Opening DMR Network

**Comment by SA7BNT** [comment]
https://github.com/g4klx/MMDVMHost/issues/659

**Comment by do1vm** [comment]
Same here with working config and new Parameters for Type=Direct

M: 2020-12-08 17:01:49.641 MMDVMHost-20201206 is running
E: 2020-12-08 17:02:59.743 DMR, Connection to the master has timed out, retrying connection
M: 2020-12-08 17:02:59.743 Closing DMR Network
M: 2020-12-08 17:02:59.743 Opening DMR Network

MMDVMHost-20201208 has this error too.....

**Comment by g4klx** [comment]
Please do another pull.


Sent from Yahoo Mail for iPhone


On Tuesday, December 8, 2020, 21:02, do1vm <notifications@github.com> wrote:




Same here with working config and new Parameters for Type=Direct

M: 2020-12-08 17:01:49.641 MMDVMHost-20201206 is running
E: 2020-12-08 17:02:59.743 DMR, Connection to the master has timed out, retrying connection
M: 2020-12-08 17:02:59.743 Closing DMR Network
M: 2020-12-08 17:02:59.743 Opening DMR Network

MMDVMHost-20201208 has this error too.....

**Comment by do1vm** [comment]
Fresh compiled. Same Version and same Error.

M: 2020-12-08 22:10:50.297 MMDVMHost-20201208 is running
E: 2020-12-08 22:12:00.395 DMR, Connection to the master has timed out, retrying connection
M: 2020-12-08 22:12:00.395 Closing DMR Network

**Comment by sp4xkb** [comment]
I have the same problem.
DMR is not connected to the Brand Meister and DMR + networks.
-Version 20201208
- TEENSY 3.5 modem version 20200901
- MMDVM.ini newest and set to Type=Direct

works on the current ubuntu system

**Comment by g4klx** [comment]
And another pull and test please!
    On Tuesday, 8 December 2020, 22:13:10 GMT, do1vm <notifications@github.com> wrote:  
 
 


Fresh compiled. Same Version and same Error.

M: 2020-12-08 22:10:50.297 MMDVMHost-20201208 is running
E: 2020-12-08 22:12:00.395 DMR, Connection to the master has timed out, retrying connection
M: 2020-12-08 22:12:00.395 Closing DMR Network

**Comment by do1vm** [comment]
Yes Sir! Wait a Moment :-)

**Comment by do1vm** [comment]
M: 2020-12-09 10:12:27.878 MMDVMHost-20201209 is running
M: 2020-12-09 10:12:37.991 DMR, Logged into the master successfully

Up and running! TNX!

**Comment by sp4xkb** [comment]
Now it is logging in correctly.

TNX

**Comment by hp3icc** [comment]
to solve the problem of connection to BM, after compiling, delete the executable MMDVMHost and replace the file with version 20200924 and it worked perfectly well

rm MMDVMHost 
wget http://ysf-hp3icc.ddns.net/hp3icc/MMDVMHost
chmod +x MMDVMHost
./MMDVMHost MMDVM.ini

M: 2020-12-09 14:31:32.628 MMDVMHost-20200924 is running
D: 2020-12-09 14:31:42.757 DMR, Sending authorisation
D: 2020-12-09 14:31:42.874 DMR, Sending configuration
M: 2020-12-09 14:31:42.997 DMR, Logged into the master successfully

**Comment by do1vm** [comment]
This is a downgrade. We want the new Version 20201209. This connects perfectly to Brandmeister. I don't compile the new Version and download the old Binary :-)  This is stupid....

**Comment by hp3icc** [comment]
@do1vm  would be stupid to wait for others to solve your problem, I am very sorry that my contribution as an alternative to solve the connectivity to BM does not please you, just comment on how to solve it without having to wait for an answer, or compile again from scratch.

Seeing that the developer released a new version, I decided in another memory to compile from scratch and install the new version MMDVMHost-20201209 which if it connects to BM correctly, thank you very much @g4klx  for the new corrected version

M: 2020-12-09 16:42:20.899 MMDVMHost-20201209 is running
D: 2020-12-09 16:42:31.010 DMR, Sending authorisation
D: 2020-12-09 16:42:31.118 DMR, Sending configuration
M: 2020-12-09 16:42:31.232 DMR, Logged into the master successfully
