### ISSUE TITLE
(POCSAG)ROT1 decoder for RIC 4520 and 4512

### ISSUE THREAD

**Issue by jg1uaa** [g4klx/MMDVMHost#668]
sometimes there is something encrypted POCSAG message in RIC 4520 and 4512 for example (at DAPNETGateway log):

```
D: 2020-12-14 11:00:40.154 Queueing message to 0004520, type 6, func Alphanumeric: "["EBQOFU.Dpsf!Tubut!!!QsjwNtht;2279!Ofxt;68:Opeft;80:!UYt;73103283"
D: 2020-12-14 11:03:01.253 Queueing message to 0004512, type 6, func Alphanumeric: "1[*Tubujtujlfo"
```
I am testing a code to decode like this (at MMDVMHost log)

```
D: 2020-12-14 11:00:54.867 Message to 0004520, func Alphanumeric: (60-2) "DAPNET-Core Stats   PrivMsgs:1168 News:579Nodes:7/9 TXs:620/2172"
D: 2020-12-14 11:03:01.259 Message to 0004512, func Alphanumeric: (60) "Statistiken"
```

Is this feature required?  Here is the code https://github.com/jg1uaa/MMDVMHost/commit/f19fb3bc9bcf8b04be4e21ba182620c5a6afe726

**Comment by g4klx** [comment]
I think this feature is required, but I'd like to implement it in another way. I will use a lot of your code, but in a different overall structure. I won't use C++ streams either, they add bloat and are inefficient.

**Comment by jg1uaa** [comment]
no problem to use/rewrite my code and idea. My goal is display decoded ROT1 message to OLED.
I want to use std::to_string() but gcc-C++0x cannot handle it so I wrote C++ stream reluctantly.

**Comment by g4klx** [comment]
I’ve pushed my version of your changes. I suppose they need some more work for displaying the data, but I think you can see how my version works.


Sent from Yahoo Mail for iPhone


On Monday, December 14, 2020, 12:18, SASANO Takayoshi <notifications@github.com> wrote:




no problem to use/rewrite my code and idea. My goal is display decoded ROT1 message to OLED.
I want to use std::to_string() but gcc-C++0x cannot handle it so I wrote C++ stream reluctantly.

**Comment by jg1uaa** [comment]
I looked OLED could display decoded data but rublic index is not shown.
Is there any good way to pass that value?

For example, simply keep (undecode) first two or three letters for RIC 4520/4512 and decode them by display driver itself.

**Comment by jg1uaa** [comment]
#669 has merged, close this issue. Thanks
