### ISSUE TITLE
Assertion `!port.empty()' failed

### ISSUE THREAD

**Issue by will-caruana** [g4klx/MMDVMHost#670]
I have a fresh install of Raspbian on my Pi. I installed the software and set up a config file. When I try to run it I get an error.

```
./MMDVMHost config.ini
MMDVMHost: Modem.cpp:207: CModem::CModem(const string&, bool, bool, bool, bool, unsigned int, unsigned int, bool, bool, bool): Assertion `!port.empty()' failed.
Aborted
```
Other then git I haven't installed anything else on the Pi.

**Comment by g4klx** [comment]
It looks like you have no value for the Port in the [Modem] section.
    On Thursday, 17 December 2020, 00:38:34 GMT, will-caruana <notifications@github.com> wrote:  
 
 


I have a fresh install of Raspbian on my Pi. I installed the software and set up a config file. When I try to run it I get an error.
./MMDVMHost config.ini
MMDVMHost: Modem.cpp:207: CModem::CModem(const string&, bool, bool, bool, bool, unsigned int, unsigned int, bool, bool, bool): Assertion `!port.empty()' failed.
Aborted

Other then git I haven't installed anything else on the Pi.

**Comment by will-caruana** [comment]
That was it thank you
