### ISSUE TITLE
MMDVMHost did not read DMRIds.dat

### ISSUE THREAD

**Issue by dl7ata** [g4klx/MMDVMHost#672]
Hi folks,

anybody else with that problem, that the current version of MMDVMHost did not read DMRIds.dat?

I: 2020-12-23 08:42:47.900     Mapping File: /opt/mmdvm/RSSI.dat.HAT
I: 2020-12-23 08:42:47.906 Loaded 14 RSSI data mapping points from /opt/mmdvm/RSSI.dat.HAT
I: 2020-12-23 08:42:47.906 DMR Id Lookups
I: 2020-12-23 08:42:47.906     File: /opt/mmdvm/DMRIds.dat
I: 2020-12-23 08:42:47.906     Reload: 24 hours
I: 2020-12-23 08:43:07.215 Loaded 1 IDs to lookup table - /opt/mmdvm/DMRIds.dat

The file is the same one which can be read by older versions of MMDVMHost.

**Comment by SkyAndy** [comment]
My recommendation to try the following. Create a new file with the old and another with new syntax.

OLD syntax:
filename: DMRIds.dat
2621053 DO7EN Andreas

NEW syntax:
filename: dmrid.dat 
2621053;DO7EN;

URLs:
OLD:
https://ham-digital.org/status/users.csv

NEW:
https://database.radioid.net/static/user.csv
https://database.radioid.net/static/dmrid.dat (ready to use)

download it and rename :)

**Comment by SA7BNT** [comment]
> Hi folks,
> 
> anybody else with that problem, that the current version of MMDVMHost did not read DMRIds.dat?
> 
> I: 2020-12-23 08:42:47.900 Mapping File: /opt/mmdvm/RSSI.dat.HAT
> I: 2020-12-23 08:42:47.906 Loaded 14 RSSI data mapping points from /opt/mmdvm/RSSI.dat.HAT
> I: 2020-12-23 08:42:47.906 DMR Id Lookups
> I: 2020-12-23 08:42:47.906 File: /opt/mmdvm/DMRIds.dat
> I: 2020-12-23 08:42:47.906 Reload: 24 hours
> I: 2020-12-23 08:43:07.215 Loaded 1 IDs to lookup table - /opt/mmdvm/DMRIds.dat
> 
> The file is the same one which can be read by older versions of MMDVMHost.

Change the DB adress in 
https://github.com/g4klx/MMDVMHost/blob/02141f55ff8b268bfa39c5a16df58a681abf0b84/linux/DMRIDUpdate.sh#L56
to
https://database.radioid.net/static/user.csv

After this im getting 

> I: 2020-12-26 01:10:36.604 DMR Id Lookups
I: 2020-12-26 01:10:36.604     File: /home/pi/DMRIds.dat
I: 2020-12-26 01:10:36.604     Reload: 24 hours
I: 2020-12-26 01:10:38.888 Loaded 181980 IDs to lookup table - /home/pi/DMRIds.dat
I: 2020-12-26 01:10:38.888 DMR RF Parameters

**Comment by dl7ata** [comment]
Thanks SkyAndy, the line
`curl ${DATABASEURL} 2>/dev/null | sed -e 's/\t//g' | awk -F"," '/,/{gsub(/ /, "", $2); printf "%s\t%s\t%s\n", $1, $2, $3}' | sed -e 's/\(.\) .*/\1/g' > ${DMRIDPATH}/DMRIds.tmp
NUMOFLINES=$(wc -l ${DMRIDPATH}/DMRIds.tmp | awk '{print $1}')
`
was different than the previuos and MMDVMHost is now more sensitive when there is a different format.
Everything works now as it should - merry Christmas!
