### ISSUE TITLE
DMR ID witt ESSID don't fits to HD44780 layouts

### ISSUE THREAD

**Issue by soosp** [g4klx/MMDVMHost#711]
The layouts in HD44780.layouts file assume than the DMR ID is 7 digit, but on Bandmeiser network these IDs are 9 digit length because of the ESSID. So the ESSID goes to the start of the next line (marked with E below).
```
 With clock                Without clock
 ----------                -------------

  0         1               0         1
  01234567890123456479      01234567890123456789
 +--------------------+    +--------------------+
0|AAAAAA       NNNNNNN|   0|AAAAAA       NNNNNNN|
1|EE    DD/MM/YY      |   1|EE                  |
2|      HH:MM:SS      |   2|                    |
3|MMDVM           Idle|   3|MMDVM           Idle|
 +--------------------+    +--------------------+
```

**Comment by KE7FNS** [comment]
> My version is Pi-Star: 4.1.5 / Dashboard: 20210721. I upgraded it by Dashboard update menu.

Pi-Star runs an older version of MMDVMHost that has been deemed stable by the Pi-Star team.  Andy hasn't fully tested and released the latest MMDVMHost code to all the Pi-Star users yet, it will come at some point in the future, but I do not know when.

Also, your DMR ID is invalid, and I don't think your callsign is valid either.  I question if you are actually licensed.

@g4klx you might just want to close this report as the latest MMDVMHost code  correctly trims the DMR ID to 7 characters, I tested it earlier tonight when I made my recent changes to HD44780.cpp.

**Comment by soosp** [comment]
> Pi-Star runs an older version of MMDVMHost that has been deemed stable by the Pi-Star team. Andy hasn't fully tested and released the latest MMDVMHost code to all the Pi-Star users yet, it will come at some point in the future, but I do not know when.

Thank you for investigating this. I close the issue.
