### ISSUE TITLE
Analog FM mode in /var/log/pi-star/   

### ISSUE THREAD

**Issue by ON2ON-HAM** [g4klx/MMDVMHost#730]
Hi,

FM mode is working superb, no hickups, none whatsoever ;)
The only thing i do not see, is on the Pi-star dash, that the 'listening' cage, switches from Listening to DMR etc..., but to FM,
The FM is not shown, it stays on Listening even when FM Analog is active.

Any way to overcome this ?

Thanks for a great job !

ON2ON Luke
Repeater Club Antwerp

**Comment by g4klx** [comment]
This is a Pi-Star issue not with the base MMDVM Host. Please ask on the Pi-Star forum.
