### ISSUE TITLE
Support for I2C cheap display PCF8574

### ISSUE THREAD

**Issue by Giorgiofox** [g4klx/MMDVMHost#74]
Maybe can be a good idea integrate support for I2C display based on PCF8574 (very cheap)
( For example:
http://www.ebay.com/itm/IIC-I2C-TWI-SP-I-Serial-Interface1602-16X2-Character-LCD-Module-Display-Blue-/310565065847?hash=item484f1ed477:g:mPQAAOSwofxUhQre )

This code work, need to be integrated in HD4478.cpp and .h

import wiringpi2 as wiringpi

wiringpi.wiringPiSetupSys();

af_base = 100

af_rs = af_base + 0
af_e = af_base + 2
af_db4 = af_base + 4
af_db5 = af_base + 5
af_db6 = af_base + 6
af_db7 = af_base + 7

af_backlight = af_base + 3

def backlight_on():
    wiringpi.digitalWrite(af_backlight, 1)

def backlight_off():
    wiringpi.digitalWrite(af_backlight, 0)

wiringpi.pcf8574Setup(af_base, 0x27)

lcd_handle = wiringpi.lcdInit(4, 20, 4, af_rs, af_e, af_db4, af_db5, af_db6, af_db7, 0, 0, 0, 0)

backlight_on()

wiringpi.lcdPrintf(lcd_handle, "Hello World!")

**Comment by g0wfv** [comment]
Just looking at this, looks like it would need a very similar change to the one that was made for the Adafruit.  Didn't you do that one, Giorgio?

**Comment by Giorgiofox** [comment]
Hi,
Excuse me for delay, really busy at Friedrischafen :)
No, Actually I don't did it. For sure is a good idea use another makefile for these displays.

**Comment by g0wfv** [comment]
Hope you enjoyed FHN!

Looking back, so you didn't - I can't see who did, as it just says 'root' and doesn't link to a git profile!

Fairly sure the way you say could be done though.  I don't know if anyone has one of these screens though?  I've only written for the screen I have and a bit for the Nextion which is easily tested as most people are using them!

I can try to add something, but I won't be able to test it!

I've just had a look at the wiringPi site for the support for this chipset/LCD, and the code differs fro that which you quote above - can you point me to where you got that code please?

**Comment by g0wfv** [comment]
Ahhhh don't worry!  The code you quoted is Python!  I shall find something appropriate in C++

**Comment by g0wfv** [comment]
Giorgio, 

As this is working now, can you close the issue please?  (Bare in mind I have some additions in my develop repo still waiting to be tested if you get to them before I receive my own LCD!)

Cheers,
Tony

**Comment by Giorgiofox** [comment]
Thank you Jonathan

73
Giorgio

2016-07-01 15:50 GMT+02:00 Jonathan Naylor <notifications@github.com>:

> Closed #74 <https://github.com/g4klx/MMDVMHost/issues/74>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/g4klx/MMDVMHost/issues/74#event-710516691>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABsBD5YscpIvBshILg0QHC6AyXeh-4QWks5qRRsmgaJpZM4IhpzL>
> .
>



-- 
Giorgio
giorgiofox@gmail.com
Secure: giorgiofox@protonmail.ch
Ham: iz2xbz@aribrescia.it
