### ISSUE TITLE
FM enabled in the host but not in the modem firmware, disabling

### ISSUE THREAD

**Issue by iddq** [g4klx/MMDVMHost#743]
Hello,

Can you please help me what can be the reason to get this message after MMDVHost upgrade?

W: 2022-03-04 23:00:36.070 FM enabled in the host but not in the modem firmware, disabling

**Comment by W0CHP** [comment]
Exactly what it says: you need to update or compile the modem firmware for FM support.

**Comment by iddq** [comment]
It has FM support it works with FM.

**Comment by iddq** [comment]
the protocol changed between host and mmdvm. see CModem::setConfig
