### ISSUE TITLE
 No reply from the modem for some time, resetting it

### ISSUE THREAD

**Issue by YV5OF** [g4klx/MMDVMHost#77]
Hi Team,

Since the last two updates, I have been experiencing more recurrent the resetting.Today I had this resetting, at least 5 times, on two occasions being totally in a loop.

I did a re-flash firmware to discard, but the resetting is maintained at random.

**Partial log :** 

E: 2016-05-28 00:13:34.465 No reply from the modem for some time, resetting it
M: 2016-05-28 00:13:34.466 Closing the MMDVM
M: 2016-05-28 00:13:36.466 Opening the MMDVM
I: 2016-05-28 00:13:38.477 MMDVM protocol version: 1, description: DVMEGA HR2.28
E: 2016-05-28 00:13:38.497 Connection to the master has timed out, retrying connection
M: 2016-05-28 00:13:38.497 Closing DMR IPSC
M: 2016-05-28 00:13:44.469 Opening DMR IPSC
M: 2016-05-28 00:14:01.511 Logged into the master successfully

**Comment by YV5OF** [comment]
More log  : 

I: 2016-05-28 02:20:24.378 Loaded 35206 DMR Ids to the callsign lookup table
M: 2016-05-28 02:20:24.379 MMDVMHost-20160527 is running
M: 2016-05-28 02:20:36.409 Logged into the master successfully
E: 2016-05-28 05:29:51.080 No reply from the modem for some time, resetting it
M: 2016-05-28 05:29:51.080 Closing the MMDVM
M: 2016-05-28 05:29:53.098 Opening the MMDVM
I: 2016-05-28 05:29:55.108 MMDVM protocol version: 1, description: DVMEGA HR2.28
E: 2016-05-28 07:19:58.699 No reply from the modem for some time, resetting it
M: 2016-05-28 07:19:58.699 Closing the MMDVM
M: 2016-05-28 07:20:00.712 Opening the MMDVM
I: 2016-05-28 07:20:02.722 MMDVM protocol version: 1, description: DVMEGA HR2.28
E: 2016-05-28 09:39:58.186 No reply from the modem for some time, resetting it
M: 2016-05-28 09:39:58.186 Closing the MMDVM
M: 2016-05-28 09:40:00.197 Opening the MMDVM
I: 2016-05-28 09:40:02.208 MMDVM protocol version: 1, description: DVMEGA HR2.28
E: 2016-05-28 11:01:52.840 No reply from the modem for some time, resetting it
M: 2016-05-28 11:01:52.840 Closing the MMDVM
M: 2016-05-28 11:01:54.851 Opening the MMDVM
I: 2016-05-28 11:01:56.862 MMDVM protocol version: 1, description: DVMEGA HR2.28

**Comment by g0wfv** [comment]
MMDVMHost is seemingly unable to read from the DVMega every couple of hours which it seems to recover from gracefully as it is supposed to.  Whilst the recovery is expected behaviour, the loss of connectivity with the DVMega is not.  Is this still an ongoing issue?

If so, I will turn logging on and monitor mine to see if it's the same but as far as I am aware mine is running with no adverse issues (DVMega, MMDVMHost, RPi B+)

Also some further log detail of what is going on at or about the time the host loses connectivity wouldn't go amiss.

**Comment by YV5OF** [comment]
Hi Tony,

After applying the two last commit the MMDVMHost not recurred. I have been monitoring for 72 hours without problems.

I tested internet disconnect and reconnect, everything so far no news. Apply the new firmware (2.29) to DVMEGA, and everything is working perfect.

I'll close the report, and if it reappears taketh more details.

Thank's
