### ISSUE TITLE
no CW-Id, m_cwIdTImer not started

### ISSUE THREAD

**Issue by Boromatic** [g4klx/MMDVMHost#79]
Hello,

the software does never send the CW-Id because the timer "m_cwIdTimer" is only started in case of MODE_ERROR or MODE_LOCKOUT. See lines 938 et seq. in MMDVMHost.cpp

		if (m_mode == MODE_ERROR || m_mode == MODE_LOCKOUT) {
			m_modem->sendCWId(m_callsign);
			m_cwIdTimer.start();

Sorry I can't write a patch because I'm to busy today to test it after writing.

Best wishes!

**Comment by g4klx** [comment]
Thanks for that. I'll check it out in a few days when I get back to developing.

Jonathan G4KLX

**Comment by Boromatic** [comment]
I've found some time to write :-) See the pull request.

72
