### ISSUE TITLE
MMDVMHost: UDPSocket...error

### ISSUE THREAD

**Issue by labdvm** [g4klx/MMDVMHost#793]
Hi, just recompiled latest MMDVMHost and I get this error:
MMDVMHost: UDPSocket.cpp:224: int CUDPSocket::read(unsigned char*, unsigned int, sockaddr_storage&, unsigned int&): Assertion `m_fd >= 0' failed.

What should I do ?
73, Z32IT

**Comment by overnite** [comment]
I have the exact same issue

**Comment by labdvm** [comment]
> I have the exact same issue

I have recompiled one backward version and works ok.

**Comment by g4klx** [comment]
Maybe providing a copy of your log file and/or your configuration file would be a good start.
    On Wednesday, 31 January 2024 at 20:59:22 GMT, labdvm ***@***.***> wrote:  
 
 


Hi, just recompiled latest MMDVMHost and I get this error:
MMDVMHost: UDPSocket.cpp:224: int CUDPSocket::read(unsigned char*, unsigned int, sockaddr_storage&, unsigned int&): Assertion `m_fd >= 0' failed.

What should I do ?
73, Z32IT

**Comment by g4klx** [comment]
In the absence of any logs or a configuration file, I have looked around the source code and made some changes which may help. If you build from the latest sources, which are dates 20240201 and see if that helps. I was unable to reproduce it here with my system.

**Comment by labdvm** [comment]
> In the absence of any logs or a configuration file, I have looked around the source code and made some changes which may help. If you build from the latest sources, which are dates 20240201 and see if that helps. I was unable to reproduce it here with my system.

OK, I will recompile today version.

**Comment by labdvm** [comment]
OK, 20240201 works !

**Comment by overnite** [comment]
Excellent, just did it and now have it workingThanksBryanSent from my iPhoneOn Feb 1, 2024, at 2:37 PM, Jonathan Naylor ***@***.***> wrote:﻿
In the absence of any logs or a configuration file, I have looked around the source code and made some changes which may help. If you build from the latest sources, which are dates 20240201 and see if that helps. I was unable to reproduce it here with my system.
