### ISSUE TITLE
FMNetwork.h include samplerate.h: no such file

### ISSUE THREAD

**Issue by es2ast** [g4klx/MMDVMHost#794]
make -f Makefile.Pi.OLED
samplerate.h no such file

![pilt](https://github.com/g4klx/MMDVMHost/assets/38312339/a7dc410f-6318-4ba1-97a0-c9f162b0b753)

**Comment by labdvm** [comment]
Try with this:
 sudo apt-get install -y libsamplerate0 libsamplerate0-dev

**Comment by es2ast** [comment]
Thanks.
