### ISSUE TITLE
HD44780 display, TS1 no data

### ISSUE THREAD

**Issue by ik1whn** [g4klx/MMDVMHost#82]
Letest version of MMDVMHost, display HD44780 4x20 does not display any data for ts1, both from RF and network, I only see dmr label scrolling.
Ts2 instead it appears correctly.
Mauri ik1whn

**Comment by g0wfv** [comment]
I've probably introduced a bug. I'll have a look tomorrow evening (flying
back from abroad tomorrow morning and all packed right now!)

On Sun, 5 Jun 2016, 19:19 ik1whn, <notifications@github.com> wrote:

> Letest version of MMDVMHost, display HD44780 4x20 does not display any
> data for ts1, both from RF and network, I only see dmr label scrolling.
> Ts2 instead it appears correctly.
> Mauri ik1whn
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/g4klx/MMDVMHost/issues/82>, or mute the thread
> <https://github.com/notifications/unsubscribe/AQf_4vzVUgvknN4G6HJ0j3T5Y-k2nUkfks5qIvcPgaJpZM4IuY3M>
> .
>
-- 

A J Corbett

G0WFV

**Comment by iw9grl** [comment]
I confirm the same issue, also during Idle, some scrolling appear over the Clock !!!!

**Comment by g0wfv** [comment]
Gents,

I've added a few more lines of code that will hopefully solve the issues
(if I have understood them right!)

I've created a PR to Jon's code but if you would like to test before he
merges, the code can be found in the develop branch of my fork ...
https://github.com/g0wfv/MMDVMHost/tree/develop

Regards,
Tony

On Sun, Jun 5, 2016 at 5:31 PM iw9grl <notifications@github.com> wrote:

> I confirm the same issue, also during Idle, some scrolling appear over the
> Clock !!!!
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/g4klx/MMDVMHost/issues/82#issuecomment-223822688>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AQf_4v4lGq_4ItEFdhrQseohQfwLbbWFks5qIvnPgaJpZM4IuY3M>
> .
>
-- 

A J Corbett

G0WFV

**Comment by g0wfv** [comment]
PR now merged - please test and report back here if all OK.

I will be unable to test TS1 myself even if I get a 20x4 screen, as I run a
DVMega (slot 2 only!) so I need your feedback with as much info as
possible, preferably with a video of what's going on?

Perhaps I should build a full MMDVM repeater HIHI!

On Sun, Jun 5, 2016 at 7:10 PM Tony Corbett <tonyc.uk@gmail.com> wrote:

> Gents,
>
> I've added a few more lines of code that will hopefully solve the issues
> (if I have understood them right!)
>
> I've created a PR to Jon's code but if you would like to test before he
> merges, the code can be found in the develop branch of my fork ...
> https://github.com/g0wfv/MMDVMHost/tree/develop
>
> Regards,
> Tony
>
> On Sun, Jun 5, 2016 at 5:31 PM iw9grl <notifications@github.com> wrote:
>
>> I confirm the same issue, also during Idle, some scrolling appear over
>> the Clock !!!!
>>
>> —
>> You are receiving this because you commented.
>>
>>
>> Reply to this email directly, view it on GitHub
>> <https://github.com/g4klx/MMDVMHost/issues/82#issuecomment-223822688>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AQf_4v4lGq_4ItEFdhrQseohQfwLbbWFks5qIvnPgaJpZM4IuY3M>
>> .
>>
> --
>
> A J Corbett
>
> G0WFV
>
-- 

A J Corbett

G0WFV

**Comment by ik1whn** [comment]
Now work thanks

**Comment by iw9grl** [comment]
confirm now it works. thank you
