### ISSUE TITLE
Add Connection Status To IDLE page on Nextion Display

### ISSUE THREAD

**Issue by zs5cey** [g4klx/MMDVMHost#93]
Hi, Is it possible to have some status message on the "Idle" page on the LCD screen that shows whether the host is connected to a network server for quick connection diagnostics?

Thanks
Andy

**Comment by g0wfv** [comment]
Something I'm planning to work on and has been discussed previously - It
will be DMR only, as the network connection for YSF and DStar are both
dealt with by other software packages (YSFGateway and ircddbgateway
respectively)

On Sat, Jun 11, 2016 at 5:54 PM Andy <notifications@github.com> wrote:

> Hi, Is it possible to have some status message on the "Idle" page on the
> LCD screen that shows whether the host is connected to a network server for
> quick connection diagnostics?
>
> Thanks
> Andy
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/g4klx/MMDVMHost/issues/93>, or mute the thread
> <https://github.com/notifications/unsubscribe/AQf_4lf-72-9hNWDxzN69lg9FQXFh8ucks5qKugugaJpZM4Izl2s>
> .
>
-- 

A J Corbett

G0WFV

**Comment by zs5cey** [comment]
Great thanks - no important, more a nice to have.

**Comment by g0wfv** [comment]
Still thinking on this one .....

**Comment by zs5cey** [comment]
Nof a show stopper, so not a rush.


Get Outlook for Android






On Fri, Jun 24, 2016 at 6:55 PM +0200, "Tony Corbett" <notifications@github.com> wrote:












Still thinking on this one .....
